### DISCUSSION TITLE
Default to patch release

### DISCUSSION THREAD

**Discussion by vishnusraju** [semantic-release/semantic-release#1819] [Configuration]
Hi, We in our team are trying to automate release process and would like to set the default commit to have a patch release. Found some  few similar issues [(Isue 162)](https://github.com/semantic-release/commit-analyzer/issues/162) and tried the different options. it did not help. Below is the .releaserc.yml used for deploy.

It works fine while following the commit conventions. But all other mesages are pretty much ignored even after updating the file as below:
```
plugins:
- "@semantic-release/commit-analyzer"
- releaseRules:
  - type: "demo"
    release: patch
  - message: "*"
    release: patch
  - subject: "*"
    release: patch
- "@semantic-release/release-notes-generator"
- - "@semantic-release/exec"
  - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
- "@semantic-release/gitlab"

branches:
- "master"
- "+([0-9])?(.{+([0-9]),x}).x"
- name: "alpha"
  prerelease: "alpha"
```
