### DISCUSSION TITLE
Azure Repos Authentication from Azure Pipelines

### DISCUSSION THREAD

**Discussion by oarm14** [semantic-release/semantic-release#1851] [Configuration] [answered]
Hello,
I've been having a hard time getting Semantic-Release to authenticate back to my Azure Repos instance for the push.  I'm wondering if anyone has had similar issues or if this is altogether not supported.

I am trying to make this work for Java repositories so I've taken out the npm plugin in the releaserc and Semantic Release is installed globally on my CI server. It is a  Windows Server that has a build agent installed.

My .releaserc file looks like this (using a feature branch to test this out instead of master for now).  This is a Java repo as well 

```
{
"branches": ["feature/semantic-release"],
"plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/exec",
    ["@semantic-release/git", {
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]
  
    ]
}
```

In my pipeline yaml, after the build and tests I call Semantic Release via the command line and try to pass in the default user and system token that allows pipelines to access repos.  "username" isn't what is actually used.  I've just changed that to make this generic.

```
- task: CmdLine@2
        displayName: Semantic Release
        inputs:
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          script: 'semantic-release --GIT_CREDENTIALS username:SYSTEM_ACCESSTOKEN'
```
I have also tried it like this with the actual variable being passed in.
```
- task: CmdLine@2
        displayName: Semantic Release
        inputs:
          env:
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
          script: 'semantic-release --GIT_CREDENTIALS username:$(System.AccessToken)'
```
I'd love to have your opinion on what I might be getting wrong.

Thanks!

**Comment by bigbrozer** [comment, marked as answer]
Hi @oarm14, in order to perform git operations (commits and tags for semantic-release), you need to give access to the `SYSTEM_ACCESSTOKEN` during the [checkout](https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#checkout) step like this:

```yaml
steps:
  - checkout: self
    persistCredentials: true
```

Then, configure the git user identity with something like:

```yaml
- bash: |
    git config --global user.email "foobar@example.com"
    git config --global user.name "Foo BAR"
  displayName: "🤷‍♂️ Set git identity"
```

Verify also that the **Build Service Accounts** running your CI has proper permissions on the git repository (Create tags, Contribute, ...).

Semantic release will work like a charm after that :smile:.
