### DISCUSSION TITLE
Dry-run in CI environment from pull request branch

### DISCUSSION THREAD

**Discussion by XC-** [semantic-release/semantic-release#1886] [Q&A]
Hi,

I have been trying to do a semantic-release simulation as a part of the pull request workflow, but bump into issues with the configuration. The configuration for the repository has the following branches configuration:
`  "branches": ["main"]`

Then in the workflow job, I am running semantic-release with the following command:
`npx semantic-release --dry-run --no-ci --branches $GITHUB_REF`
in hope that it would do the dry-run from the pull request branch github action has checked out. However,  I run into the following error:
`[4:05:39 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].`

What am I missing or configuring wrong?

**Comment by latipun7** [comment]
Hey, this is what I'm trying to do too, haha 😅 I want to test the `semantic-release` simulation in the pull request workflow.

I was trying to do `npx semantic-release  --no-ci --branches "$GITHUB_HEAD_REF" --dry-run` instead, but the error is, well, it's not an error, but the test is skipped with this message:
```
[12:49:46 PM] [semantic-release] › ℹ  Running semantic-release version 18.0.0
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
➤ YN0000: [12:49:46 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
➤ YN0000: [12:49:48 PM] [semantic-release] › ℹ  This test run was triggered on the branch refs/pull/375/merge, while semantic-release is configured to only publish from upgrade, therefore a new version won’t be published.
```
from that message, `refs/pull/375/merge` is the `$GITHUB_REF`, while `upgrade` is `$GITHUB_HEAD_REF`. 

Then I tried to do switch the branch first:
```
git switch "$GITHUB_HEAD_REF"
npx semantic-release  --no-ci --branches "$GITHUB_HEAD_REF" --dry-run
```
but the ref still persist to `refs/pull/375/merge`, maybe the refs is always persisted to `refs/pull/:prNumber/merge` no matter what I do based on the [github actions documentation](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull_request).

I hope there's some workaround.  🤔

**Comment by seedy** [comment]
In case you're still looking for a workaround, here's what I did with github actions:

> Hey folks, I found a workaround to go forward on the subject :rocket: 
>
> I'm still struggling with the dry run output, though. I still don't know how to output it inside my PRs to make it useful...

> To summarize:
> 1. I added a branch name in my release branches list, which is dedicated to dry-run
> 2. I am creating that branch on my repository only for the duration of my workflow, then deleting it (I took whatever github action I found for this :shrug: )
> 3. I run the command proposed by @guilhermetod to ignore GH actions data
>
> Here's my package.json part containing my branches:
> ```
>   "branches": [
>       "main",
>       "next",
>       "dry"
>     ],
> ```
>
> ...aaaaaaaaand, here's my workflow (I removed sensitive data):
> ```
> name: Pull Request
>
> 
> on:
>   pull_request:
> 
> jobs:
>   test-semantic-release:
>     name: Release dry-run
>     runs-on: ubuntu-latest
>     steps:
>       - name: Checkout code
>         uses: actions/checkout@v2
> 
>       - name: Create dry branch
>         uses: peterjgrainger/action-create-branch@v2.0.1
>         env:
>           GITHUB_TOKEN: ${{ SECRET }}
>         with:
>           branch: 'dry'
> 
>       - name: Checkout dry branch
>         uses: actions/checkout@v2
>         with:
>           ref: dry
>       
>       - name: Setup Node.js
>         uses: actions/setup-node@v2
>         with:
>           node-version: 'lts/*'
> 
>       - name: Install dependencies
>         run: npm ci
> 
>       - name: Dry run
>         env:
>           GITHUB_TOKEN: ${{ SECRET }}
>           NPM_TOKEN: ${{ SECRET }}
>         run: unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci
>       
>       - name: Back to code
>         uses: actions/checkout@v2
>       
>       - name: Clear dry branch
>         uses: dawidd6/action-delete-branch@v3
>         with:
>           github_token: ${{SECRET}}
>           branches: dry
> ```
> 
> Last missing steps:
> 
> - I'd like to output the result of the dry-run to my PR, I'm thinking about adding a comment to the PR through `actions/github-script@v6`
> 

I commented on this [issue](https://github.com/semantic-release/semantic-release/issues/1890#issuecomment-1043141978)

**Comment by bigbrozer** [comment]
Hi ! That's what I'm doing for PR dry-run (using Azure DevOps but others may be similar):

```bash
# Bash tricks to substitute part of a string...
--branches "${SOURCE_BRANCH#refs/heads/}"
```

I'm removing the `refs/heads/` part in the branch name. It appears, semantic-release is looking at the branch name on the remote (similar to your local `git branch`). It works but looks like a workaround ;-)

**Comment by armandsauzay** [comment]
Hi! Any luck on this using github actions with `pull_request` trigger? I can't seem to find the way to get the dry run to work on pull_request only trigger

**Comment by armandsauzay** [comment]
Not sure if it's ideal but got it to work with the following script. Curious if anyone has a better solution!

```
name: Scratch

on:
  pull_request:
      branches:
          - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with :
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Set up Node.js
        uses: actions/setup-node@v3          
      - name: Semantic Release dry run
        id: dry-release
        run: |
          OUTPUT="$(bash -c "unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci --branches '${HEAD_REF}'")"
          NEW_RELEASE_VERSION=$(echo "$OUTPUT" | grep -oP 'The next release version is \K(\d+\.\d+\.\d+)')
          echo "new-release-version=$NEW_RELEASE_VERSION" >> "$GITHUB_OUTPUT"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_REF: ${{ github.head_ref }}
      - name: Use the version
        run: echo "The version is ${{ steps.dry-release.outputs.new-release-version }}"
```

**Comment by diogokiss** [comment]
The following snippet did the trick for me.

```
      - name: Generate release notes
        id: release-notes-preview
        run: |
          # Trick semantic-release into thinking we're not in a CI environment
          unset GITHUB_ACTIONS
          unset GITHUB_EVENT_NAME

          semantic-release --dry-run --no-ci --branches $GITHUB_HEAD_REF
```

I based this solution on the library that semantic-release uses to detect CI environments: [env-ci](https://github.com/semantic-release/env-ci).
https://github.com/semantic-release/env-ci/blob/master/services/github.js#L39-L62

**Comment by tinyroy** [comment]
Like the above workarounds, I tricked semantic versioning into thinking it is running against a regular branch, "dryrun" but it is actually the pull request reference "refs/pull/${prNumber}/merge". 

The code below creates the "dryrun" branch, tricks semantic-release by setting GITHUB_REF and finally deletes the branch.

Make sure "dryrun" branch is in your .releaserc configuration.

```      
      - name: Create Dryrun Branch
        run: |
          git checkout -b dryrun
          git push --set-upstream origin dryrun -f

      - name: Dryrun Release
        run: GITHUB_REF=dryrun npx semantic-release --dry-run --no-ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Dryrun Branch
        run: |
          git push --delete origin dryrun
```

**Comment by Avivbens** [comment]
# Hi all 👋 

**I've created a nice GitHub action workflow, with no additional configuration needed 👍** 

### Here are the workflow results for `chore` commit:
![CleanShot 2024-01-19 at 22 40 23@2x](https://github.com/semantic-release/semantic-release/assets/77183871/9f4e2f9f-7a6a-44ca-b606-c758e11286f7)


### Once you committed additional stuff, it will remove the last report and create a new one. Here are the results for `fix` commit:
![CleanShot 2024-01-19 at 22 41 17@2x](https://github.com/semantic-release/semantic-release/assets/77183871/82b64078-e404-4f76-9c45-54d791a5ad25)



### The workflow:
```---
name: Semantic Release Check 📝
on:
    pull_request:
        branches:
            - master

permissions: write-all

jobs:
    PR-checks:
        runs-on: self-hosted
        name: Semantic Release Check 📝
        steps:
            - name: 📀 Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 🖥️ Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: 🔗 Install Dependencies
              shell: bash
              run: |
                  npm ci --no-fund --no-audit --ignore-scripts

            - name: 🔬 Check semantic versioning
              id: semantic-release
              run: |
                  GITHUB_REF=${{ github.head_ref }}
                  npx semantic-release --no-ci --dry-run --plugins @semantic-release/commit-analyzer,@semantic-release/release-notes-generator --branches ${{ github.head_ref }} > output.txt
                  OUTPUT=$(cat output.txt | base64 -w 0)
                  echo "::set-output name=releaseNote::$OUTPUT"

            - name: 📝 Report semantic versioning
              uses: actions/github-script@v3
              if: ${{ steps.semantic-release.outputs.releaseNote != '' }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      // build release note
                      const semanticReleaseOutput = Buffer.from('${{ steps.semantic-release.outputs.releaseNote }}', 'base64').toString('utf8');
                      const semanticReleaseLogMatch = /^[[0-9:\sAMPM]+\]\s\[semantic-release\].*$/;
                      const lines = semanticReleaseOutput.split('\n');
                      const lastSemanticReleaseLogIndex = [...lines]
                          .reverse()
                          .findIndex((line) => line.match(semanticReleaseLogMatch));

                      const releaseNoteIndex = lines.length - lastSemanticReleaseLogIndex;
                      const releaseNote = lines.slice(releaseNoteIndex);

                      let res = releaseNote.join('\n');
                      if (!releaseNote.length || !res) {
                          res = '### No release note would be generated.';
                      }

                      const SEMANTIC_RELEASE_BODY_HEADER = '## 📝 Semantic Release Report';
                      const body = [SEMANTIC_RELEASE_BODY_HEADER, res].join('\n');

                      // get last comment
                      const comments = await github.issues.listComments({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo
                      });

                      // find comments to delete
                      const commentsToDelete = comments.data.filter((comment) =>
                          comment.body.startsWith(SEMANTIC_RELEASE_BODY_HEADER)
                      );

                      // delete comments
                      const prms = commentsToDelete.map((comment) =>
                          github.issues.deleteComment({
                              comment_id: comment.id,
                              owner: context.repo.owner,
                              repo: context.repo.repo
                          })
                      );

                      await Promise.all(prms);

                      // create new comment for release note
                      github.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body
                      });

```

## **Enjoy 🥳** 


CC: @XC- @bigbrozer @diogokiss @seedy @tinyroy

**Reply by boris-ning-usds** [reply]
Thank you for this. I'm totally robbing the last two steps.

**Reply by Avivbens** [reply]
@boris-ning-usds 

Yeah, loved that report 🎉 

Have a similar one for `Nx` projects, so you can see the affected changes before merge 🤞

**Comment by Djaytan** [comment]
I made lots of experimentations for dry-run, and came up with that:

```yaml
name: Release - Dry Run

on:
  pull_request:
    branches: [ main, '+.x', beta, alpha ]

permissions: {}

jobs:
  release-dryrun:
    name: Release - Dry Run
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    permissions:
      contents: write # Necessary for semantic-release to verify Git push permissions, even during a dry run.

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Required by semantic-release
          # Use the pull request head ref (source branch) to ensure the dry run simulates a release for the current PR.
          # LIMITATION: will probably not work with pull requests from forks forbidding read accesses.
          ref: ${{ github.head_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: lts/jod
          cache: npm
          cache-dependency-path: .github/release/package-lock.json

      - name: Install semantic-release
        working-directory: .github/release/
        run: npm clean-install --engine-strict

      - name: Simulate new feature
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit --no-verify --allow-empty -m 'feat: simulate new feature'

      - name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        working-directory: .github/release/
        # Perform a dry run without publishing anything.
        #
        # Unset the `GITHUB_ACTIONS` environment variable to trick semantic-release into thinking it's not running in a CI environment,
        # as `--no-ci` alone is insufficient.
        #
        # Use `--branches "${GITHUB_HEAD_REF}"` to consider the PR head ref (source branch) as a release one for the dry run.
        run: |
          unset GITHUB_ACTIONS
          npx --no-install semantic-release --dry-run --no-ci --branches "${GITHUB_HEAD_REF}"
```

Outcome (shortned for consiceness):

> [10:22:45 AM] [semantic-release] › ℹ  Running semantic-release version 24.2.6
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[10:22:45 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[10:22:47 AM] [semantic-release] › ⚠  Run automated release from branch ci/semantic-release-dryrun on repository https://github.com/Djaytan/bukkit-slf4j in dry-run mode
[10:22:48 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[10:22:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[10:22:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[10:22:48 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[10:22:48 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com/)
[10:22:48 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[10:22:48 AM] [semantic-release] › ℹ  Found git tag v3.1.2 associated with version 3.1.2 on branch ci/semantic-release-dryrun
[10:22:48 AM] [semantic-release] › ℹ  Found 67 commits since last release
[10:22:48 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:22:48 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: simulate new feature
[10:22:48 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[10:22:48 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci: add dry-run execution of semantic-release for validation purposes
[10:22:48 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
\<snip\>
[10:22:48 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 67 commits complete: minor release
[10:22:48 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:22:48 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/exec"
[10:22:48 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/exec"
[10:22:48 AM] [semantic-release] › ℹ  The next release version is 3.2.0
[10:22:48 AM] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "@semantic-release/exec"
[10:22:48 AM] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "@semantic-release/exec"
[10:22:48 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:22:48 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:22:48 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[10:22:48 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/exec" in dry-run mode
[10:22:48 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[10:22:48 AM] [semantic-release] › ⚠  Skip v3.2.0 tag creation in dry-run mode
[10:22:48 AM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/exec" in dry-run mode
[10:22:48 AM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/github" in dry-run mode
[10:22:48 AM] [semantic-release] › ⚠  Skip step "success" of plugin "@semantic-release/exec" in dry-run mode
[10:22:48 AM] [semantic-release] › ⚠  Skip step "success" of plugin "@semantic-release/github" in dry-run mode
[10:22:48 AM] [semantic-release] › ✔  Published release 3.2.0 on default channel
[10:22:48 AM] [semantic-release] › ℹ  Release note for version 3.2.0:
> \#\# 3.2.0 (https://github.com/Djaytan/bukkit-slf4j/compare/v3.1.2...v3.2.0) (2025-08-10)
>
> \#\#\# 🌟 Features
> 
>   \* simulate new feature ([aeba783](https://github.com/Djaytan/bukkit-slf4j/commit/aeba7835f0d1a2174457b3a919854ccce96ffc4e))
>
> \#\#\# 🏗️ Build System
> 
>   \* \*\*deps:\*\* update Maven Wrapper to v3.9.10 ([#218](https://github.com/Djaytan/bukkit-slf4j/issues/218)) ([bc0ec33](https://github.com/Djaytan/bukkit-slf4j/commit/bc0ec330544fef455606b02bed804632d2e3e381))
> 
> \#\#\# ✅ Tests
> 
> \<snip\>

=> https://github.com/Djaytan/bukkit-slf4j/pull/247

⚠️ Always use `--branches "${GITHUB_HEAD_REF}"` instead of `--branch ${{ github.head_ref }}` to protect you against potential script injections (more info [here](https://securitylab.github.com/resources/github-actions-untrusted-input/)).

I fear it's not realistically possible to achieve something significantly better without enhancements on `semantic-release` side to better support dry-runs at PR level.
