### DISCUSSION TITLE
Publishing a GitHub release & triggering another workflow

### DISCUSSION THREAD

**Discussion by bdubaut** [semantic-release/semantic-release#1906] [Q&A] [answered]
Hi, I'm using semantic release in my CI pipeline (GitHub Actions), which looks like this.
<img width="1017" alt="Screenshot 2021-04-24 at 08 25 55" src="https://user-images.githubusercontent.com/798319/115949638-b285c580-a4d6-11eb-98f2-2d2af04af5a6.png">

The `Bump version` job uses semantic release to (amongst other things) generate a GitHub release after tagging.

The problem is that I want to trigger another workflow based on a new Release being published and this does not trigger, although the workflow is setup this way:
```yaml
name: Release
on:
  release:
    types: [published]
jobs:
  build_docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      # rest of the job
```

What am I doing wrong? Am I correct to assume that semantic release publishing a GitHub release should emit the `release:published` event?

**Comment by gr2m** [comment, marked as answer]
you need to use a token other than `GITHUB_TOKEN` when creating the release on GitHub. GitHub actions do not trigger other GitHub actions to avoid infinite loops. I usually create a bot user account for this use case, and save a personal access token in the org/repo secrets. But you can also register a GitHub App and then create an installation access token and pass that to semantic-release. There are actions to do that, e.g. https://github.com/marketplace/actions/action-github-app-token

**Reply by bdubaut** [reply]
Thanks !

**Reply by englut** [reply]
I have set to my PAT to `GITHUB_TOKEN` from a Github secret (along with `GH_TOKEN` for good measure), but I'm still not able to trigger a tag push event when creating a tag via semantic-release (to trigger another Github Action):
```
...
      - run: npx semantic-release
        env:
          CI: true
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
...
```
Do you know what I'm doing wrong?

**Reply by gr2m** [reply]
Was the release created on GitHub? Who is shown as the actor who created the release?

Without knowing more, I'd say your release workflow looks correct, maybe the workflow that should act on the releases is the problem?

**Reply by englut** [reply]
The tag and release is created on github, under the expected user (not github actions bot). But the github action I have set up for tag pushes was not triggered. The tag push action will trigger if I manually push a tag however.

Basically I have two github actions:
1. Triggers on all pushes to the master branch. Will run semantic-release, which will create a tag & release if there's changes that need to be released.
2. Triggers on all pushes to any tags. Takes the release and deploys it.

Right now, anything released by semantic-release (even with the my PAT) is not triggered #2 github action.

**Reply by gr2m** [reply]
I use a similar setup in a lot of projects, I don't think it's a problem with semantic release. Is the repo public? If it's not, I'd ask support at https://support.github.com/contact

**Reply by englut** [reply]
Thanks @gr2m! I'll contact Github!

**Reply by levibostian** [reply]
Putting a comment here for anyone who stumbles across this discussion looking for help...

I had the same issue as @qauff. I was noticing that when I ran semantic-release with the `@semantic-release/git` plugin to make a commit on deployment:
1. The actual commit being made was authored by the `semantic-release` user account. Not the GitHub actions bot account. This was what I expected. 
2. When I would go back to my "feed" of GitHub by logging into GitHub and going to `github.com`, my timeline told me that the `github-actions` GitHub account *pushed* those commits to my repository. That's where I believed the issue was coming from. 

I fixed the issue with:
```yml
name: Deploy action 
on:
  push:
    branches:
      - main
      - beta
      - alpha

jobs:
  deploy:
    name: Deploy git tag
    runs-on: ubuntu-latest
    steps:
      # To make git commits made by semantic-release be made to our bot and not "github-actions" user which doesn't trigger other Action Workflows. 
      # https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # <----- makes `github-actions` user account no longer push my commits. 
      - name: Deploy via semantic release 
        uses: cycjimmy/semantic-release-action@v2
        with: 
          semantic_version: 18
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_PUSH_TOKEN }}
```

**Reply by twinh** [reply]
> Putting a comment here for anyone who stumbles across this discussion looking for help...
> 
> I had the same issue as @qauff. I was noticing that when I ran semantic-release with the `@semantic-release/git` plugin to make a commit on deployment:
> 
> 1. The actual commit being made was authored by the `semantic-release` user account. Not the GitHub actions bot account. This was what I expected.
> 2. When I would go back to my "feed" of GitHub by logging into GitHub and going to `github.com`, my timeline told me that the `github-actions` GitHub account _pushed_ those commits to my repository. That's where I believed the issue was coming from.
> 
> I fixed the issue with:
> 
> ```yaml
> name: Deploy action 
> on:
>   push:
>     branches:
>       - main
>       - beta
>       - alpha
> 
> jobs:
>   deploy:
>     name: Deploy git tag
>     runs-on: ubuntu-latest
>     steps:
>       # To make git commits made by semantic-release be made to our bot and not "github-actions" user which doesn't trigger other Action Workflows. 
>       # https://github.com/semantic-release/semantic-release/blob/2c30e268f9484adeb2b9d0bdf52c1cd909779d64/docs/recipes/ci-configurations/github-actions.md#pushing-packagejson-changes-to-a-master-branch
>       - name: Checkout
>         uses: actions/checkout@v2
>         with:
>           fetch-depth: 0
>           persist-credentials: false # <----- makes `github-actions` user account no longer push my commits. 
>       - name: Deploy via semantic release 
>         uses: cycjimmy/semantic-release-action@v2
>         with: 
>           semantic_version: 18
>         env:
>           GITHUB_TOKEN: ${{ secrets.BOT_PUSH_TOKEN }}
> ```

It works!

another option is to use your token in checkout step, instead of the semantic-release step.

```
- uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
```
