### DISCUSSION TITLE
Adding body to commit message

### DISCUSSION THREAD

**Discussion by jaystary** [semantic-release/semantic-release#1914] [Q&A]
Hello, 

we want to integrate semantic-release into our workflow. One thing however i couldnt figure out yet from the docs, how can i attach a body to the commit message that would show up in the changelog/release? Is this possible? I tried with the format over at conventional commits but the body was still ignored.

Thank you.

**Comment by mhagnumdw** [comment]
I even did a quick test for you, I defined the body and footer of the commit message as it says [here](https://github.com/semantic-release/semantic-release#user-content-commit-message-format) that takes us [here](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#user-content-commit), but both appear neither in the changelog nor in the release notes. I also took a quick look at the plugin docs `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator` and `@semantic-release/changelog` and didn’t find it.

**Comment by bigbrozer** [comment]
I have taken inspiration from here to add commit body to the changelog: https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/templates/commit.hbs

Using `conventionalcommits` preset, it seems that templates can be overriden by the `writerOpts` setting of `release-notes-generator` plugin:

```yaml
- - "@semantic-release/release-notes-generator"
    - writerOpts:
        commitPartial: "*{{#if scope}} **{{scope}}:**\n{{~/if}} {{#if subject}}\n  {{~subject}}\n{{~else}}\n  {{~header}}\n{{~/if}}\n\n{{~!-- commit link --}}{{~#if hash}} {{#if @root.linkReferences~}}\n  ([{{shortHash}}](\n  {{~#if @root.repository}}\n    {{~#if @root.host}}\n      {{~@root.host}}/\n    {{~/if}}\n    {{~#if @root.owner}}\n      {{~@root.owner}}/\n    {{~/if}}\n    {{~@root.repository}}\n  {{~else}}\n    {{~@root.repoUrl}}\n  {{~/if}}/\n  {{~@root.commit}}/{{hash}}))\n{{~else}}\n  {{~shortHash}}\n{{~/if}}{{~/if}}\n\n{{~!-- commit references --}}\n{{~#if references~}}\n  , closes\n  {{~#each references}} {{#if @root.linkReferences~}}\n    [\n    {{~#if this.owner}}\n      {{~this.owner}}/\n    {{~/if}}\n    {{~this.repository}}{{this.prefix}}{{this.issue}}]({{@root.host}}/{{@root.owner}}/_workitems/edit/{{this.issue}})\n  {{~else}}\n    {{~#if this.owner}}\n      {{~this.owner}}/\n    {{~/if}}\n    {{~this.repository}}{{this.prefix}}{{this.issue}}\n  {{~/if}}{{/each}}\n{{~/if}}{{#if body}}\n{{body}}{{/if}}\n"
```

Example of output in the changelog:

![image](https://user-images.githubusercontent.com/218972/120866097-8bb7b600-c58f-11eb-9875-ce3947b31544.png)

Example of commit message:

```plain
feat(installer): bump pyenv to v1.2.27

    * Check [upstream changes](https://github.com/pyenv/pyenv/releases/tag/1.2.27).
```

A bit verbose but it does the job :-)
