### DISCUSSION TITLE
How resolve "[semantic-release] › ℹ  This run was triggered by a pull request and therefore a new version won't be published" in GitHub Actions

### DISCUSSION THREAD

**Discussion by jortfal** [semantic-release/semantic-release#1937] [Q&A] [answered]
I have workflow in GitHub Actions to auto generate the releases for Terraform Modules, but this are not working. The "semantic-relase" show the next message:

> [semantic-release] › ℹ  This run was triggered by a pull request and therefore a new version won't be published.

The workflow configuration is:

```yml
name: Release

on:
  pull_request:
    types: 
      - closed
    branches:
      - main

jobs:
  release:
    name: Release
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Install semantic release and semantic release terraform config
        run: npm install --save-dev semantic-release @jortfal/semantic-release-terraform-config
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main -e @jortfal/semantic-release-terraform-config
```

The job show this:

```
Run npx semantic-release --branches main -e @jortfal/semantic-release-terraform-config
[3:35:50 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.3
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@google/semantic-release-replace-plugin"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[3:35:51 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[3:35:51 PM] [semantic-release] › ℹ  This run was triggered by a pull request and therefore a new version won't be published.
```

Can you help me to solve this?

Thank you very much!

Greetings.

**Comment by travi** [comment, marked as answer]
`semantic-release` works from release _branches_, not pull requests. you need to update your workflow trigger to be for a branch event. you can reference [this project's config](https://github.com/semantic-release/semantic-release/blob/55194c106e25c18b9671ffda5096cc8b9d35ff1a/.github/workflows/release.yml#L3-L8) for an example.

**Reply by jortfal** [reply]
I understand what you are saying, but previously I had configured the workflow trigger to be for a branch event (https://github.com/jortfal/terraform-azure-resource-group/commit/48846f973c1245a473fab23aebffd10c373b8c49). And I switched to pull request (https://github.com/jortfal/terraform-azure-resource-group/commit/529293f28e72183cf4b09149cf0af842f34a1767) because the workflow was not running after merge the pull request in main branch.

My goal is that when I merge a pull request into the `main` branch it runs the workflow `release.yml` which should run `semantic-release`. I am using `GitHub flow` as a branching strategy, **is it possible to use semantic-release for this use case?**

Thank you very much in advance.

**Reply by travi** [reply]
> the workflow was not running after merge the pull request in main branch

the link you provided to your initial config appears to be configured correctly to trigger when changes are merged to the mainline. it appears from [this build](https://github.com/jortfal/terraform-azure-resource-group/runs/2521025253?check_suite_focus=true#step:5:1) that the configuration did work correctly initially. can you point to an example where it did not work?

**Reply by jortfal** [reply]
This still doesn't work and I don't understand why

> This run was triggered by a pull request and therefore a new version won't be published.

https://github.com/jortfal/terraform-azure-resource-group/runs/3640320697?check_suite_focus=true

Example -> https://github.com/jortfal/terraform-azure-resource-group/pull/16

**Reply by travi** [reply]
as mentioned earlier in this thread and in the error message that you included in your last comment, semantic-release does not release from PR builds. your release workflow is [only configured to release for PR triggers](https://github.com/jortfal/terraform-azure-resource-group/blob/ce71f49e4cb98eb38af12a71360869e2f3235248/.github/workflows/release.yml#L4). you need to change your trigger to be for the `push` event instead

**Reply by jortfal** [reply]
I am confused in the documentation it is mentioned that the trigger can be a pull request:

> Triggering a release
>
> For each new commit added to one of the release branches (for example: master, next, beta), with git push or by merging a pull request or merging from another branch, a CI build is triggered and runs the semantic-release command to make a release if there are codebase changes since the last release that affect the package functionalities.
>
> https://semantic-release.gitbook.io/semantic-release/#triggering-a-release

However, I have changed the trigger in the workflow and this way the workflow does not run 👎🏼

https://github.com/jortfal/terraform-azure-resource-group/pull/26

**Reply by travi** [reply]
> merging a pull request

merging a pull request is different than the pull request trigger. the pull request trigger executes when a pull request is created. when a pull request is merged, the result is a new commit added to the target branch, which results in triggering the push trigger.

**Reply by jortfal** [reply]
That is indeed the case. That is the current configuration and it has not worked.

Thank you for your help.

**Reply by travi** [reply]
it appears that the push event for the _squash_ merge of your v2.0.0 PR did not trigger any of your actions. this is not a problem with semantic-release, but a problem with your CI triggers. we do not have the bandwidth to provide CI support here.

I will say that the squash commit that resulted from your merge does not follow the default commit convention, so it would have been ignored by semantic-release, even if it had run. if you choose to use squash merging, you need to be careful that the resulting commit matches the convention defined for semantic-release to expect.

**Reply by jortfal** [reply]
It's true, I hadn't realised about the squash and merge commit. Thank you very much, I'll keep it in mind for the next PR that comes up.

Best regards 👍🏼

**Reply by jorgeramirezamora** [reply]
The solution suggested by @travi works for me even if I merge with a squash

```
name: Release New Version

# Triggers the workflow when a push happens
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    name: Release

    steps:
      - name: Fetch Git entire history for all branches and tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Use Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Semantic Release
        run: nxp semantic release

**Reply by jedwards1211** [reply]
@travi I ran into this issue because I was testing out release changes by pushing commits to `beta`, then I decided to open a PR to merge `beta` into `master`, then I realized I needed to fix another thing, and pushed another commit to `beta`...and bam, `semantic-release` refuses to operate.  

I closed the pull request and manually retriggered a build of the `beta` branch in CircleCI, but `semantic-release` still thought it was triggered by a pull request.  So...that's not good, right?

I was at least able to get it to work by pushing another commit after closing the PR, but it feels like there could be a better way to handle this kind of situation.

**Reply by travi** [reply]
@jedwards1211 what you describe sounds like a different issue than the one described here. could you open a new discussion with more detail about problem you ran into? a public reproduction could be really helpful to understand, if possible.

i'm honestly not sure what you want to happen in this scenario. the intent when a pre-release branch is merged to trunk is that the branch is deleted and recreated the next time a prerelease is needed. without the version from trunk being in the prerelease branch, the version wouldnt be what i assume would be expected, even if it were to continue

**Comment by yn4v4s** [comment]
@jortfal if you really need to run semantic-release on PR merges, you can pass the `--no-ci` flag. I'm not sure about the implications this might have tho.

**Reply by jortfal** [reply]
Thanks, I haven't tried it because in the documentation they mention that :

Set to false to skip Continuous Integration environment verifications. This allows for making releases from a local machine.

I don't know what is involved  to skip Continuous Integration environment verifications.

**Reply by jcandan** [reply]
I have Gitlab CI running on merge requests. The release works for the actual merge, but I am attempting to generate a dry-run release version and notes metric. But, alas, I am also getting `This run was triggered by a pull request and therefore a new version won't be published.` 

The `--no-ci` flag did not resolve this.

**Reply by jcandan** [reply]
I had considered opening up the pipeline workflow rules more broadly to allow MR and branch jobs. Then, at each job, apply rules so that we can specifically run this release dry-run job on a branch pipeline rather than a merge-request pipeline.

However, I found that even if I did that, the branch job would have no way of being associated with the MR, which defeats the purpose because this release dry-run job would need to run on a merge results pipeline not on just any commit.

Really hoping we can get a `--no-ci` or some other flag that makes it so this pull-request validation doesn't run.

**Reply by jcandan** [reply]
Well, according to the conditional [here](https://github.com/semantic-release/semantic-release/blob/70996e0181d28b0651ee0472a3531c1d6274037c/index.js#L59), the `--no-ci` flag should work.

**Reply by jcandan** [reply]
Got it!

My problem was using `npm run semantic-release --no-ci --dry-run` with `"semantic-release": "semantic-release"` in the `scripts` list in `package.json`. Adding `--debug` and seeing no debug results, I surmised that the command options were not being passed.

I changed it to `npx semantic-release` and have it working.

Here is my working release check in Gitlab:

```
check-release:
  image: node:latest
  stage: build
  before_script:
    - npm install
  script:
    - npx semantic-release
        --no-ci
        --dry-run
        --branches=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        --plugins=semantic-release-unsquash,@semantic-release/commit-analyzer,@semantic-release/release-notes-generator
```

Some additional notes:
- I specify the MR source branch so that it successfully fires the release.
- I specify the plugins because my `.releaserc.json` has an `exec` that runs a git commit, and would otherwise cause this release check to fail with "The local branch <branch> is behind the remote one, therefore a new version won't be published."

With this, I will eventually be able to output metrics to the MR for easy reporting about this result.

**Reply by jcandan** [reply]
Well, one more hiccup: I can't use this with [merged results pipeline](https://docs.gitlab.com/ee/ci/pipelines/merged_results_pipelines.html).

**Reply by jcandan** [reply]
Looking into opening an issue to allow release to bypass the [branch up-to-date check](https://github.com/semantic-release/semantic-release/blob/v21.0.7/index.js#L90).

**Reply by jcandan** [reply]
Found https://github.com/semantic-release/semantic-release/issues/1849.

**Reply by jcandan** [reply]
Man! Well, I cannot do it even if I turn off [merged results pipeline](https://docs.gitlab.com/ee/ci/pipelines/merged_results_pipelines.html).

```
The command "git push --dry-run --no-verify failed with the error message remote: You are not allowed to upload code.
fatal: unable to access...The requested URL returned error: 403.
```

Seems I am still at the drawing board.

**Reply by jcandan** [reply]
Got it. The `GITLAB_TOKEN` was protected. This is a feature-branch MR, so not a protected branch. Unchecked the Protected setting for the CI/CD Variable, and that solved it.

**Reply by jcandan** [reply]
With help from https://github.com/semantic-release/semantic-release/issues/1647 and https://github.com/semantic-release/semantic-release/issues/753, I was able to come up with the following to supply the Gitlab MR with the expected version in a Metrics report:

```yml
  script:
    - NEXT_RELEASE_VERSION=$(npx semantic-release
        --no-ci
        --dry-run
        --branches=$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
        --plugins=semantic-release-unsquash,@semantic-release/commit-analyzer,@semantic-release/release-notes-generator
        |
        grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+')
    - echo "expected_version ${NEXT_RELEASE_VERSION}" > metrics.txt
  artifacts:
    reports:
      metrics: metrics.txt
```

**Reply by jcandan** [reply]
Well, shoot. Still not quite there.

![image](https://github.com/semantic-release/semantic-release/assets/2332648/5d3e76b6-0e03-4733-b82d-f1709cf7cc09)

The source branch isn't where the merge will take place (it would take place on the target), so the release version isn't correctly taking into account the branch prerelease setting.

In other words, my feature branch MR into a pre-release has the source branch being passed to semantic-release, giving it a production release version update. And, unless I do some git wrangling within the script (which I don't know if that's possible), there's no way to conduct a prerelease version check.

**Reply by jcandan** [reply]
A script with a similar result, but has potential to manipulate the branch preRelease setting, maybe:

```yml
  script:
    - npx -p @semantic-release/exec
        -p semantic-release
        semantic-release
        --dry-run
        --no-ci
        --plugins "@semantic-release/commit-analyzer,@semantic-release/exec"
        --analyzeCommits @semantic-release/commit-analyzer
        --verifyRelease @semantic-release/exec
        --verifyReleaseCmd 'echo expected_version ${nextRelease.version} > metrics.txt'
```

**Reply by jcandan** [reply]
Going with a solution I dug into and documented here:  https://stackoverflow.com/a/76788731/2917434.

**Comment by alexo-wex** [comment]
I am facing the same issue but I am using Azure Pipelines and GitHub Repository. The error exactly the same (you can see it below). My YAML is:

``` yml
trigger:
  branches:
    include:
      - main
   
variables:
- group: cbs-secret-vars

pool:
  vmImage: 'ubuntu-latest'
  
steps:
- script: |
    npm install --force --global npx
  displayName: "Install NPX Globally"

- script: |
    npm install --save-dev semantic-release
  displayName: "Install semantic-release"

- script: |
    npm install @semantic-release/git @semantic-release/changelog -D
  displayName: "Install semantic-git and semantic-changelog"

- script: |
     npx semantic-release
  displayName: "Run semantic-release"
  env:
    GH_TOKEN: $(github_personal_access_token)
```

Error
![image](https://user-images.githubusercontent.com/107505668/202302240-8df70c84-179a-4f0e-bacc-e336c33154a2.png)

**Reply by jortfal** [reply]
Hi @oliveira-alexdias-wex,

are you doing a merge or a merge and squash?

**Comment by MrSwitch** [comment]
**Solved (possibly)**

I had the same error. It came down to merely the presence of an open PR from the branch i was pushing to `next` targeting another branch in this case it was `main`. I **deleted the PR** and pushed an empty commit to the `next` branch, and lo and behold it worked!  - tagged the `next` channel as designed. I then reopened the PR.

You can see the whole saga here https://github.com/5app/dare/pull/258

**Comment by armandsauzay** [comment]
Curious if someone has a better way of handling this, but currently I found the work around below: 

```yaml 
name: Final

on:
  pull_request:
      branches:
          - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      new-release-version: ${{ steps.dry-release.outputs.new-release-version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with :
        fetch-depth: 0
        ref: ${{ github.head_ref }}
    - name: Setup Node.js environment
      uses: actions/setup-node@v4
      with:
        node-version: 20    
    - name: Semantic Release dry run
      id: dry-release
      run: |
        OUTPUT=$(unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci --branches "$GITHUB_HEAD_REF")
        VERSION=$(echo "$OUTPUT" | grep -o "The next release version is [0-9]*\.[0-9]*\.[0-9]*" | awk '{print $6}')
        echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Use the version
      run: echo "The version is ${{ steps.dry-release.outputs.new-release-version }}"
```
