### DISCUSSION TITLE
Problem with pre-release versions

### DISCUSSION THREAD

**Discussion by milica-nikolic** [semantic-release/semantic-release#1984] [Q&A] [answered]
Hi all!

With this configuration:

```
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/gitlab"
branches:
  - "master-test-sv"
  # This matches maintenance branches
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "rc"
    prerelease: true
```

Master branch is on release 1.0.0.
Version of SR is 17.4.4

I have created rc branch from dev branch and checkouted on rc branch. After that I have pushed change with commit containing breaking change based on Angular convention and semantic release created 1.0.0-rc.1 release instead od 2.0.0-rc.1

I have followed this article [link to article](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md)

Please if you can help me to understand this workflow.

Kind regards!
