### DISCUSSION TITLE
Are the JSON and YAML configurations exactly equivalent?

### DISCUSSION THREAD

**Discussion by trallnag** [semantic-release/semantic-release#2095] [Q&A] [answered]
The Semantic Release documentation always uses JSON for example configs. Same goes for many projects using Semantic Release. If I want to use the YAML config, can I simply transpile JSON to YAML to get valid config or are there inherent differences?

Asking because some config blocks look kind of weird in YAML (list as a list item for example).

```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
			"@semantic-release/changelog",
			{
				"changelogTitle": "x"
			}
		],
    [
			"@semantic-release/exec",
			{
				"verifyConditionsCmd": "x",
				"prepareCmd": "x",
				"publishCmd": "x"
			}
		],
    "@semantic-release/github",
    "@semantic-release/git"
  ]
}
```

to 

```yaml
---
plugins:
- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- - "@semantic-release/changelog"
  - changelogTitle: x
- - "@semantic-release/exec"
  - verifyConditionsCmd: x
    prepareCmd: x
    publishCmd: x
- "@semantic-release/github"
- "@semantic-release/git"
```
