### DISCUSSION TITLE
support bang syntax for breaking changes

### DISCUSSION THREAD

**Discussion by wyardley** [semantic-release/semantic-release#2306] [Commit Convention] [answered]
I know it's not in the original Angular spec, but https://www.conventionalcommits.org/en/v1.0.0/ does outline the bang syntax (`feat!`) for breaking changes. As best I've been able to tell, that's still not supported here. Would that need to be added in conventional-changelog or one of its subrepos? Is it possible to configure?

Maybe some additional context:
https://github.com/conventional-changelog/commitlint/issues/658

**Comment by travi** [comment, marked as answer]
semantic-release uses the angular convention by default, which does not support the syntax you mention. you can choose the conventional-commits convention instead, which supports that syntax. we intend to make that the default convention at some point, but for now you have to switch your convention in your config.

**Comment by wyardley** [comment]
Got it. I thought it was using conventional as the default. Thanks for the response.

**Comment by wyardley** [comment]
I have this in the release config:
```yaml
plugins:
  - '@semantic-release/commit-analyzer'
 ```

which uses conventional-changelog -- I had assumed that the various projects under `conventional-changelog` followed the conventional commits standard by default, though I can see now that it is referring to different conventional commit formats. It's very hard to search for examples because of all of the similar / related names.

After reading through the docs a few times, I did figure it out; to put it here in case anyone else is searching:

```bash
% npm install --save-dev conventional-changelog-conventionalcommits
```
and then
```yaml
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
```

**Comment by djcsdy** [comment]
It's also necessary to configure `release-notes-generator`, otherwise changes marked with `!` won't be included in the release notes.

Also, don't fall into the trap of specifying only the presets that you're configuring. If you specify `presets`, then the default list of `presets` is overwritten by whatever you specify.

So if you want the default semantic-release configuration but with Conventional Commits, the full configuration is:

```yaml
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: conventionalcommits
  - - '@semantic-release/release-notes-generator'
    - preset: conventionalcommits
  - '@semantic-release/npm'
  - '@semantic-release/github'
```

and:

```bash
npm install --save-dev conventional-changelog-conventionalcommits
```

It's almost impossible to figure this out from the docs, it took me a lot of trial and error.
