### DISCUSSION TITLE
How to skip npm release, and only generate tags

### DISCUSSION THREAD

**Discussion by jpbnetley** [semantic-release/semantic-release#2392] [Q&A] [answered]
Hi, 
I am using this acton to manage releases for a Github composite action.

I configured the action with the following
```
- name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        id: semantic
        with:
          branch: 'main'
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I was under the impression if I specify the plugins for the action with `extra_plugins`, they will override the default plugins.

Ie I don't want to do the npm release part, but I want to do the commit-analyzer, release-notes-generator, git
to publish a new tag, and not release it to npm.

But I see the plugins doesn't seem to override, as seen in the build log.

```
[9:49:06 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[9:49:06 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[9:49:08 AM] [semantic-release] › ✔  Run automated release from branch main on repository https://x-access-token:[secure]@github.com/fullfacing/ff-web-release-package.git
[9:49:08 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:49:08 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[9:49:08 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://npm.pkg.github.com
[9:49:08 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[9:49:08 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[9:49:08 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[9:49:08 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[9:49:08 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[9:49:09 AM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #2.
[9:49:11 AM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #2: https://github.com/fullfacing/ff-web-release-package/issues/2#issuecomment-1066578[47](https://github.com/fullfacing/ff-web-release-package/runs/5535085207?check_suite_focus=true#step:3:47)2.
[9:49:11 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[9:49:11 AM] [semantic-release] › ✖  ENONPMTOKEN No npm token specified.
An npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the NPM_TOKEN environment variable on your CI environment.
```

Is there a way that I can complete the action when it gets to the tagging step, and then skip the npm release step and finish up the action?

Thanks for the awesome action and docs :)
