### DISCUSSION TITLE
Why is semantic-release/git not running?

### DISCUSSION THREAD

**Discussion by piejanssens** [semantic-release/semantic-release#2522] [Q&A] [answered]
I have an Azure Devops pipeline with a task to run semantic-release.

This is my `.releaserc`:
```yaml
branches:
  - master

plugins:
  - "@semantic-release/commit-analyzer"
  - "semantic-release-ado"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git":
    assets:
      - "CHANGELOG.md"
    message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

dryRun: false
debug: true

```

This is the generated output (and no trace of semantic-release/git):
```
Starting: Semantic release
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
Script contents:
npx -p @semantic-release/git -p @semantic-release/changelog -p semantic-release-ado semantic-release
========================== Starting Command Output ===========================
/usr/bin/bash --noprofile --norc /home/vsts/work/_temp/fb4d94f8-d259-4e0b-8127-fce35ca98c0b.sh
npm WARN exec The following packages were not found and will be installed: @semantic-release/changelog, @semantic-release/git, semantic-release-ado
[3:05:39 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.3
[3:05:39 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[3:05:39 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:05:39 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "semantic-release-ado"
[3:05:39 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "semantic-release-ado"
[3:05:39 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[3:05:39 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[3:05:40 PM] [semantic-release] › ✔  Run automated release from branch master on repository https://Deloitte-HRT-SAP-SF@dev.azure.com/Deloitte-HRT-SAP-SF/Profile%20Picture%20Wizard/_git/Profile%20Picture%20Wizard
[3:05:40 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[3:05:40 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[3:05:40 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[3:05:40 PM] [semantic-release] › ℹ  Found git tag v0.5.2 associated with version 0.5.2 on branch master
[3:05:40 PM] [semantic-release] › ℹ  Found 2 commits since last release
[3:05:40 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:05:40 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: test patch increment
[3:05:40 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[3:05:40 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci: update
[3:05:40 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:05:40 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[3:05:40 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:05:40 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "semantic-release-ado"
[3:05:40 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "semantic-release-ado"
[3:05:40 PM] [semantic-release] › ℹ  The next release version is 0.5.3
[3:05:40 PM] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "semantic-release-ado"
[3:05:40 PM] [semantic-release] [semantic-release-ado] › ℹ  Setting version 0.5.3 to the env var nextRelease
[3:05:40 PM] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "semantic-release-ado"
[3:05:40 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[3:05:40 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[3:05:40 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[3:05:40 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Create /home/vsts/work/1/s/CHANGELOG.md
[3:05:40 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[3:05:41 PM] [semantic-release] › ✔  Created tag v0.5.3
[3:05:41 PM] [semantic-release] › ✔  Published release 0.5.3 on default channel
Finishing: Semantic release
```

**Comment by travi** [comment, marked as answer]
your yaml is formatted incorrectly. instead, you would need closer to 
```yaml
branches:
  - master

plugins:
  - "@semantic-release/commit-analyzer"
  - "semantic-release-ado"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"

dryRun: false
debug: true
```
