### DISCUSSION TITLE
How to trigger a GitHub Actions workflow after the `semantic-release` has created a release.

### DISCUSSION THREAD

**Discussion by matzar** [semantic-release/semantic-release#2596] [Release workflow] [answered]
I'm trying to set-up Docker Build and Push workflow when a new release is created with semantic-release.

This is my `release.yml` workflow:

```yml
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build --omit=dev
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

And this is how it try to invoke `docker-build-and-publish.yml` workflow:

```yml
name: Build and Push Docker Image

on: 
  release:
    types: [published]
jobs:
# ...
```

I've tried bypassing it by targeting tag creation but no luck. Is `semantic-release` not triggering the `release` event, even though it's releasing a package? Funny thing is, that when I create a release manually, `docker-build-and-publish.yml` workflow triggers with the above `on` settings.
