### DISCUSSION TITLE
My subsequence GitHub action is not being triggered

### DISCUSSION THREAD

**Discussion by albatarnik** [semantic-release/semantic-release#2666] [Q&A]
I have a GitHub action that creates a new release using semantic release which **works**, but the subsequent GitHub action that is meant to trigger when a new release or pre-release is created does not work.

First GitHub action ( create the release )  triggers 

```
name: release 

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - next
      - beta
      - alpha
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: yarn
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
```  
  
 This never triggers, though the release has been created :/
     
```
name: building docker test

# Controls when the workflow will run
on:
  release:
    types: [published, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
```
