### DISCUSSION TITLE
defining steps in config files

### DISCUSSION THREAD

**Discussion by mehdihadeli** [semantic-release/semantic-release#2683] [Q&A]
Hi,
How can I define steps and map plugins to [the steps](https://github.com/semantic-release/semantic-release/blob/master/README.md#release-steps)? I could find this syntax in the docs.
Is this approach deprecated?
I saw such definition [here](https://gist.github.com/ujlbu4/15a305f2e53cb487c39c9484e660903a#file-releaserc-yaml-L72)

``` yml
verifyRelease:
 - path: '@semantic-release/exec'
   cmd:  >-
        ./set-output-version.sh ${nextRelease.version} 
```
