### DISCUSSION TITLE
How get the version created by semantic-release in flow?

### DISCUSSION THREAD

**Discussion by brunokunace** [semantic-release/semantic-release#2697] [Release workflow]
Hi all,

i am using github actions and trying to get the version created by sementic-release to use in another service.

Example of use:
* created a log in asana with the version deployed
* create .version file with the version created

I see the semantic-release not change the package.json version (idk why), but its helps when you have pre-releases, like beta -> latest

Its is my repository:

https://github.com/SuperViz/sdk

Have way to set this version in package.json without conflict after merge beta branch in main branch? i changed from release-it because this.

ty all

**Comment by brunokunace** [comment]
i will create a plugin to make it

**Comment by Shereef** [comment]
```
      - name: Set next version
        id: nextVersion
        run: |
          export NEXT_VERSION=$(npx semantic-release --dry-run | grep -i 'The next release version is' | sed -E 's/.* ([[:digit:].]+)$/\1/')
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
      - name: Echo next version
        run: echo "${{ steps.nextVersion.outputs.version }}"
```

This is what I use
I got this from [here](https://github.com/semantic-release/semantic-release/issues/753#issuecomment-1049746307) and added some GH Actions steps for it
