### DISCUSSION TITLE
npx semantic-release does not work when using nvm for node versioning

### DISCUSSION THREAD

**Discussion by AmmarArnt** [semantic-release/semantic-release#2714] [Configuration] [answered]
### Current behavior

When running my CI, the npx semantic-release throws an error:

```sh
[semantic-release]: node version >=18 is required. Found v16.19.0.
```

My workflow file looks like this:

```yaml
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set the correct Node version using nvm
        shell: bash -l {0}
        run: nvm install

      - name: Install dependencies
        run: npm ci

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
```

And the .nvmrc file specifies the version 18.14.0 which is truly picked up after the `nvm install ` task:
```sh
Now using node v18.14.0 (npm v9.3.1)
```

### Expected behavior

I would expect the semantic-release to successfully execute, given that the task before did pick up the correct node version.

### `semantic-release` version

^20.1.0

### CI environment

Github Actions

### Plugins used

 "@semantic-release/commit-analyzer",
 "@semantic-release/release-notes-generator",
    [
      "@semantic-release/github",

### `semantic-release` configuration

{
  "branches": [
    "main"
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/github",
      {
        "assets": [
          {
            "path": "dist/asset.min.css",
            "label": "CSS distribution"
          },
          {
            "path": "dist/asset.min.js",
            "label": "JS distribution"
          }
        ]
      }
    ]
  ]
}

### CI logs

```sh
Run npm ci
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'semantic-release@20.1.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.19.0', npm: '8.19.3' }
npm WARN EBADENGINE }
```

```sh
Run npx semantic-release
  npx semantic-release
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***

[semantic-release]: node version >=18 is required. Found v16.19.0.
```
