### DISCUSSION TITLE
"Each maintenance branch in the branches configuration must have a unique range property."

### DISCUSSION THREAD

**Discussion by ghicks-rmn** [semantic-release/semantic-release#2887] [Configuration]
I have a repository that has the following git branches:

* main
* 1.x
* 1.10.x
* 1.9.x
* 1.8.x
* 1.7.x
* 1.6.x
* 1.5.x
* 1.4.x
* beta
* alpha
* TOIL-1630
* CLDINFR-783
* CLDINFR-780
* aws-provider
* CLDINFR-775
* docs
* CLDINFR-316
* postgresUpdate
* param-groups
* feature/update-tags-module-reference

It uses this configuration for `branches`:
```
---
branches:
- main
- name: beta
  prerelease: true
- name: alpha
  prerelease: true
- '+([0-9])?(.{+([0-9]),x}).x'
```

I'm trying to run semantic-release after a merge to `main` that should generate a 2.0.0 release. I'm getting the following error back:

```
[9:02:48 PM] [semantic-release] › ✖  EMAINTENANCEBRANCHES The maintenance branches are invalid in the `branches` configuration.
Each maintenance branch in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches) must have a unique range property.

Your configuration for the problematic branches is [ { channel: '1.10.x', type: 'maintenance', name: '1.10.x', tags: [ [Object], [Object], [Object], [Object], [Object], ... 22 more items ], range: '>=1.10.0 <1.10.1', accept: [], mergeRange: '>=1.10.0 <1.11.0' }, { channel: '1.4.x', type: 'maintenance', name: '1.4.x', tags: [ [Object], [Object], [Object], [Object], [Object], ... 15 more items ], range: '>=1.4.0 <1.5.0', accept: [ 'patch' ], mergeRange: '>=1.4.0 <1.5.0' }, { channel: '1.5.x', type: 'maintenance', name: '1.5.x', tags: [ [Object], [Object], [Object], [Object], [Object], ... 16 more items ], range: '>=1.5.0 <1.6.0', accept: [ 'patch' ], mergeRange: '>=1.5.0 <1.6.0' }, { channel: '1.6.x', type: 'maintenance', name: '1.6.x', tags: [ [Object], [Object], [Object], [Object], [Object], ... 18 more items ], range: '>=1.6.1 <1.7.0', accept: [ 'patch' ], mergeRange: '>=1.6.0 <1.7.0' }, { channel: '1.7.x', type: 'maintenance', name: '1.7.x', tags: [ [Object], [Object], [Object], [Object], [Object], ... 19 more items ], range: '>=1.7.0 <1.8.0', accept: [ 'patch' ], mergeRange: '>=1.7.0 <1.8.0' }, ... 3 more items ].
```

As far as I can tell, there is no overlap in the branch ranges as listed - but it doesn't show the whole expanded config, so I can't say for sure. I don't see any reason why the rest of the branches would have overlaps either, and until recently this was working fine.

What am I doing wrong here? My best guess is that it's related to the fact that the newest created branch is 1.10.0, but I don't see how any of the others would conflict with it.

Is there a way to force semantic-release to output the whole branch configuration instead of concatenating it? If I could see what it's actually generating that might help.

Full .releaserc config is below, if it helps:

```
---
branches:
- main
- name: beta
  prerelease: true
- name: alpha
  prerelease: true
- '+([0-9])?(.{+([0-9]),x}).x'
tagFormat: "${version}"
plugins:
- - "@semantic-release/commit-analyzer"
  - preset: conventionalcommits
    releaseRules:
    - type: docs
      release: patch
    - type: refactor
      release: patch
    - type: test
      release: patch
    - type: style
      release: patch
    parserOpts:
      noteKeywords:
      - BREAKING CHANGE
      - BREAKING CHANGES
      - BREAKING
- - "@semantic-release/release-notes-generator"
  - preset: conventionalcommits
    parserOpts:
      noteKeywords:
      - BREAKING CHANGE
      - BREAKING CHANGES
      - BREAKING
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
- - "@semantic-release/github"
  - assets:
    - CHANGELOG.md
```
