### DISCUSSION TITLE
Semantic release is not using the correct commit message

### DISCUSSION THREAD

**Discussion by whitespacecode** [semantic-release/semantic-release#3135] [Q&A]
I create a new release with a Github Action. There is see the commit-analyzer is getting all my commit messages from my push.
Yet when the release is done the only message attached to my release is `chore: set 'package.json' to x.x.x [skip ci]` 
Am i missing something ?

```
- name: Release
  id: release
  env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  run: npx semantic-release
```
My release.config.js
```
module.exports = {
    branches: [
      { name: 'main' },
      { name: 'development', prerelease: true },
    ],
    plugins: [
        ["@semantic-release/commit-analyzer"],
        ["@semantic-release/npm"],
        ["@semantic-release/git",
          {
            "assets": ["package.json"],
            "message": "chore: set `package.json` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
          }
        ],
        ["@semantic-release/github",
          {
            "successComment": false,
            "failTitle": false
          }
        ]
    ],
};
```
