### DISCUSSION TITLE
Node 16 actions are deprecated

### DISCUSSION THREAD

**Discussion by Oliver-Turp** [semantic-release/semantic-release#3162] [Q&A]
Hi Everyone,

I just got this warning after updating my node version for semantic release
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
I followed the link but didn't see anything relevant to my specific actions. I was hoping someone knew what I should do my YAML file to make it node 20 compatible?:

```yaml
name: Release

on:
  push:
    branches:
      - live

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
```
        
        
            
    Thanks for your time!

**Comment by travi** [comment]
that warning is about the actions you are using in your workflow. since you are running semantic-release with npx, that warning does not apply to your use of semantic-release directly

to handle the warning, you should just need to update the versions of the actions you are using. from your included workflow definition, it looks like that would be `actions/checkout` and `actions/setup-node` in your case

**Reply by Oliver-Turp** [reply]
I made the changes you suggested and thought nothing of it because I wasn't pushing any minor or major changes for a while. Then today when I tried to push a minor change I noticed the action was failing and the issue seems to be with the changed uses line. Is there a correct syntax to use @latest if I must supply a version?

![image](https://github.com/semantic-release/semantic-release/assets/55669423/ed5c404a-b959-4af8-8a7a-7110afe0e890)
```yaml
name: Release

on:
  push:
    branches:
      - live

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Node.js
        uses: actions/setup-node
        with:
          node-version: 20.11.0

      - name: Install dependencies
        run: npm install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
        ```
