### DISCUSSION TITLE
Use github action env variables in semantic-version@exec plugin?

### DISCUSSION THREAD

**Discussion by melsawy93** [semantic-release/semantic-release#3172] [Q&A]
Hi Everyone,

Is it possible to use environmental variables defined at the start of a github action yml file in a prepareCmd (semantic-release/exec).

Here is what I tested and im not able to get it to work:

Github action file:

```
name: CI-CD

on:
  workflow_dispatch:

# Environment variables
env:
  Project: "xx"
  
  InstallerPath: "xxx"
  InstallerName: "xx"
....
    - name: Semantic Auto-Release
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        InstallerPath: ${{ env.InstallerPath }}
        InstallerName: ${{ env.InstallerName }}

```

In my package.json:

```
....
        "@semantic-release/exec",
        {
          "prepareCmd": "move ${InstallerPath}/${InstallerName} ${InstallerPath}/${InstallerName}_${nextRelease.version}.msi",
          "publishCmd": "echo \"$SEMANTIC_RELEASE_NOTES\" > changelog_${nextRelease.version}.md"
        }
...
```

I am getting this error: ** [semantic-release] » ×  An error occurred while running semantic-release: ReferenceError: InstallerPath is not defined**. Ive also tried using env.InstallerPath like the way its done in github action yml files but no luck.
