### DISCUSSION TITLE
Any ability to trigger using self defined types

### DISCUSSION THREAD

**Discussion by vovkanaz** [semantic-release/semantic-release#3190] [Commit Convention] [answered]
### New feature motivation

It would be nice to have the possibility to define custom types () instead of the default (feat/fix/breaking)

### New feature description

For example, we have:
```
analyzeCommits:
  - path: "@semantic-release/commit-analyzer"
    releaseRules:
    - type: "feat"
      release: "minor"
    - type: "hotfix"
      release: "patch"
    - type: "patch"
      release: "patch"
    - type: "minor"
      release: "minor"
    - type: "breaking"
      release: "major"
```
Maybe we could add /define a custom type
```
    - type: "custom-type-name"
      release: "minor"
```
to be able to trigger semantic release on commits containing this type inside a commit message.
We've tried to do this, and the pipeline was successfully triggered, but we've got an empty message under the tag definition inside CHANGELOG.md(without Features/Bug Fixes), and working well if fix/feat/BREAKING CHANGE
