### DISCUSSION TITLE
Output for github action

### DISCUSSION THREAD

**Discussion by devskar** [semantic-release/semantic-release#3193] [Configuration]
So I have 2 questions:
1. I want to have a second job running in my workflow, but only when semantic-release published a new version.
Minimal example
```yml
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
        run: npx semantic-release

  deploy:
    needs: release
    runs-on: ubuntu-latest
    if: ???
```
How could I achieve this?

2. Is there a way to store the released version in a variable or in steps.release.outputs?

**Comment by gr2m** [comment]
I would very much like us to add this, yes! The functionality should go into the https://github.com/semantic-release/github plugin. Looks like somewhat related to https://github.com/semantic-release/github/issues/604.

I'd love a pull request if someone would be interested in working on it. You an ping me directly for reviews

**Reply by travi** [reply]
i'm a bit more hesitant to enable this sort of workflow. one of the core goals of semantic-release is to coordinate the entire release workflow and we have purposely not made the resulting version available outside of the semantic-release lifecycle in order to encourage this approach. enabling an output like this feels like it would violate that goal by enabling follow-up jobs to continue the release process after semantic-release does part of it.

what sort of workflow is desired here that would be better handled by including the steps of the second job within what semantic-release manages, possibly with the use of the exec plugin?

**Reply by gr2m** [reply]
in the context of GitHub Actions, I can see using other GitHub Actions as a follow up which cannot easily utilized by an exec plugin. I would start out by creating a dedicated semantic-release plugin to set these outputs though

**Reply by vdksystem** [reply]
also GitHub Actions maintainers (microsoft) made a decision not to trigger release event if it was published by action GITHUB_TOKEN. So good idea of making a release in one action and handling release logic in another won't work here. PAT is agains't security best practices (or adds rotation hell).
Having those outputs would be helpful.

**Comment by devskar** [comment]
I am not sure if this is a problem only for github. Wouldn't it be nicer to have a solution that works for all ci environments?

**Reply by gr2m** [reply]
yes, the same could be done for other CI environments, with CI specific plugins

**Reply by gr2m** [reply]
or we follow an approach similar to https://github.com/semantic-release/env-ci

**Comment by kamzil** [comment]
We're using @semantic-release/exec to achieve this by writing version to a file called VERSION.

In package.json:
```
  "devDependencies": {
    "@semantic-release/exec": "^6.0.3",
    "semantic-release": "^23.0.2"
  },
  "release": {
    "branches": [
      "main"
    ],
    "npmPublish": false,
    "plugins": [
      [
        "@semantic-release/exec",
        {
          "successCmd": "echo v${nextRelease.version} > VERSION"
        }
      ]
    ]
  }
```

In GitHub workflow yaml:
```
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semantic-release.outputs.version }}
    steps:
      - id: semantic-release
        run: |
          npx semantic-release
          VERSION=$(cat VERSION)
          echo "Resolved version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  deploy:
    needs: release
    name: Release ${{ needs.release.outputs.version }}
    runs-on: ubuntu-latest
```

Would be nice to have this built-in.
