### DISCUSSION TITLE
How to checkout into a commit that was pushed in a previous step in bitbucket pipelines?

### DISCUSSION THREAD

**Discussion by tomerh2001** [semantic-release/semantic-release#3201] [Q&A]
I have the following bitbucket pipeline:

```
  branches:
    develop:
      - step: *semantic_release # Performs git push 
      - step: *deploy           # Deploys the version before the push
```

I'm looking for a way to reliably check into the commit that was pushed (or just the latest commit of the branch) within the deploy step; how can you do that?

I tried `git checkout $BITBUCKET_BRANCH,` but that didn't work.
