### DISCUSSION TITLE
Help to define my release pipeline

### DISCUSSION THREAD

**Discussion by fslef** [semantic-release/semantic-release#3213] [Configuration]
I would like to use Semantic Release to track all changes done on a simple project repo. I need to maintain a changelog at the root, and to publish a new release on github each time the main branch is updated.

I tried the default recipe [(available here)](https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions), but this is unclear for me why I would need npm and nodes ?

Why those 3 steps are required, as my only goal is to publish a release in my own repo:

``` yml
 - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
```
