### DISCUSSION TITLE
conventionalcommits preset not being picked up?

### DISCUSSION THREAD

**Discussion by timothystone-knsl** [semantic-release/semantic-release#3290] [Configuration] [answered]
I'm pretty sure this use to work, but I'm not sure when it stopped (possibly with v23, though I haven't had luck downgrading to v22). The file, `.releaserc.yml` is being read:

```shell
[3:07:56 PM] [semantic-release] › ℹ  Running semantic-release version 23.0.8
2024-05-06T15:07:56.520Z semantic-release:config load config from: /builds/another15y/commit-config-presets/.releaserc.yml
2024-05-06T15:07:56.528Z semantic-release:config options values: {
  branches: [ 'master', 'main' ],
  repositoryUrl: '[https://gitlab-ci-token:[secure]@gitlab.com/another15y/commit-config-presets.git'](https://gitlab-ci-token:%5Bsecure%5D@gitlab.com/another15y/commit-config-presets.git'),
  tagFormat: '${version}',
  plugins: [
    [ '@semantic-release/commit-analyzer', [Object] ],
    [ '@semantic-release/release-notes-generator', [Object] ],
    '@semantic-release/gitlab',
    [ '@semantic-release/npm', [Object] ],
    [ '@semantic-release/changelog', [Object] ],
    '@semantic-release/git'
  ],
  _: [],
  debug: true,
  ci: true,
  '$0': 'semantic-release'
}
```

Setting the `preset: 'conventionalcommits'` is not behaving as expected. I even tried passing an empty `presetConfig: {}` because the documentation for the `commit-analyzer` suggests it's necessary.

_Pretty sure I'm getting the syntax correct for the commits_, i.e., `feat!: something important to bump the major\n\nhands typing words.` I have some [sample pipelines showing it failing](https://gitlab.com/another15y/commit-config-presets/-/jobs/6789268881). 

```shell
[3:08:00 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat(config)!: turn on conventionalcommits and pass a config correctly
The presetConfig was not passed to the configuration correctly. Turn on conventionalcommits and set
the semantic release to latest.
2024-05-06T15:08:00.022Z semantic-release:commit-analyzer Analyzing with default rules
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(config)!: pass empty presetConfig
Per semrel documentation, "For presets that expects a configuration object, such as
conventionalcommits, the presetConfig option must be set." Setting one.
2024-05-06T15:08:00.023Z semantic-release:commit-analyzer Analyzing with default rules
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat!: dowgrade to sem-rel 22x
22.0.12 downgrade.
2024-05-06T15:08:00.023Z semantic-release:commit-analyzer Analyzing with default rules
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat!: only bang commit in list
updated dummy.txt
2024-05-06T15:08:00.024Z semantic-release:commit-analyzer Analyzing with default rules
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[3:08:00 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 4 commits complete: no release
[3:08:00 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:08:00 PM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

Take note that `commit-analyzer` is "...analyzing with **default** rules." That seems...  incorrect. 🤔

What am I doing wrong in the configuration?

```yml
plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: "conventionalcommits"
      presetConfig: {}
  - - '@semantic-release/release-notes-generator'
    - preset: "conventionalcommits"
      presetConfig: {}
  - '@semantic-release/gitlab'
  - - '@semantic-release/npm'
    - npmPublish: false
  - - '@semantic-release/changelog'
    - changelogTitle: |-
        # Another Caffeinated Day Project CHANGELOG

        **Do not edit this file; it is automatically generated by Semantic Release.**
  - '@semantic-release/git'
branches:
  - 'master'
  - 'main'
tagFormat: '${version}'
```
