### DISCUSSION TITLE
Generating 2 sets of changelog, 2 changelog files with different types

### DISCUSSION THREAD

**Discussion by PeS82** [semantic-release/semantic-release#3315] [Q&A]
(This is a copy of [StackOverflow question](https://stackoverflow.com/questions/78506028/semantic-release-generate-2-sets-of-changelog) I posted)

We have somehow extended commit messages syntax to cover internal changes that should be helpful for some departments in the company but we don't want to share them with public. For example apart from the well known `fix` we have internal sibling `ifix`.

I am struggling to generate "Internal Changelog" that includes all (relevant) commits and public Changelog that contains reduced set of info.

I tried to setup the `releaserc.yml` to run `@semantic-release/changelog` twice with different config:

```yaml
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/changelog'
  - '@semantic-release/gitlab'
  - '@semantic-release/exec'

prepare:
  - path: '@semantic-release/changelog'
    changelogFile: CHANGELOG.md
    types:
    - type: 'feat'
      section: 'Features'
    - type: 'fix'
      section: 'Bug Fixes'
  - path: '@semantic-release/changelog'
    changelogFile: INTERNAL_CHANGELOG.md
    types:
      - type: 'feat'
        section: 'Features'
      - type: 'fix'
        section: 'Bug Fixes'
      - type: 'ifix'
        section: "Internal Bug Fixes"
      - type: 'perf'
        section: 'Performance Improvements'
      - type: 'chg'
        section: 'Changes'
      - type: 'bug'
        section: 'Bugs'
      - type: 'docs'
        section: 'Documentation'
      - type: 'refactor'
        section: 'Code Refactoring'
      - type: 'test'
        section: 'Tests'
      - type: 'chore'
        section: 'Chores'

publish:
  - path: '@semantic-release/gitlab'
    assets:
      - path: CHANGELOG.md
        label: 'Changelog'
      - path: INTERNAL_CHANGELOG.md
        label: 'Internal'

```

However this seem to pickup only the first config and even though `INTERNAL_CHANGELOG.md` is created they both are the same - containing only the commits targeted to public.

Another attempt was to have 2 sets of `.releaserc.yml` in CI file variables, run 2 jobs in sequence and before the job starts copy the relevant config. One job would generate changelog and the other internal one. The problem I ran into there was that the first one tagged the version in GitLab and therefore the second job did not find any relevant commits.

How would you deal with generating 2 sets of changelog, please?
