### DISCUSSION TITLE
releaserc didn't produce expected results

### DISCUSSION THREAD

**Discussion by MrGadget1024** [semantic-release/semantic-release#3340] [Release workflow]
### Current behavior

- releaserc dictates "breaking" tag but commits with that didn't trigger major version.
- releaserc also has a prepare command to run unitypacker that either didn't execute or wasn't included in the published release.

### Expected behavior

major release 90.0.0 should've been produced and unity package should've been included

See https://github.com/MirrorNetworking/Mirror/releases
Where you can compare the assets for 89.6.9 that was produced with cycjimmy/semantic-release-action with 89.7.0 that was produced with semantic-release/semantic-release.

### `semantic-release` version

24.0.0

### CI environment

GitHub

### Plugins used

- @semantic-release/commit-analyzer
- @semantic-release/release-notes-generator
- @semantic-release/exec
- @semantic-release/github

### `semantic-release` configuration

https://github.com/MirrorNetworking/Mirror/blob/master/.github/workflows/Semantic.yml
https://github.com/MirrorNetworking/Mirror/blob/master/.releaserc.yml

### CI logs

https://github.com/MirrorNetworking/Mirror/actions/runs/8958765510/job/24603391210

### Bonus Points

Additionally, we'd like to disable producing these if possible and only produce the unity package:

![image](https://github.com/semantic-release/semantic-release/assets/9826063/1b8b8d05-f2f8-44b7-afa7-7f04cdaf3c21)

**Comment by travi** [comment]
i notice that you define a list of plugins using the `--preset` flag here: https://github.com/MirrorNetworking/Mirror/blob/7c9e8e917c6c2252ef6d9281474186035da4c4b3/.github/workflows/Semantic.yml#L41

cli flags take precedence over the same properties defined in a config file, so the plugins list defined in your config file is being ignored

**Reply by MrGadget1024** [reply]
> i notice that you define a list of plugins using the `--preset` flag here: https://github.com/MirrorNetworking/Mirror/blob/7c9e8e917c6c2252ef6d9281474186035da4c4b3/.github/workflows/Semantic.yml#L41
> 
> cli flags take precedence over the same properties defined in a config file, so the plugins list defined in your config file is being ignored

So I should delete lines 41-42 in Semantic.yml, and add `- debug: true` to each of the plugins in releaserc.yml?

**Comment by MrGadget1024** [comment]
can't have `- debug: "true"` but it's working now without that

**Reply by travi** [reply]
debug should be possible as a top-level property or could still be used as a cli flag since it is independent of the plugins list

**Reply by MrGadget1024** [reply]
> debug should be possible as a top-level property or could still be used as a cli flag since it is independent of the plugins list

Restoring `--debug true` to Semantic.yml...

```yaml
- name: Release
  run: npx semantic-release
    --debug true
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
...with the following in releaserc...
```yaml
- - '@semantic-release/release-notes-generator'
  - preset: "conventionalcommits"
    presetConfig:
      types:
      - type: "breaking"
        section: "Breaking Changes"
        hidden: false
      - type: "release"
        section: "Release"
        hidden: false
      - type: "fix"
        section: "Bug Fixes"
        hidden: false
      - type: "feat"
        section: "Features"
        hidden: false
      - type: "feature"
        section: "Features"
        hidden: false
```
...produces this:
```
2024-06-15T14:24:16.854Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {
  preset: 'conventionalcommits',
  presetConfig: { types: [ [Object], [Object], [Object], [Object], [Object] ] }
}
```
Maybe this could be a bit more verbose for debug mode?
