### DISCUSSION TITLE
Help with workflow, build flutter app with next version before release

### DISCUSSION THREAD

**Discussion by vishnumukundan** [semantic-release/semantic-release#3373] [Q&A] [answered]
Hi,
I'm new to `semantic-release`, and I need some specific tasks to be done before release. I hope someone could help me.
So, the steps are:

- Get the next version from `semantic-release`
- use that version to update the version number in my Flutter app's `pubspec.yaml.` file
- commit that change to git
- then the usual stuff. tags, release, and so on

I don't know if this is possible. if it is possible please help me with that.
I found #3357 helpful and tried it many times. But my steps are a little different from them.

Thanks.

**Comment by ruiaraujo012** [comment, marked as answer]
Hi. I think you could use the plugin [semantic-release-pub](https://github.com/zeshuaro/semantic-release-pub), you can see all the plugins available [here](https://semantic-release.gitbook.io/semantic-release/extending/plugins-list).
If you need the file to be updated before the build, you'll need to do something like I did in #3357, otherwise, only adding that plugin should do what you need.

**Reply by vishnumukundan** [reply]
Thank you. I will look into it and update

**Reply by ruiaraujo012** [reply]
NP, let me know if it worked ;)

**Reply by vishnumukundan** [reply]
sure

**Reply by vishnumukundan** [reply]
@ruiaraujo012  It's worked. thank you very much.

And one more thing. 😃 
By default, the version number update removes the build number. but if I enable the `updateBuildNumber` config, it works fine, and the build number is always updating along with the version. but I need to update the build number only on release to the Play Store. Is there any configuration for not updating the build number and also not removing that?

>.releaserc.yml
```yaml
plugins:
  - - "@semantic-release/commit-analyzer"
    - presets: conventionalcommits
  - - "@semantic-release/release-notes-generator"
    - presets: conventionalcommits
  - "@semantic-release/github"
  - - "semantic-release-pub"
    - publishPub: false
      updateBuildNumber: true
  - - "@semantic-release/git"
    - assets: ["pubspec.yaml"]
      message: "chore(release): ${nextRelease.version}"
branches:
  - main
```

Thank you
