### DISCUSSION TITLE
[@semantic-release/github] - The asset cannot be read, and will be ignored.

### DISCUSSION THREAD

**Discussion by Rossella-Mascia-Neosyn** [semantic-release/semantic-release#3417] [Q&A]
my problem is that I can’t find my apk.

This is my github action
```
name: Release uat
on:
  push:
    branches:
      - uat

permissions:
  contents: read # for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
          cache: gradle

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Run Yarn Install
        run: |
             npm i -g corepack
             yarn install

      - name: Set env uat
        run: yarn setUat

      - name: Create bundle assets
        run: yarn android:bundle:assets
             
      - name: Build Android debug APK
        run: yarn build:android-uat-debug-apk

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app-uat-debug
          path: android/app/build/outputs/apk/uat/debug/app-uat-debug.apk
          retention-days: 3
          
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
```

```
{
  "branches": [
    "main",
    "next",
    {
      "name": "dev",
      "prerelease": true
    },
    {
      "name": "uat",
      "prerelease": true
    }
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "semantic-release-react-native",
    [
      "@semantic-release/git",
      {
        "assets": [
          "ios/**/Info.plist",
          "ios/**/*.pbxproj",
          "android/app/build.gradle",
          "docs/CHANGELOG.md"
        ],
        "message": "chore: ${nextRelease.version}"
      }
    ],
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "docs/CHANGELOG.md"
      }
    ],
    [
      "@semantic-release/github",
      {
        "assets": [
          {
            "path": "android/app/build/outputs/apk/dev/debug/app-dev-debug.apk",
            "label": "Android dev debug apk"
          },
          {
            "path": "artifacts/app-uat-debug.zip",
            "label": "Android uat debug apk"
          },
          {
            "path": "android/app/build/outputs/apk/prod/debug/app-prod-debug.apk",
            "label": "Android prod debug apk"
          }
        ]
      }
    ]
  ]
}
```

<img width="1143" alt="Screenshot 2024-08-06 at 15 27 51" src="https://github.com/user-attachments/assets/ef10cb88-0848-4a25-a94f-9e895172a43b">
