### DISCUSSION TITLE
Calculate Semantic Version of remote Repo in Azure Devops

### DISCUSSION THREAD

**Discussion by Slaizer007** [semantic-release/semantic-release#3441] [Release workflow]
### Current behavior

When checking out a remote repo+branch with this steps in azure pipeline:

```
resources:
  repositories:
    - repository: vpn-api-service
      type: git
      name: xxx/vpn-api-service
      ref: dev
    - checkout: vpn-api-service
      clean: true
      fetchDepth: 3
      persistCredentials: true
   - script: |
      npx -p semantic-release@latest -p @semantic-release/commit-analyzer@latest semantic-release
```      

 The semantic tool still uses the branch the pipeline is located in (main) instead of the remote branch 'dev'.
 See also the CI logs for this i attached.

### Expected behavior

semantic-release should use the remote branch and calculate its sem version.

### `semantic-release` version

latest

### CI environment

Azure Devops

### Plugins used

commit-analyzer:latest

### `semantic-release` configuration
```
{
  "branches": ["dev","main"],
  "plugins": ["@semantic-release/commit-analyzer"]
}
```

### CI logs
```
npm warn exec The following packages were not found and will be installed: semantic-release@24.1.0, @semantic-release/commit-analyzer@13.0.0
[3:29:59 PM] [semantic-release] › ℹ  Running semantic-release version 24.1.0
[3:29:59 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:30:00 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://<my_azure_url>/_git/vpn-api-service
[3:30:00 PM] [semantic-release] › ℹ  The local branch main is behind the remote one, therefore a new version won't be published.
```
