### DISCUSSION TITLE
Skip Adding Comments to PR's

### DISCUSSION THREAD

**Discussion by MrGadget1024** [semantic-release/semantic-release#3451] [Configuration] [answered]
How can I skip this step and save 2 minutes for the job to complete?

workflow: https://github.com/MirrorNetworking/Mirror/blob/master/.github/workflows/Semantic.yml
releaserc: https://github.com/MirrorNetworking/Mirror/blob/master/.releaserc.yml

![image](https://github.com/user-attachments/assets/0b4b1545-85df-4214-b16b-cba9dbd57925)

**Comment by travi** [comment, marked as answer]
you can find documentation for that ability under the [options for the github plugin](https://github.com/semantic-release/github#options). for your case, you would want to look at details for the [`successComment`](https://github.com/semantic-release/github#successcomment) option as well as the [`failComment`](https://github.com/semantic-release/github#failcomment)

**Reply by MrGadget1024** [reply]
> you can find documentation for that ability under the [options for the github plugin](https://github.com/semantic-release/github#options). for your case, you would want to look at details for the [`successComment`](https://github.com/semantic-release/github#successcomment) option as well as the [`failComment`](https://github.com/semantic-release/github#failcomment)

This seems to have worked, thanks.

.releaserc.yml
```yaml
  # Create a new release on GitHub
  - - '@semantic-release/github'
    - assets:
      - path: "Mirror.unitypackage"
        label: "Mirror Unity Package"
        name: "Mirror-${nextRelease.version}.unitypackage"
      successCommentCondition: "false"
      failCommentCondition: "false"
```
