### DISCUSSION TITLE
Automatic Versioning for Github Packages

### DISCUSSION THREAD

**Discussion by justuswitmer** [semantic-release/semantic-release#3454] [Configuration] [answered]
Hey!
I am having an issue versioning my Github package automatically. I am using semantic to version the repo connected to my package and that is working well. However, my Github package is not versioning with my repo. Looking at the docs it seems like the `@semantic-release/npm` plugin should accomplish what I am looking for, however I have been unsuccessful so far in configuring that correctly. I don't want to publish to the npm registry, Just Github.
Any advice on resolving my issue is appreciated!

Here is my `.releaserc.yml`
```
branches:
  - master
  - name: beta
    prerelease: true

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - - '@semantic-release/changelog'
    - changelogFile: 'CHANGELOG.md'
  - - '@semantic-release/github'
    - assets:
        - 'CHANGELOG.md'
  - - '@semantic-release/git'
    - assets:
        - 'CHANGELOG.md'
        - 'dist/**'
      message: 'chore(release): set `package.json` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}'
``` 

And here is my `npm-publish.yml`
```
name: Release
on:
  push:
    branches:
      - master # or main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: "https://npm.pkg.github.com/"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Github personal access token 
          NPM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
```
