### DISCUSSION TITLE
Azure repos and azure pipeline

### DISCUSSION THREAD

**Discussion by pitchan** [semantic-release/semantic-release#3508] [Configuration] [answered]
Hello ! 

I tried to setup semantic release in my pipeline azure.

I can't find much info on the web maybe someone can help here.

i tried adding this script to my pipeline :
```
  - script: |
      npx semantic-release --repository-url=$GIT_REPOS_URL
    displayName: 'Run Semantic Release'
    env:
      GIT_REPOS_URL: $(GIT_REPOS_URL)
      GIT_AUTHOR_NAME: $(Build.RequestedFor)
      GIT_AUTHOR_EMAIL: $(Build.RequestedForEmail)
      GIT_COMMITTER_NAME: $(Build.RequestedFor)
      GIT_COMMITTER_EMAIL: $(Build.RequestedForEmail)
      AZURE_DEVOPS_TOKEN: $(AZURE_DEVOPS_TOKEN)
```
      
**Is that a good configuration ? where can i use the azure token ?**      

I removed url from .releaserc to set the value with --repository-url
```json
{
  "branches": ["develop", "build/*"],
  "repositoryUrl": "",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": ["package.json", "CHANGELOG.md"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}
```

This is not working actually but i want to know if i am in the good way.

Thanks in advance for your help !
