### DISCUSSION TITLE
FYI Using Turbo for monorepo

### DISCUSSION THREAD

**Discussion by waynevanson** [semantic-release/semantic-release#3635] [Configuration]
Hey All!

Just adding issues I came across which took days to figure out.

Came across this in my job.
EINVALIDGHTOKEN

Solution is to allow turbo to pass through env variables

```json
{
  "$schema": "https://turbo.build/schema.json",
  "tasks": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/"]
    },
    "release": {
      "cache": false,
      "dependsOn": ["build", "^release"], 
      "env": ["GITHUB_TOKEN", "GH_TOKEN", "NPM_TOKEN", "NODE_AUTH_TOKEN"] # THIS
    }
  }
}

```

A step in my job.
```yaml
      - run: pnpm run release
        name: Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          NODE_AUTH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ github.token }}
```
