### ISSUE TITLE
Travis recipe fails as-is resulting in `Script failed with status 127`

### ISSUE THREAD

**Issue by myii** [semantic-release/semantic-release#1102]
## Current behavior

The example given as-is crashes out with `Script failed with status 127`:

https://github.com/semantic-release/semantic-release/blob/aed4ea2edc1bf6d4e452a6cea421899aa497016f/docs/recipes/travis.md#L88-L94

* https://travis-ci.org/myii/ubports-mirscreencast/builds/494368337?utm_source=github_status&utm_medium=notification

Commenting out the `- nvm install lts/*` works fine as [done here](https://github.com/myii/ubports-mirscreencast/blob/753bcf3bfc615f24cec2047a8b7674db528ccfa7/.travis.yml#L8-L14).

* https://travis-ci.org/myii/ubports-mirscreencast/builds/494368590?utm_source=github_status&utm_medium=notification

**Comment by pvdlg** [comment]
I tried this recently on Travis and it worked as expected. Also the `nvm` documentation indicate this is a valid command: https://github.com/creationix/nvm#long-term-support

Maybe this error happened for another reason? Can you try again?

**Comment by myii** [comment]
@pvdlg Thanks for the response.  This is how we're [doing it now](https://github.com/saltstack-formulas/template-formula/blob/178c7103f3e53e0a51132c4698e7ce5fc24999bf/.travis.yml#L44-L70):

```yaml
    # Define the release stage that runs semantic-release
    - stage: release
      language: node_js
      node_js: lts/*
      before_install: skip
      script:
        # Update `AUTHORS.md`
        - export MAINTAINER_TOKEN=${GH_TOKEN}
        - go get github.com/myii/maintainer
        - maintainer contributor

        # Update Tables of Content in the relevant `.md` files
        - npm install markdown-toc -D
        - markdown-toc -i CONTRIBUTING.md
        # - markdown-toc -i README.md
        - markdown-toc -i TOFS_pattern.md

        # Install all dependencies required for `semantic-release`
        - npm install @semantic-release/changelog@3 -D
        - npm install @semantic-release/exec@3 -D
        - npm install @semantic-release/git@7 -D
      deploy:
        provider: script
        skip_cleanup: true
        script:
          # Run `semantic-release`
          - npx semantic-release@15
```

There's a couple of feature ideas there for `semantic-release` as well:

1. Update `AUTHORS.md`
1. Update Tables of Content in the relevant `.md` files
