### ISSUE TITLE
Setup SSH, but still get ENOGHTOKEN error for github

### ISSUE THREAD

**Issue by prios-karly-nelson** [semantic-release/semantic-release#1263]
## Current behavior

We are trying to use semantic-release with CircleCI. We were not able to do the setup through the semantic-release CLI, because for security reasons we need to authenticate through SSH, so we haven't setup the GH_TOKEN. We followed the SSH setup instructions for CircleCI from the documentation: https://semantic-release.gitbook.io/semantic-release/recipes/git-hosted-services/git-auth-ssh-keys, including adding everything we need to our environmental variables but our build is still failing in CircleCI with an error saying we don't have a GH_TOKEN even though we shouldn't need one.

Here's the error we're getting: 

```
[8:58:45 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
[8:58:45 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[8:58:45 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository principlesos/design-system-tokens.

AggregateError: 
    SemanticReleaseError: No GitHub token specified.
        at module.exports (/home/circleci/project/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/home/circleci/project/node_modules/@semantic-release/github/lib/verify.js:85:17)
        at verifyConditions (/home/circleci/project/node_modules/@semantic-release/github/index.js:24:9)
        at validator (/home/circleci/project/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /home/circleci/project/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/home/circleci/project/node_modules/p-reduce/index.js:17:9)
    at /home/circleci/project/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/circleci/project/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/circleci/project/node_modules/semantic-release/index.js:82:3)
    at async module.exports (/home/circleci/project/node_modules/semantic-release/index.js:168:22)
    at async module.exports (/home/circleci/project/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}Exited with code 1
```

## Expected behavior

Semantic-release is able to connect to github repo and push tags, releases, etc.

## Environment

- **semantic-release** version:  ^15.13.19
- CI environment: CircleCI
- Plugins used: Github, NPM
- **semantic-release** configuration: 
This is all I have in my .releaserc, should I have more?
```
{
  "branch": "master"
}
```
- CircleCI config.yml:
```
  publish_release:
    docker:
      - image: *primary_image
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: authenticate github
          command: |
            # Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
            openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in git_deploy_key.enc -out /tmp/git_deploy_key
            # Make sure only the current user can read the private key
            chmod 600 /tmp/git_deploy_key
            # Create a script to return the passphrase environment variable to ssh-add
            echo 'echo ${SSL_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
            # Start the authentication agent
            eval "$(ssh-agent -s)"
            # Add the key to the authentication agent
            DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
            npx semantic-release --dry-run
```
- CI logs: our circle ci is private so I can't link to it, but here's the entire output from the failing build step:
```
#!/bin/bash -eo pipefail
# Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in git_deploy_key.enc -out /tmp/git_deploy_key
# Make sure only the current user can read the private key
chmod 600 /tmp/git_deploy_key
# Create a script to return the passphrase environment variable to ssh-add
echo 'echo ${SSL_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
# Start the authentication agent
eval "$(ssh-agent -s)"
# Add the key to the authentication agent
DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
npx semantic-release --dry-run
Agent pid 128
Identity added: /tmp/git_deploy_key (/tmp/git_deploy_key)
[8:58:44 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.21
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[8:58:44 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[8:58:44 PM] [semantic-release] › ⚠  Run automated release from branch semantic-release-config in dry-run mode
[8:58:45 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:58:45 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[8:58:45 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://principled.jfrog.io/principled/api/npm/npm-mpllc/
[8:58:45 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[8:58:45 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[8:58:45 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[8:58:45 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
[8:58:45 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[8:58:45 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository principlesos/design-system-tokens.

AggregateError: 
    SemanticReleaseError: No GitHub token specified.
        at module.exports (/home/circleci/project/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/home/circleci/project/node_modules/@semantic-release/github/lib/verify.js:85:17)
        at verifyConditions (/home/circleci/project/node_modules/@semantic-release/github/index.js:24:9)
        at validator (/home/circleci/project/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /home/circleci/project/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/home/circleci/project/node_modules/p-reduce/index.js:17:9)
    at /home/circleci/project/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/circleci/project/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/circleci/project/node_modules/semantic-release/index.js:82:3)
    at async module.exports (/home/circleci/project/node_modules/semantic-release/index.js:168:22)
    at async module.exports (/home/circleci/project/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}Exited with code 1
```
