### ISSUE TITLE
"semantic-release" fatal: You are not currently on a branch.

### ISSUE THREAD

**Issue by Jeff-Tian** [semantic-release/semantic-release#1298]
## Current behavior
```
> git push && git push --tags
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use
    git push origin HEAD:<name-of-remote-branch>
npm ERR! code ELIFECYCLE
npm ERR! errno 128
npm ERR! grpc-man@1.2.0 postversion: `git push && git push --tags`
npm ERR! Exit status 128
npm ERR! 
npm ERR! Failed at the grpc-man@1.2.0 postversion script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

My project: https://github.com/Jeff-Tian/grpc-man
My travis config:
```
language: node_js
node_js:
  - '10'
install:
  - npm i
script: npm run test && npm run lint && npm run build

jobs:
  include:
    - stage: release
      node_js: lts/*
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        all_branches: true
```

It failed when `git push`. But I swear I had configured the token correctly.

![image](https://user-images.githubusercontent.com/3367820/65770844-7eff7f80-e169-11e9-9713-0065c1cfda1a.png)

## Expected behavior

It should release automatically

## Environment

- **semantic-release** version: ^15.13.24
- CI environment: Travis Pro
- Plugins used: 
- **semantic-release** configuration: https://github.com/Jeff-Tian/grpc-man
- CI logs: https://travis-ci.com/Jeff-Tian/grpc-man/jobs/239805310
