### ISSUE TITLE
let semantic-release work from github actions triggered on new tags

### ISSUE THREAD

**Issue by fent** [semantic-release/semantic-release#1389]
## New feature motivation

I'm trying to add semantic-release into my workflow, by triggering only when I push a new tag to my repo. I'm using the following workflow file

```yml
name: Release
on:
  push:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: >
          npx semantic-release
          --branch undefined
          --dry-run
          --plugins @semantic-release/commit-analyzer
          --plugins @semantic-release/release-notes-generator
          --plugins @semantic-release/npm
          --plugins @semantic-release/github
```

I've set `--branch undefined` because I tried to unset the branch requirement error that I get, but I still get it setting the option to `undefined`.

    This test run was triggered on the branch undefined, while semantic-release is configured to only publish from undefined, therefore a new version won’t be published.

Am I unsetting the option incorrectly? Is there a way to do this correctly? I'd also rather do this all from the workflow file to keep things in one place, rather than adding an additional `.releaserc` file to the repo. So setting all this from semantic-release's cli would be ideal.
