### ISSUE TITLE
NPM plugin not respecting `pkgRoot` option

### ISSUE THREAD

**Issue by harrysolovay** [semantic-release/semantic-release#1472]
## Current behavior

I've configured my repository with `pika`, which builds the publish-ready assets, including a slimmed-down `package.json`, into a root-level `pkg` folder. I'm following the same protocol as [`octokit/core`](https://github.com/octokit/core.js/blob/master/package.json)––wherein the NPM plugin is provided a `pkgRoot` option:

```json
[
  "@semantic-release/npm",
  {
    "pkgRoot": "./pkg/"
  }
]
```

I've configured my workflow as follows:

```yml
name: Release
on:
  push:
    branches:
      - master
      - next
      - beta
      - "*.x"
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - uses: actions/github-script@0.5.0
        with:
          script: |
            console.log(
              "DEBUG DEBUG DEBUG",
              require("fs").readFileSync(
                "./pkg/package.json",
                "utf8",
              ),
            );
      - run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

```

## Expected behavior

As expected, the GitHub script action logs out the built contents of `pkg/package.json` (the build is successful). The GitHub release, notes, and change log generation are also successful. However, when it comes time to trigger the NPM publish, I get the following workflow error:

```
AggregateError: 
    SemanticReleaseError: Missing `package.json` file.
        at module.exports (/home/runner/work/testing-semantic-release/testing-semantic-release/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/home/runner/work/testing-semantic-release/testing-semantic-release/node_modules/@semantic-release/npm/lib/get-pkg.js:17:33)
    at prepare (/home/runner/work/testing-semantic-release/testing-semantic-release/node_modules/@semantic-release/npm/index.js:65:11) {
  name: 'AggregateError'
}error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
##[error]Process completed with exit code 1.
```

## Environment

- **semantic-release** version: 17.0.4
- CI environment: GitHub actions, ubuntu-latest, Node
- Plugins used:
  * commit-analyzer
  * release-notes-generator
  * changelog
  * git
  * github
  * npm
- **semantic-release** configuration:
```json
"release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/changelog",
        {
          "changelogFile": "docs/CHANGELOG.md"
        }
      ],
      [
        "@semantic-release/git",
        {
          "assets": [
            "docs/CHANGELOG.md"
          ]
        }
      ],
      "@semantic-release/github",
      [
        "@semantic-release/npm",
        {
          "pkgRoot": "./pkg/"
        }
      ]
    ]
  },
```

Am I doing anything wrong? Thank you in advance for taking a look!
