### ISSUE TITLE
Exec Does Not Commit Version file

### ISSUE THREAD

**Issue by mohammadsrahman** [semantic-release/semantic-release#1549]
## Current behavior

When I run my pipeline. Package.json and CHANGELOG.md are commited with the new version. This is not the case for VERSION file. Which is not updated.

My .releaserc.yaml looks as below:

```
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/exec'
    - verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION'
      prepareCmd: 'echo ${nextRelease.version} > VERSION'
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/npm'
    - npmPublish: false
  - - '@semantic-release/git'
    - assests: ['VERSION', 'package.json', 'CHANGELOG.md']
  - '@semantic-release/gitlab

branches:
  - 'master'
  - '+([0-9])?(.{+([0-9]),x}).x'
  - name: 'alpha'
    prerelease: 'alpha'
```

## Expected behavior

I would expect the VERSION file to also be updated and committed as part of the '@semantic-release/git' part.  

## Environment

- **semantic-release** version: 17.0.7
- CI environment: gitlab
- Plugins used:  
 + @semantic-release/gitlab@6.0.4
 + @semantic-release/changelog@5.0.1
 + @semantic-release/git@9.0.0
 + @semantic-release/exec@5.0.0
 + @semantic-release/npm@7.0.5

**Comment by DiogoAbu** [comment]
The code posted has a typo: `assests` should be `assets`. Can you check your yaml?

**Comment by mohammadsrahman** [comment]
@DiogoAbu Cheers. I have now resolved it already. But maybe you can help me with the next question. I am trying to execute multiple prepareCmd's. Would this be how to do it?

```
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/exec'
    - verifyReleaseCmd: echo ${nextRelease.version} > VERSION
      prepareCmd:
        - echo ${nextRelease.version} > VERSION
        - sed -i -e "s/version:.*/version: ${nextRelease.version}/" charts/*/Chart.yaml
        - sed -i -e "s/appVersion:.*/appVersion: ${nextRelease.version}/" charts/*/Chart.yaml
  - - '@semantic-release/changelog'
    - changelogFile: CHANGELOG.md
  - - '@semantic-release/npm'
    - npmPublish: false
  - - '@semantic-release/git'
    - assets:
        - VERSION
        - CHANGELOG.md
        - package.json
        - package-lock.json
        - charts/*/Chart.yaml
  - '@semantic-release/gitlab'

branches:
  - 'master'
  - '+([0-9])?(.{+([0-9]),x}).x'
  - name: 'alpha'
    prerelease: 'alpha'

```
