### ISSUE TITLE
release works but creates multiple publish comments on GitHub

### ISSUE THREAD

**Issue by zeke** [semantic-release/semantic-release#1580]
## Current behavior

I have a semantic-release setup that has been working normally but did some strange things on the most recently merged pull request today:

- The npm publish worked 👍 
- The GitHub release worked 👍 
- There are 4 duplicate `🎉 This PR is included in version 4.1.0 🎉` comments on the pull request.
- There's an octokit/request error in the GitHub Actions log:

```
  attemptNumber: 4,
  retriesLeft: 0,
  pluginName: '@semantic-release/github'
}
AggregateError: 
    HttpError: Server Error
        at /home/runner/work/openapi/openapi/node_modules/@octokit/request/dist-node/index.js:66:23
    HttpError: Server Error
        at /home/runner/work/openapi/openapi/node_modules/@octokit/request/dist-node/index.js:66:23
    at /home/runner/work/openapi/openapi/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
```

## Expected behavior

I expected to see one release comment and no errors in the logs.

## Environment

- **semantic-release** version: 
- CI environment: GitHub Actions
- Plugins used: None
- **semantic-release** configuration: 

```yml
name: Release npm package

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

- CI logs: https://gist.github.com/zeke/9454174fc2ee987db64697e29a986e10
