### ISSUE TITLE
Is posible to tell semantic-release what is my current version?

### ISSUE THREAD

**Issue by sk8Guerra** [semantic-release/semantic-release#1640]
## Current behavior

I have an npm package in version 1.9.2 and from this version, I implemented semantic-release in my project, also with travis. So when I push a new feature to github, travis takes that push, run the tests and finally semantic-release tries to update to version of the package and publish it to npm.

## Expected behavior

The new release to npm should be the v.1.10.2 but it tries to release the v1.0.0

## Environment

- **semantic-release** version: ^17.1.2
- CI environment: Travis

```yml
sudo: false
language: node_js
cache:
  npm:
    false
notifications:
  email: false
node_js:
  - 11.10.1
before_install:
  - npm i -g npm@^6.7.0
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
```

- Plugins used: any
- **semantic-release** configuration: any
- CI logs: https://travis-ci.org/github/sk8Guerra/werkstatt/builds/730108575

Here is the package: https://github.com/sk8Guerra/werkstatt
