### ISSUE TITLE
[Feature Request] command to just print next version semantic-release would use

### ISSUE THREAD

**Issue by jedwards1211** [semantic-release/semantic-release#1647]
I'm using semantic-release to deploy some stuff in CI and it's getting in my way really bad.

The process of choosing the next version feels too tightly coupled to all the steps that come after it.

I need to:
* Build a docker container and an npm package in parallel with my tests, **without** actually publishing either one
* Later, after the build and test jobs have passed, in a deploy job in a separate container in CI, actually publish the docker container and npm package

I used to test and then run semantic-release in the same build job but it's too slow, gotta run the build and tests in parallel.

I'm using `@semantic-release/exec` with `prepareCmd` to receive the release version.

My hope was to:
* Run `semantic-release --dry-run` in the build job to build the assets
* Run `DO_PUBLISH=1 semantic-release` in the deploy job to actually publish the built docker container, npm package, git tag and git release

However `semantic-release --dry-run` skips the `prepare` step of `@semantic-release/exec` (argh!)
`@semantic-release/npm` has an option to disable publish but `@semantic-release/github` doesn't currently have an option to not create tag and release (argh!)

I guess I'll just do a `--dry-run` and extract the version it chooses with a regex, but this is messy.
It would all be sooooooo much simpler if I could just run a simple command that prints the next version semantic-release wants to use.

**Comment by jdbruijn** [comment]
I have a similar issue where I'd like to have the next version of `semantic-release` before actually publishing. I know it can be a bit tricky since in-between getting the version and actually publishing there could be another commit that prevents publishing in the current workflow but it still has its cases. Maybe something like a `--version-only` CLI option that just prints the version and then exits?
In the meantime, although it is indeed a bit messy, can be to do a `--dry-run` and `grep` the version (crudely).

```shell
$ npx --no-install semantic-release --no-ci --dry-run | grep -oP 'The next release version is \K[0-9]+\.[0-9]+\.[0-9]+'
2.1.2
```

**Comment by chgl** [comment]
I'm using a similar workaround:

```json
{
  "plugins": [
    [
      "@semantic-release/exec",
      {
        "verifyReleaseCmd": "echo ${nextRelease.version} > .VERSION"
      }
    ]
  ]
}
```

```sh
npx semantic-release --dry-run --no-ci
```

Which writes the next version to the `.VERSION` file.

**Comment by jedwards1211** [comment]
@chgl the fiddly thing is you would need one config file to run that, and another config file to run the other stuff like GitHub release notes.  But the `semantic-release` command doesn't take a `--command` option so you'd have to overwrite the config property/file on the fly, which feels gross.

**Comment by chgl** [comment]
@jedwards1211 you'll need two jobs: one "dry-run"-ning to get the next version, and one actually running to create the GitHub Release and Git Tag. But the config remains the same. For example, my GitLab pipeline looks like this:

<details>
<summary>.gitlab-ci.yml - Click to expand</summary>
<p>

```yaml
get next version:
  image: r.example.com/semantic-release:v17
  stage: version
  script:
    - npx semantic-release --dry-run --branches master,$CI_COMMIT_REF_NAME --no-ci
    - test -e .VERSION || (echo $(git describe --abbrev=0 --tags | tr -d v) > .VERSION && touch .NORELEASE)
    - echo "Determined Version $(cat .VERSION)"
  artifacts:
    paths:
      - .VERSION
      - .NORELEASE
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_COMMIT_TAG == null
    - if: $CI_MERGE_REQUEST_ID

build:
  stage: build
  variables:
    DOCKER_BUILDKIT: 1
    BUILDKIT_PROGRESS: plain
  script:
    - export VERSION=$(cat .VERSION)
    - docker build -t $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
      --build-arg VERSION=$VERSION
      --build-arg GIT_REF=$CI_COMMIT_SHA
      --build-arg BUILD_TIME="$(date -Is)" .
    - docker push $IMAGE_PATH:$CI_COMMIT_SHORT_SHA

registry release:
  stage: release
  image: docker:stable
  script:
    - VERSION=$(cat .VERSION)
    - VERSION_MAJOR=$(echo $VERSION | cut -d. -f1)
    - VERSION_MINOR=$(echo $VERSION | cut -d. -f2)
    - SHORTVERSION=$VERSION_MAJOR.$VERSION_MINOR
    - docker pull $IMAGE_PATH:$CI_COMMIT_SHORT_SHA
    - docker tag $IMAGE_PATH:$CI_COMMIT_SHORT_SHA $IMAGE_PATH:$VERSION
    - docker tag $IMAGE_PATH:$CI_COMMIT_SHORT_SHA $IMAGE_PATH:$SHORTVERSION
    - docker push $IMAGE_PATH:$VERSION
    - docker push $IMAGE_PATH:$SHORTVERSION
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

gitlab release:
  image: r.example.com/semantic-release:v17
  stage: release
  script:
    - npx semantic-release
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
```

</p>

<p>

(Note that currently the image tags arent't immutable because even if the commit message doesn't bump the version images are re-build and pushed using the old version number. I should definitely check for the presence of `.NOVERSION`...)

</p>

</details>

**Comment by jedwards1211** [comment]
Ah I see, yeah makes sense with --dry-run.

**Comment by marktoujiline** [comment]
I'm interested in this as well. Would you welcome a PR?

**Comment by jedwards1211** [comment]
@chgl 
> Which writes the next version to the .VERSION file.

Except when there are no changes, `semantic-release` bails before running the `verifyReleaseCmd`, sigh

**Comment by chgl** [comment]
> @jedwards1211 
> Except when there are no changes, `semantic-release` bails before running the `verifyReleaseCmd`, sigh

Unfortunately, yes. To at least allow for handling this, my .gitlab-ci.yml does the following: `test -e .VERSION || (echo $(git describe --abbrev=0 --tags | tr -d v) > .VERSION && touch .NORELEASE)`. So if no change is detected, use the latest git tag (ie the last published version), write it to the .VERSION file and create a .NORELEASE file which can later be used to check if a new release is actually supposed to occur.

**Comment by felipecrs** [comment]
I just published a new plugin, [`semantic-release-export-data`](https://github.com/felipecrs/semantic-release-export-data#readme) which should help in this matter.

It works in `--dry-run` mode, check this example:

https://github.com/felipecrs/semantic-release-export-data#github-actions-example

**Comment by simlu** [comment]
For anyone wondering why this thread is so short, here is the original one: https://github.com/semantic-release/semantic-release/issues/753

**Comment by char0n** [comment]
Here is a recipe for find out the next release version before actually releasing, using GitHub Actions.

**.releaserc**
```json
{
  "branches": [a
    {"name": "master"},
    {"name": "next", "channel": "alpha", "prerelease": "alpha"}
  ],
  "tagFormat": "v${version}",
  "plugins": [
    "@semantic-release/commit-analyzer",
    [
      "@semantic-release/exec",
      {
        "verifyReleaseCmd": "echo \"NEXT_RELEASE_VERSION=${nextRelease.version}\" >> $GITHUB_ENV"
      }
    ],
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    "@semantic-release/github",
    ["@semantic-release/git", {
      "assets": [
        "package.json",
        "package-lock.json"
      ],
      "message": "chore(release): cut the ${nextRelease.version} release\n\n${nextRelease.notes}"
    }]
  ]
}
```

**release.yml** (GitHub workflow)
```yaml
name: Release SwaggerEditor@next
on:
  workflow_dispatch:
    branches:
      - next

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
          submodules: true
          ref: next

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@swagger-api"

      - name: Determine the next release version
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: true
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}

      - name: Nothing to release
        if: ${{ env.NEXT_RELEASE_VERSION == '' }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Nothing to release')

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}

      - name: Prepare for the Release
        env:
          REACT_APP_VERSION: ${{ env.NEXT_RELEASE_VERSION }}
        run: |
          npm run lint
          npm run test
          npm run build:app
          npm run cy:ci
          npm run build:bundle:esm
          npm run build:bundle:umd

      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        with:
          dry_run: false
          extra_plugins: |
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}

      - name: Release failed
        if: steps.semantic.outputs.new_release_published == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Release failed')

      - name: Release published
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo ${{ steps.semantic.outputs.new_release_major_version }}
          echo ${{ steps.semantic.outputs.new_release_minor_version }}
          echo ${{ steps.semantic.outputs.new_release_patch_version }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: ./build
```
