### ISSUE TITLE
Automatic rebase with dev branch after commit to master

### ISSUE THREAD

**Issue by denis-ev** [semantic-release/semantic-release#1651]
## New feature motivation

I'm working with a master and dev branch, everyone only clones the repo and the master is always latest.
I've been trying to get it to work as is, but it won't work.

Every PR is getting squash merged into dev and when we are happy with it and like to bump the version, we would just run `git rebase dev master`, the CI (Travis CI) would do the Versioning and the rebase into dev and that's it.

Main Problem:
- custom VERSION file is not getting updated [The Project](https://github.com/VivumLab/VivumLab)
- a rebase back to dev creates inconsistency because VERSION file is not updated, every commit to master would trigger another release

I'm open to different ideas too tho.

## New feature description

- Plugin to rebase to a set branch
- Plugin set custom files to be updated (plaintext for example)
- - there is one plugin which needs a placeholder to work, but that won't work because of the VERSION change

## New feature implementation

Don't know how to implement it

**Comment by gempain** [comment]
Totally agree with this. I remember reading a while back that semantic-release's philosophy is that every feature should be released directly, but I disagree with that. Most of the time, you have planned releases or at least work on a few things and release them on the `next` branch before releasing them. 

We've done this with a bash script for a few years now, but it requires quite a bit of setup as we do it with SSH keys:

```bash
[[ "$1" == "" ]] && echo 'missing base branch ($1)' && exit 1;
BASE_BRANCH="$1"

[[ "$2" == "" ]] && echo 'missing head branch ($2)' && exit 1;
HEAD_BRANCH="$2"

# save head to come back to it after we're done rebasing
HEAD=$(git rev-parse HEAD | tr -d '\n')

# reduce log verbosity
git config advice.detachedHead false

# cleanup workspace
git reset --hard

# update everything
git fetch

# move to head branch and update
git checkout $HEAD_BRANCH
git pull --rebase

# move to base branch
git checkout $BASE_BRANCH
git branch -u origin/$BASE_BRANCH
git pull --rebase
#git push --set-upstream origin $BASE_BRANCH
git merge --ff -m "chore: realign $BASE_BRANCH on $HEAD_BRANCH [ci skip]" $HEAD_BRANCH
git push
git checkout $HEAD
```

and then in Github Actions:

```yaml
# ...
     - name: "realign next"
        if: ${{ env.IS_RELEASE_BRANCH == 'true' }}
        run: |
          source ./scripts/setup-git.sh "$RELEASE_DEPLOY_KEY"
          HEAD_BRANCH=`echo "${GITHUB_REF//refs\/heads\//}" | tr -d '\n'`
          ./scripts/rebase-git-branch.sh "next" "$HEAD_BRANCH"
        env:
          RELEASE_DEPLOY_KEY: ${{ secrets.RELEASE_DEPLOY_KEY }}
```

Quite some code for just rebasing to be honest. The setup script is as follows (because we use SSH deploy keys that are project scoped and hence can't harm much if leaked):

```bash
[[ "$1" == "" ]] && echo 'missing deploy key ($1)' && exit 1;
DEPLOY_KEY="$1"

# install ssh and add ssh key for semantic-release
which ssh-agent || apk add openssh
eval $(ssh-agent -s)
echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -
mkdir -p ~/.ssh
chmod 700 ~/.ssh
# setup git
git config user.name "semantic-release"
git config user.email "release@id6.io"
```
