### ISSUE TITLE
Gitlab CI error "Cannot find module '@semantic-release/changelog'"

### ISSUE THREAD

**Issue by EsaxCO** [semantic-release/semantic-release#1673]
My gitlab ci config for release job looks like
```
release:
  tags:
    - powershell
  stage: release
  variables:
      GITLAB_TOKEN: $ACCESS_TOKEN
  before_script:
    - npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/gitlab @semantic-release/git @semantic-release/npm @semantic-release/release-notes-generator
  script:
      - npx semantic-release
  only:
      - master
  except:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TITLE =~ /^RELEASE:.+$/
```

```yaml
branches: ['master']
ci: true
debug: true
dryRun: false
tagFormat: '${version}'

preset: 'conventionalcommits'
gitlabUrl: 'https://url/' # your gitlab url

verifyConditions:
  - '@semantic-release/changelog'
  - '@semantic-release/git'
  - '@semantic-release/gitlab'

analyzeCommits:
  - path: '@semantic-release/commit-analyzer'

generateNotes:
  - path: '@semantic-release/release-notes-generator'
    writerOpts:
      groupBy: 'type'
      commitGroupsSort: 'title'
      commitsSort: 'header'
    linkCompare: true
    linkReferences: true

prepare:
  - path: '@semantic-release/changelog'
  - path: '@semantic-release/git'
    message: 'RELEASE: ${nextRelease.version}'
    assets: ['CHANGELOG.md']

publish:
  - path: '@semantic-release/gitlab'

success: false

fail: false
```

Everytime in release job I have an error, but I have installed modules in before_script. What could be wrong?
```
Cannot find module '@semantic-release/changelog'
```
