### ISSUE TITLE
Add support for GItHub app installation token

### ISSUE THREAD

**Issue by npalm** [semantic-release/semantic-release#1807]
## New feature motivation

For running a semantic release on protected branch on github admin rights on the repo are required. One option is create a release user (service-account) for which a PAT token is used to run the release. A better and more secure approach is uing a GitHub app. And only grant the app for the requires rights. This also avoid creating users. 

## New feature description

Add suport for using the GitHub app installation token. In the current way semantic release is using a github auth url is generated which not works for an GitHub app. To use the GitHub app installation token a url of the form ` https://x-access-token:$GITHUB_TOKEN@github.com/owner/repo` needs to be generated. I have tried to use the option `--repositoryUrl` to pass the repo url, which works. But in case if the repo is behind, it generates an strang error. The error is cased by a catch to check the `git pull`. In the catch clause en invallid url is created.

## New feature implementation

For crating the github auth url it is requred to understand if the token is app token. Therefor the most trivial approach is adding a variable to support the token. Downside is that the number of tokens that is support is increasing.

**Comment by gr2m** [comment]
We do currently support GitHub App installation tokens, but only in the context of GitHub Actions, as `secrets.GITHUB_TOKEN` is technically an installation access token.

I agree your use case is valid.

> I have tried to use the option `--repositoryUrl` to pass the repo url, which works. But in case if the repo is behind, it generates an strang error. The error is cased by a catch to check the `git pull`. In the catch clause en invallid url is created.

That sounds like an independent problem that we could address first, as it sounds like it would unblock the workaround for you? Can you start a pull request with a failing test that reproduces the problem?

**Comment by Merlin-Taylor** [comment]
I ran into this issue today too. In my case I read this line in the code, which adds *the x-access-token:* prefix if the *GITHUB_ACTION* environment variable is set.

https://github.com/semantic-release/semantic-release/blob/971a5e0d16f1a32e117e9ce382a1618c8256d0d9/lib/get-git-auth-url.js#L67

and re-ran *semantic-release* with the *GITHUB_ACTION* environment variable set to *yes*. This worked. I would be happy to update the documentation to reflect this. This looks like the most appropriate place:

https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication

**Comment by sunggun-yu** [comment]
@Merlin-Taylor 
wow, thank you so much! It works in circleci with `GITHUB_ACTION=yes` 🤣

**Comment by npalm** [comment]
We using semantic release indeed with a token from an App, but I think it is still quiet hard. See here an example:

```yaml
- name: Get installation token
        uses: npalm/action-app-token@v1.0.0
        id: app-token
        with:
          appId: ${{ secrets.FOREST_RELEASER_APP_ID }}
          appPrivateKeyBase64: ${{ secrets.FOREST_RELEASER_APP_PRIVATE_KEY_BASE64 }}
          appInstallationType: repo
          appInstallationValue: ${{ github.repository }}

      - name: Release
        if: github.event_name != 'pull_request' && contains('refs/heads/main', github.ref)
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          cp .release/* .
          yarn
          yarn release --repositoryUrl https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          
```

**Comment by roman-shandurenko** [comment]
> GITHUB_ACTION environment variable set to yes

@Merlin-Taylor Thanks, it helped in circle ci!

**Comment by gr2m** [comment]
fyi there is an official action by GitHub now: https://github.com/actions/create-github-app-token

If you want to use the provided GITHUB_TOKEN you need to set permissions explicitly:
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#defining-access-for-the-github_token-scopes

```yml
permissions:
   # needed to create tags and releases
  contents: write
  # needed for release notifications
  issues: write
  pull-requests: write 
```
