### ISSUE TITLE
Dry-run for previewing release does nothing

### ISSUE THREAD

**Issue by XC-** [semantic-release/semantic-release#1890]
## Current behavior

Dry-run does nothing and instead reports something like:
`This run was triggered by a pull request and therefore a new version won't be published.` or
`[2:59:20 PM] [semantic-release] › ℹ  This test run was triggered on the branch refs/pull/3/merge, while semantic-release is configured to only publish from main, therefore a new version won’t be published.`

## Expected behavior

Dry-run runs the normal steps and plugins like with a release but does not commit anything or release artifacts.

## Environment

- **semantic-release** version: ^17.4.2
- CI environment: Github actions
- Plugins used: 
- **semantic-release** configuration: https://github.com/XC-/semantic-release-commitlint/blob/test/releaserc-configuration/.releaserc
- CI logs: https://github.com/XC-/semantic-release-commitlint/runs/2334857005?check_suite_focus=true#step:3:29 and https://github.com/XC-/semantic-release-commitlint/runs/2334409061?check_suite_focus=true#step:3:31

**Comment by guilhermetod** [comment]
The issue appears to be with [env-ci](/semantic-release/env-ci). It doesn't matter if you checkout the actual branch, it'll parse the branch from the Github Action event. Maybe if `--no-ci` is specified, [this variable](https://github.com/semantic-release/semantic-release/blob/628e29e4132c96e2da32a1a05293983f0bb32986/index.js#L30) should not look at envci and instead get the output from something like `git branch --show-current`.

**Comment by guilhermetod** [comment]
Ok, I found a workaround. Not sure if it's ideal, but it's working if anyone is interested

1. We need to checkout to the actual PR branch
2. We need unset "GITHUB_ACTIONS" from env so that `env-ci` will infer the branch name from git instead of GH Actions data

```
      - name: Checkout branch
        run: git checkout $GITHUB_HEAD_REF
      - name: Preview semantic-release
        run: unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci
```

If you're running in a CI other than GitHub actions, I suggest you look at its [corresponding `detect` criteria](https://github.com/semantic-release/env-ci/blob/master/services) so that you can force it to false and get force `semantic-release` to use git

**Comment by guilhermetod** [comment]
@seedy I create an action for this. I combine it with `create-or-update-comment`, in a way that my `yml` file looks like this:

```yml
name: Integration

on: pull_request

jobs:
  preview_release_notes:
    runs-on: ubuntu-latest
    name: Preview release notes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          registry-url: https://npm.pkg.github.com/omnichat
          node-version: 12
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Generate release notes preview
        id: build-release-notes
        uses: guilhermetod/semantic-release-notes-preview@v1.0.0
      - name: Comment release notes preview
        if: steps.build-release-notes.outputs.releaseNotes
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: |
            ## 👋 Hey there!
            Thank you for you contribution. Below is a preview of the release notes if your PR gets merged.
            Please, make sure it includes all your significant changes with descriptive messages.
            Keep in mind that release notes are automatically generated from the commit messages according to [conventional commits](https://www.conventionalcommits.org/).
            If you feel like you need to change anything, please take a look into [this guide](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#addressing-review-feedback) to learn how you can fixup your commits.

            ---

            ${{ steps.build-release-notes.outputs.releaseNotes }}

```

I hope this helps you!

**Comment by TJM** [comment]
I thought I would be clever and just send my "current" branch in, but it "helpfully" detects that I am in a merge request, and doesn't tell me the proposed version. I want to be able to see, and potentially even use somewhere (with the exec plugin), the proposed version. However, this is what I get:

```console
$ npx semantic-release --dry-run --branches master,$CI_COMMIT_BRANCH
[11:[50](https://gitlab.gcp.davita.com/shared-services/terraform-modules/vault-gcp-secret-engine/-/jobs/1434256#L50):04 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[11:50:04 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[11:50:04 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[11:50:04 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[11:50:04 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[11:50:04 PM] [semantic-release] › ℹ  This run was triggered by a pull request and therefore a new version won't be published.
Cleaning up project directory and file based variables
00:01
Job succeeded
```

Config (.gitlab-ci.yml)

```yaml
dry-run-release:
  stage: deploy
  image: node:17-alpine
  before_script:
    - apk add git
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - ./scripts/git-configure-token.sh
    - npx semantic-release --dry-run --branches master,$CI_COMMIT_BRANCH
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
```

NOTE: the "git-configure-token.sh" script switches out the default CI token, which is read-only, for another "RW" token from a CI/CD var.

**Comment by mipaull** [comment]
@TJM if you also pass through the `--no-ci` flag, semantic-release won't do the CI environment checks and so will skip the pull request check. This command should do the full dry run:

`npx semantic-release --dry-run --no-ci --branches master,$CI_COMMIT_BRANCH`

**Comment by csantos1113** [comment]
The most annoying thing is that it ends up returning `refs/pull/35/merge` regardless if I let it run in GITHUB (my CI) or in GIT (doing `unset GITHUB_ACTIONS`)

Github env: https://github.com/semantic-release/env-ci/blob/b39d3440157a17e89fc964876f4b5eb38df991d5/services/github.js#L39

Git env: https://github.com/semantic-release/env-ci/blob/b39d3440157a17e89fc964876f4b5eb38df991d5/lib/git.js#L11

Which would be ok IF ONLY `semantic-release` wasn't checking THAT against real branch names 🙄  which will NEVER MATCH. This is quite disappointing 😞

https://github.com/semantic-release/semantic-release/blob/1beeb84c9032a22d455fc21b9a736efbcfde6b5d/index.js#L40-L41

https://github.com/semantic-release/semantic-release/blob/1beeb84c9032a22d455fc21b9a736efbcfde6b5d/index.js#L69-L73

Any updates from semantic-release contributors on how make this work?

**Comment by OliverEhrhardt** [comment]
I want to point out that the docs for the dry run feature makes it sound like this is possible:
https://semantic-release.gitbook.io/semantic-release/support/faq#is-there-a-way-to-preview-which-version-would-currently-get-published
But from digging around on this thread and others, such as [this](https://github.com/semantic-release/semantic-release/issues/722#issuecomment-378975356), it sounds like the dry run feature is not meant for release preview, but more for setting up semantic version itself. I think some more clear documentation is needed around this flag if it's intent is not meant for previewing releases, but rather setup verification. Currently, it's unclear how to use this flag in a CI environment that would be useful, and my own experiments have come up dry. I know my team would very much like this feature, but I'm hesitant to implement any of the workarounds on here in fear of having some other un-intended bug popping up. Would be nice if this was an actual feature.

**Comment by BinToss** [comment]
I believe all messages ending with `...therefore a new version won’t be published.` should be followed by, on a new line...
- the new version would have remained as x.y.z (configuration is working AND commits were analyzed)
- the new version would have bumped to x.y.z. (configuration is working AND commits were analyzed)
- the new version could not be determined. (configuration is invalid OR unable to analyze commits)

Or, for simplicity
- the version could have been (x.y.z | UNDETERMINED).

Currently, errors irrelevant in dev environments such as `ENOGHTOKEN` and non-error rules as as "The local branch `main` is behind the remote one, therefore a new version won't be published." *prevent* users from troubleshooting configuration errors and improving existing configurations without `PUSH`ing to remote...which, when checking single-line changes, can be annoying or even lead to undesired changes by the CI/CD environment. The latter can be resolved by first adjusting the CI/CD's invokation of semantic-release to *also* use `--dry-run`, but then you need at least two more commits (and/or changes in a web interface) for diagnostics that could have been done without committing or pushing.

`@GitTools/GitVersion`'s CLI has comparable commit analysis and version generation capabilities. It can work offline, while out-of-sync with remote, and with uncommitted changes.
<details><summary>GitTools' GitVersion CLI output</summary>

```json
> gitversion
{
  "Major": 2,
  "Minor": 3,
  "Patch": 0,
  "PreReleaseTag": "feat-AvanloniaUI.253",
  "PreReleaseTagWithDash": "-feat-AvanloniaUI.253",
  "PreReleaseLabel": "feat-AvanloniaUI",
  "PreReleaseLabelWithDash": "-feat-AvanloniaUI",
  "PreReleaseNumber": 253,
  "WeightedPreReleaseNumber": 253,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.feat-AvanloniaUI.Sha.4cbbd44a302bf6c156b76212df7c68e0502ac298",
  "MajorMinorPatch": "2.3.0",
  "SemVer": "2.3.0-feat-AvanloniaUI.253",
  "LegacySemVer": "2.3.0-feat-AvanloniaUI253",
  "LegacySemVerPadded": "2.3.0-feat-AvanloniaUI0253",
  "AssemblySemVer": "2.3.0.0",
  "AssemblySemFileVer": "2.3.0.0",
  "FullSemVer": "2.3.0-feat-AvanloniaUI.253",
  "InformationalVersion": "2.3.0-feat-AvanloniaUI.253+Branch.feat-AvanloniaUI.Sha.4cbbd44a302bf6c156b76212df7c68e0502ac298",
  "BranchName": "feat/AvanloniaUI",
  "EscapedBranchName": "feat-AvanloniaUI",
  "Sha": "4cbbd44a302bf6c156b76212df7c68e0502ac298",
  "ShortSha": "4cbbd44",
  "NuGetVersionV2": "2.3.0-feat-avanloniaui0253",
  "NuGetVersion": "2.3.0-feat-avanloniaui0253",
  "NuGetPreReleaseTagV2": "feat-avanloniaui0253",
  "NuGetPreReleaseTag": "feat-avanloniaui0253",
  "VersionSourceSha": "5c973c9326cc7412bd47f743a2e1ab82cf4995f2",
  "CommitsSinceVersionSource": 253,
  "CommitsSinceVersionSourcePadded": "0253",
  "UncommittedChanges": 14,
  "CommitDate": "2023-07-17"
}
```
</details>

**Comment by Avivbens** [comment]
# Hi all 👋 

**I've created a nice GitHub action workflow, with no additional configuration needed 👍** 

### Here are the workflow results for `chore` commit:
![CleanShot 2024-01-19 at 22 40 23@2x](https://github.com/semantic-release/semantic-release/assets/77183871/9f4e2f9f-7a6a-44ca-b606-c758e11286f7)


### Once you committed additional stuff, it will remove the last report and create a new one. Here are the results for `fix` commit:
![CleanShot 2024-01-19 at 22 41 17@2x](https://github.com/semantic-release/semantic-release/assets/77183871/82b64078-e404-4f76-9c45-54d791a5ad25)



### The workflow:
```
---
name: Semantic Release Check 📝
on:
    pull_request:
        branches:
            - master

permissions: write-all

jobs:
    PR-checks:
        runs-on: ubuntu-latest
        name: Semantic Release Check 📝
        steps:
            - name: 📀 Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: 🖥️ Setup Env
              uses: ./.github/workflows/install

            - name: 🔬 Check semantic versioning
              id: semantic-release
              run: |
                  GITHUB_REF=${{ github.head_ref }}
                  npx semantic-release --no-ci --dry-run --plugins @semantic-release/commit-analyzer,@semantic-release/release-notes-generator --branches ${{ github.head_ref }} > output.txt
                  OUTPUT=$(cat output.txt | base64 -w 0)
                  echo "::set-output name=releaseNote::$OUTPUT"

            - name: 📝 Report semantic versioning
              uses: actions/github-script@v3
              if: ${{ steps.semantic-release.outputs.releaseNote != '' }}
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      // build release note
                      const semanticReleaseOutput = Buffer.from('${{ steps.semantic-release.outputs.releaseNote }}', 'base64').toString('utf8');
                      const semanticReleaseLogMatch = /^[[0-9:\sAMPM]+\]\s\[semantic-release\].*$/;
                      const lines = semanticReleaseOutput.split('\n');
                      const lastSemanticReleaseLogIndex = [...lines]
                          .reverse()
                          .findIndex((line) => line.match(semanticReleaseLogMatch));

                      const releaseNoteIndex = lines.length - lastSemanticReleaseLogIndex;
                      const releaseNote = lines.slice(releaseNoteIndex);

                      let res = releaseNote.join('\n');
                      if (!releaseNote.length || !res) {
                          res = '### No release note would be generated.';
                      }

                      const SEMANTIC_RELEASE_BODY_HEADER = '## 📝 Semantic Release Report';
                      const body = [SEMANTIC_RELEASE_BODY_HEADER, res].join('\n');

                      // get last comment
                      const comments = await github.issues.listComments({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo
                      });

                      // find comments to delete
                      const commentsToDelete = comments.data.filter((comment) =>
                          comment.body.startsWith(SEMANTIC_RELEASE_BODY_HEADER)
                      );

                      // delete comments
                      const prms = commentsToDelete.map((comment) =>
                          github.issues.deleteComment({
                              comment_id: comment.id,
                              owner: context.repo.owner,
                              repo: context.repo.repo
                          })
                      );

                      await Promise.all(prms);

                      // create new comment for release note
                      github.issues.createComment({
                          issue_number: context.issue.number,
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          body
                      });

```

## NOTE:
I'm using an internal workflow for setup env, basically, just installing deps and setup NodeJS version 👍 


**Enjoy 🥳** 


CC: @TJM @seedy @OliverEhrhardt @XC- @BinToss

**Comment by BinToss** [comment]
@Avivbens, does it truly need `write-all` permissions?

**Comment by Avivbens** [comment]
> @Avivbens, does it truly need `write-all` permissions?

Nope, just didn't wanted to deal with the permissions, as the action does require a bunch of them. 

Of course, you can modify the permissions by the actual requirements, and let us know 🙌

**Comment by scootafew** [comment]
> Ok, I found a workaround. Not sure if it's ideal, but it's working if anyone is interested
> 
> 1. We need to checkout to the actual PR branch
> 2. We need unset "GITHUB_ACTIONS" from env so that `env-ci` will infer the branch name from git instead of GH Actions data
> 
> ```
>       - name: Checkout branch
>         run: git checkout $GITHUB_HEAD_REF
>       - name: Preview semantic-release
>         run: unset GITHUB_ACTIONS && npx semantic-release --dry-run --no-ci
> ```
> 
> If you're running in a CI other than GitHub actions, I suggest you look at its [corresponding `detect` criteria](https://github.com/semantic-release/env-ci/blob/master/services) so that you can force it to false and get force `semantic-release` to use git

After some trial and error this was the answer that helped me get things working as I wanted, but I can suggest an improvement based on a couple of issues I encountered:

- By using `$GITHUB_HEAD_REF` semantic-release will use the settings for the head (source) branch of our PR and not the base (destination), potentially leading to a different result to the one that will be calculated on the base when we merge the PR. For example, maybe the base branch is actually configured to be a pre-release or maintenance branch.
- Also, because we're using just the code from the head branch, if there were any commits to the base branch which are not included in our PR then the computed version will not account for them. Sure, we can fix that by ensuring our PR is kept up to date with the base branch, but this may not always be possible.

It is tempting then to replace `$GITHUB_HEAD_REF` with `$GITHUB_REF` (e.g. `refs/pull/x/merge`), but this would only solve the second problem. We'd be using the correct commit, but pointing to a ref which doesn't exist on the remote and therefore can't have any semantic-release config associated to it. Anyway, as mentioned by @csantos1113, semantic-release will actually just error out because it calls out to GitHub and finds that this ref doesn't really exist.

Therefore, we ideally want to run semantic-release on the branch with name matching the base of our PR (which must exist on the remote, and will be configured with the correct branch settings), but with the commit ref from `refs/pull/x/merge` (e.g. the result of the merge commit). Using the trick to `unset GITHUB_ACTIONS` and force semantic-release to use Git, this can be achieved by running the following:

```yaml
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: semantic-release
        run: |
            # the below line gets us locally to the result of the PR merge on the correct ref
            git checkout -b ${{ github.base_ref }} pull/${{ github.event.number }}/merge
            unset GITHUB_ACTIONS; npx semantic-release --no-ci --dry-run
```
I can't promise it works in every edge-case, but this seems to be behaving as I'd hope dry-run on a PR would.
