### ISSUE TITLE
Plugin config is very strange and hard to get right

### ISSUE THREAD

**Issue by ryboe** [semantic-release/semantic-release#1896]
## Current behavior

Here's a very `.releaserc` I just had to write.
```json
{
  "branches": ["main"],
  "plugins": [
    ["@semantic-release/commit-analyzer", {
      "preset": "conventionalcommits"
    }],
    "@semantic-release/release-notes-generator",
    "@semantic-release/gitlab",
    [
      "semantic-release-slack-bot", {
        "notifyOnSuccess": true,
        "notifyOnFail": true,
        "markdownReleaseNotes": true
      }
    ]
  ]
}
```

The type of `plugins` is a _list of items that are either strings or lists of items that are either strings or objects_. This is hard to read and even harder to write. When I try to to write this type signature, I can't do it. I'm not smart enough.

It looks especially strange when converted into YAML.

```yaml
branches:
  - main

plugins:
  - - "@semantic-release/commit-analyzer":
    - preset: conventionalcommits
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/gitlab"
  - - "semantic-release-slack-bot"
    - notifyOnSuccess: true
      notifyOnFail: true
      markdownReleaseNotes: true
```

## Expected behavior

This would be much easier to understand:
```yaml
plugins:
  "@semantic-release/commit-analyzer":
    preset: conventionalcommits
  "@semantic-release/release-notes-generator": {}
  "@semantic-release/gitlab": {}
  "semantic-release-slack-bot":
    notifyOnSuccess: true
    notifyOnFail: true
    markdownReleaseNotes: true
```
The type of `plugins` here is `map[string,map[string|any]`.

I think simplifying the config would be worth a backwards-incompatible release. Perhaps a new `plugin_config` key could be added, and the old `plugins` key deprecated.

## Environment

- **semantic-release** version: v17.4.2
- CI environment: n/a
- Plugins used: see above
- **semantic-release** configuration: see above
- CI logs: n/a
