### ISSUE TITLE
Github Action Fails with @semantic-release/git

### ISSUE THREAD

**Issue by andriolisp** [semantic-release/semantic-release#1908]
## Current behavior

When I try to deploy on my github actions the new version of my application I have the following error:

```
 npx semantic-release
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
    GH_TOKEN: ***
    NPM_TOKEN: ***
    NODE_AUTH_TOKEN: ***
npx: installed 574 in 17.092s
[5:53:20 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.2
[5:53:20 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/git'
Require stack:
- /home/runner/work/spotsvc/spotsvc/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at resolveFileName (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/lib/plugins/utils.js:51:82)
    at /home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/lib/get-config.js:84:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/spotsvc/spotsvc/noop.js' ]
}
Error: Cannot find module '@semantic-release/git'
Require stack:
- /home/runner/work/spotsvc/spotsvc/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at resolveFileName (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/lib/plugins/utils.js:51:82)
    at /home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/home/runner/.npm/_npx/2023/lib/node_modules/semantic-release/lib/get-config.js:84:35)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/spotsvc/spotsvc/noop.js' ]
}
```

That is my package.json

```
{
    "name": "template",
    "version": "1.1.1",
    "scripts": {
        "lint": "eslint 'src/**/*'",
        "build": "tsc && npm run postbuild",
        "local": "npm run build && node dist/index.js",
        "start": "npm run shell",
        "prettier": "prettier --config .prettierrc 'src/**/*.ts' --write",
        "postbuild": "cpy src/lib/docs/* dist/lib/docs/"
    },
    "engines": {
        "node": "12"
    },
    "main": "dist/index.js",
    "dependencies": {
        "@getlst/models": "1.14.2",
        "@google-cloud/firestore": "^4.9.9",
        "axios": "^0.21.1",
        "class-validator": "^0.12.2",
        "cors": "^2.8.5",
        "dataloader": "^2.0.0",
        "express": "^4.17.1",
        "firebase-admin": "^9.3.0",
        "firebase-functions": "^3.6.1",
        "geofire-common": "^5.2.0",
        "geolib": "^3.3.1",
        "graphql": "15.3.0",
        "graphql-geojson": "^1.0.0",
        "lodash": "^4.17.21",
        "ngeohash": "^0.6.3",
        "reflect-metadata": "^0.1.13",
        "rxjs": "^6.6.7",
        "supercluster": "^7.1.3",
        "swagger-ui-express": "^4.1.4",
        "type-graphql-dataloader": "^0.3.7",
        "typeorm": "^0.2.32",
        "yamljs": "^0.3.0"
    },
    "devDependencies": {
        "@commitlint/cli": "^11.0.0",
        "@commitlint/config-conventional": "^11.0.0",
        "@semantic-release/changelog": "^5.0.1",
        "@semantic-release/git": "^9.0.0",
        "@semantic-release/github": "github:semantic-release/github",
        "@types/body-parser": "^1.19.0",
        "@types/cors": "^2.8.7",
        "@types/express": "^4.17.1",
        "@types/i18n": "^0.8.7",
        "@types/lodash": "^4.14.168",
        "@types/ngeohash": "^0.6.2",
        "@types/node": "^14.14.2",
        "@types/supercluster": "^5.0.2",
        "@types/swagger-ui-express": "^4.1.2",
        "@types/yamljs": "^0.2.31",
        "@typescript-eslint/eslint-plugin": "^3.9.1",
        "@typescript-eslint/parser": "^3.8.0",
        "commitlint": "^11.0.0",
        "cpy-cli": "^3.1.1",
        "eslint": "^7.6.0",
        "eslint-plugin-import": "^2.22.0",
        "eslint-plugin-yaml": "^0.3.0",
        "husky": "^4.3.5",
        "prettier": "^2.1.2",
        "semantic-release": "17.4.2",
        "typescript": "^3.9.7"
    },
    "peerDependencies": {
      "semantic-release": "17.4.2"
    },
    "commitlint": {
        "extends": [
            "@commitlint/config-conventional"
        ]
    },
    "husky": {
        "hooks": {
            "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
        }
    },
    "release": {
        "branches": [
            {
                "name": "master",
                "prerelease": false
            },
            {
                "name": "dev",
                "prerelease": true
            }
        ],
        "plugins": [
            "@semantic-release/npm",
            "@semantic-release/github",
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            "@semantic-release/git"
        ]
    },
    "private": true
}

```

## Expected behavior

Deploy with Github Actions and update package.json with the new version

## Environment

- **semantic-release** version: 17.4.2
- CI environment: Github Actions
- Plugins used: 
            "@semantic-release/npm",
            "@semantic-release/github",
            "@semantic-release/commit-analyzer",
            "@semantic-release/release-notes-generator",
            "@semantic-release/git"
- **semantic-release** configuration: My full package.json is attached to this
- CI logs: The semantic log is on this ticket also

**Comment by gr2m** [comment]
it looks like you don't run `npm install` before running `npx semantic-release`?

**Comment by andriolisp** [comment]
I do!

```
name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/".insteadOf
          ssh://git@github.com/
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install dependencies
        run: cd functions && npm ci
      - name: Bump Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          INPUT_ARGS: firebase deploy --only functions
        with:
          args: firebase deploy --only functions


```
