### ISSUE TITLE
Release chore runs on both tags and main (duplicated)

### ISSUE THREAD

**Issue by evanrich** [semantic-release/semantic-release#1928]
## Current behavior

Release Chore seems to run twice,  see image:
![image](https://user-images.githubusercontent.com/518320/117697103-f1727700-b176-11eb-8921-86c221c1dc7c.png)

## Expected behavior

Release chore runs only on tags

## Environment

- **semantic-release** version: 17.4.2
- CI environment: Gitlab 13.11
- Plugins used: @semantic-release/gitlab @semantic-release/changelog @semantic-release/git conventional-changelog-eslint

- **semantic-release** configuration: 
<details>
  <summary>Gitlab-ci.yml</summary>

```yaml
release:
  image: node:16-alpine3.13
  stage: release
  only:
    refs:
    - master
    - alpha
    # This matches maintenance branches
    - /^(([0-9]+)\.)?([0-9]+)\.x/
    # This matches pre-releases
    - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/ 
  except:
    refs:
      - tags
  script:
    - touch CHANGELOG.md
    - apk add --no-cache git
    - npm install @semantic-release/gitlab @semantic-release/changelog
      @semantic-release/git conventional-changelog-eslint
    - npx semantic-release
  artifacts:
    paths:
    - CHANGELOG.md
```
</details>

<details>
<summary>.releaserc.yml</summary>

```yaml
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: eslint
      releaseRules:
      - tag: Breaking
        release: major
      - tag: Build
        release: patch
      - tag: Chore
        release: minor
      - tag: Fix
        release: patch
      - tag: New
        release: minor
      - tag: Update
        release: minor
      - tag: Upgrade
        release: minor
  - - "@semantic-release/release-notes-generator"
    - preset: eslint
      releaseRules:
      - tag: Breaking
        release: major
      - tag: Build
        release: patch
      - tag: Chore
        release: minor
      - tag: Fix
        release: patch
      - tag: New
        release: minor
      - tag: Update
        release: minor
      - tag: Upgrade
        release: minor
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/gitlab"
  - - "@semantic-release/git"
    - assets: CHANGELOG.md
branches:
  - "master"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "alpha"
    prerelease: "alpha"
```
</details>

CICD Logs:
```
[5:00:42 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.2
[5:00:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[5:00:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[5:00:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[5:00:42 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[5:00:42 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[5:00:42 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[5:00:42 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[5:00:42 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[5:00:44 PM] [semantic-release] › ✔  Run automated release from branch master on repository https://gitlab-ci-token:[secure]@gitlab.[MASKED].com/erichardson/py-eagle-mqtt.git
[5:00:44 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[5:00:44 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[5:00:44 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[5:00:44 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[5:00:44 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.[MASKED].com/api/v4)
[5:00:44 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[5:00:44 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[5:00:44 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[5:00:44 PM] [semantic-release] › ℹ  Found git tag v1.7.5 associated with version 1.7.5 on branch master
[5:00:44 PM] [semantic-release] › ℹ  Found 2 commits since last release
[5:00:44 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:00:44 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Build: Change docker driver to overlay2
[5:00:44 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[5:00:44 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Don't semantic release on tags
[5:00:44 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[5:00:44 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[5:00:44 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:00:44 PM] [semantic-release] › ℹ  The next release version is 1.7.6
[5:00:44 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:00:45 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:00:45 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[5:00:45 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /builds/erichardson/py-eagle-mqtt/CHANGELOG.md
[5:00:45 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[5:00:45 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[5:00:45 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
[5:00:45 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v1.7.6
[5:00:45 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[5:00:45 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:00:45 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:00:47 PM] [semantic-release] › ✔  Created tag v1.7.6
[5:00:47 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
[5:00:47 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Published GitLab release: v1.7.6
[5:00:47 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/gitlab"
[5:00:47 PM] [semantic-release] › ✔  Published release 1.7.6 on default channel
```
