### ISSUE TITLE
How to use "github-actions" to send release notice?

### ISSUE THREAD

**Issue by shink** [semantic-release/semantic-release#1932]
As stated in the [issue](https://github.com/casbin/jcasbin/issues/190) in [casbin/jcasbin](https://github.com/casbin/jcasbin), we hope "github-actions" to send release notice as shown blow instead of [this](https://github.com/casbin/jcasbin/pull/189#issuecomment-839677834).

![2](https://user-images.githubusercontent.com/49934421/118078867-95fbef80-b3e9-11eb-8263-d0e9e29831d1.png)

The [workflow](https://github.com/casbin/jcasbin/blob/297e071589696f1a288385612af23e71ed9c3c11/.github/workflows/maven-ci.yml#L40) is shown blow:

```yml
- name: Sematic Release
        run: |
          npm install -g @conveyal/maven-semantic-release semantic-release
          semantic-release --prepare @conveyal/maven-semantic-release --publish @semantic-release/github,@conveyal/maven-semantic-release --verify-conditions @semantic-release/github,@conveyal/maven-semantic-release --verify-release @conveyal/maven-semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
          OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
```

Can someone help me? Thank you very much!
