### ISSUE TITLE
CHANGELOG.md not updated

### ISSUE THREAD

**Issue by pps1** [semantic-release/semantic-release#2019]
Hi there,

We've implemented semantic-release in a GitLab pipeline successfully and releases are working almost as expected. The only issue we are having is with changelogs. While changelogs are being written and pushed to the artifacts repository, they are not updated in the project repo, therefore resulting in single entry changelogs and loss of revision history inside of the project. I've included the config and pipeline below.

```
# .releaserc.yml
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# C.O.D.I. Changelog"
  - - "@semantic-release/gitlab"
    - assets: CHANGELOG.md
branches:
  - "master"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "alpha"
    prerelease: "alpha"
```

```
# .gitlab-ci.yml
release:
  image: node:13
  stage: release
  only:
    refs:
      - master
      - alpha
      - /^(([0-9]+)\.)?([0-9]+)\.x/ 
      - /^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
  script:
    - touch CHANGELOG.md
    - npm install @semantic-release/gitlab @semantic-release/changelog
    - npx semantic-release
  artifacts:
    paths:
      - CHANGELOG.md
```

```
# Runner Logs
Running with gitlab-runner 14.0.1 (c1edb478)
  on docker-auto-scale 72989761
  feature flags: FF_SKIP_DOCKER_MACHINE_PROVISION_ON_CREATION_FAILURE:true
Preparing the "docker+machine" executor
00:36
Using Docker executor with image node:13 ...
Pulling docker image node:13 ...
Using docker image sha256:2b9604a36e4911d15d2916dac4f1d853e2da612e9bb77df1016f8a51b3e333a1 for node:13 with digest node@sha256:70d4fffcab39a1f9f7161d58e674ddcc56c7f0724196b68d52a87bab15cb4a04 ...
Preparing environment
00:03
Running on runner-72989761-project-26833353-concurrent-0 via runner-72989761-srm-1625856434-c636747b...
Getting source from Git repository
00:03
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/************/.git/
Created fresh repository.
Checking out 289453d3 as master...
Skipping Git submodules setup
Executing "step_script" stage of the job script
00:40
Using docker image sha256:2b9604a36e4911d15d2916dac4f1d853e2da612e9bb77df1016f8a51b3e333a1 for node:13 with digest node@sha256:70d4fffcab39a1f9f7161d58e674ddcc56c7f0724196b68d52a87bab15cb4a04 ...
$ touch CHANGELOG.md
$ npm install @semantic-release/gitlab @semantic-release/changelog
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN @semantic-release/gitlab@6.2.1 requires a peer of semantic-release@>=15.8.0 <18.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/changelog@5.0.1 requires a peer of semantic-release@>=15.8.0 <18.0.0 but none is installed. You must install peer dependencies yourself.
+ @semantic-release/gitlab@6.2.1
+ @semantic-release/changelog@5.0.1
added 95 packages from 109 contributors and audited 95 packages in 7.083s
19 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
$ npx semantic-release
npx: installed 574 in 23.179s
[6:49:20 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.4
[6:49:20 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[6:49:20 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[6:49:20 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[6:49:20 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[6:49:20 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[6:49:20 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[6:49:23 PM] [semantic-release] › ✔  Run automated release from branch master on repository https://gitlab-ci-token:[secure]@gitlab.com/*********/*********.git
[6:49:24 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:49:24 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[6:49:24 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[6:49:24 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:49:24 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
[6:49:24 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:49:24 PM] [semantic-release] › ℹ  Found git tag v0.1.3 associated with version 0.1.3 on branch master
[6:49:24 PM] [semantic-release] › ℹ  Found 1 commits since last release
[6:49:24 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:49:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat(ui): Testing semantic release
more style updates
[6:49:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[6:49:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: minor release
[6:49:24 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:49:24 PM] [semantic-release] › ℹ  The next release version is 0.2.0
[6:49:24 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:49:24 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:49:24 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[6:49:24 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Create /builds/******/*******/CHANGELOG.md
[6:49:24 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[6:49:26 PM] [semantic-release] › ✔  Created tag v0.2.0
[6:49:26 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
Uploading artifacts for successful job
00:02
Uploading artifacts...
CHANGELOG.md: found 1 matching files and directories 
Uploading artifacts as "archive" to coordinator... ok  id=1413593087 responseStatus=201 Created token=zkypL92f
Cleaning up file based variables
00:01
Job succeeded
```

As you can see the changelog is generated and contains the most recent build, but is ultimately not committed back to the repo. Your help is greatly appreciated!
