### ISSUE TITLE
Cuts a release even if the publish failed?

### ISSUE THREAD

**Issue by maxwell-carbon** [semantic-release/semantic-release#2026]
I have a `.releaserc` that looks something like this (some parts removed):

```yaml
plugins:
  - "gradle-semantic-release-plugin"
  - - "@semantic-release/git"
    - assets:
      - gradle.properties
  - "@semantic-release/github"
```

However, what happens is if the publish in `gradle-semantic-release-plugin` fails (it happens sometimes, permissions), this plugin still runs and commits the version bump change. (a GitHub release is also spuriously cut)

Would it be possible to only commit and push the tags if gradle-semantic-release-plugin succeeds?
