### ISSUE TITLE
Document usage with GitHub Actions for non-Node projects

### ISSUE THREAD

**Issue by trallnag** [semantic-release/semantic-release#2105]
## New feature motivation

The documentation already describes quite well how to use GitHub Actions and Semantic Release with a Node project:

* <https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md>

But what is missing there (for me) is a description on how to do the same for non-Node projects.

## New feature description

Describe (with an example) how to best configure a GitHub Action workflow for Semantic Release using non-Node projects / generic projects with a focus on caching.

I'm mentioning caching because as someone who has no experience with NPM it is kind of difficult to properly setup caching. Just using `npm install <package>` to install Semantic Release and all the plugins I want means I have no caching at all.

What is the best practice here? Placing a `package.json` just with the CI reqs? This could mess up how IDEs detect the project type. Maybe putting the `package.json` somewhere else?

## New feature implementation

Add a new block of documentation to:

* <https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/github-actions.md>

**Comment by trallnag** [comment]
Node itself is already cached with the setup GitHub Action:

```yaml
- name: Setup Node.js
  uses: actions/setup-node@v1
  with:
    node-version: "16"
   cache: npm
```

The optional `cache: npm` enables NPM caching. But it expects `node_modules` and friends in the root dir.

**Comment by trallnag** [comment]
One thing I could do is not use caching provided by `setup-node` but use the `cache` action instead and cache the complete `node_modules` directory ignoring `package.json` and the lock file.

**Comment by trallnag** [comment]
I have settled with placing the package json in another directory:

```yaml
- name: Copy package meta info to root
  run: |
    cp .local/ci/package* .
- name: Setup Node.js
  uses: actions/setup-node@v2
  with:
    node-version: "16"
    cache: npm
- name: Install packages
  # TODO: Remove `2>&1 | tee` once issue closed.
  # https://github.com/npm/cli/issues/2560
  # https://github.com/npm/cli/issues/3314
  run: npm install --no-progress --prefer-offline 2>&1 | tee
- name: Semantic Release
  if: "!contains(github.event.head_commit.message, '[skip semantic release]')"
  id: semantic_release
  run: npx --no-install semantic-release
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

https://github.com/trallnag/ansible-role-asdf-plugin/blob/master/.github/workflows/cicd.yaml
