### ISSUE TITLE
When creating a new tag, tag annotation is inherited from last commit message causing [ci skip]

### ISSUE THREAD

**Issue by vojtechmares** [semantic-release/semantic-release#2270]
## Current behavior

When generating changelog and commiting with commit message:
```yaml
     # ...
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
```

the tag message is the same as commit message and because of `[ci skip]` skips the ci process on tag which I am using to release the package

## Expected behavior

A new tag would be created and CI would run

By looking into code, I thought the tag annotation would be `release ${version}`

## Environment

- **semantic-release** version: latest, isntalling each time during CI run with `npm i -g semantic-release ...`
- CI environment: GitLab
- Plugins used: gitlab, changelog, git
- **semantic-release** configuration:
```yaml
verifyConditions:
  - "@semantic-release/gitlab"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
prepare:
  - "@semantic-release/changelog"
  - "@semantic-release/git"
generateNotes:
  - "@semantic-release/release-notes-generator"
publish:
  - "@semantic-release/gitlab"
success: false
fail: false
npmPublish: false
tagFormat: ${version}
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      parserOpts:
        - "BREAKING CHANGE"
        - "BREAKING CHANGES"
        - "BREAKING"
  - - "@semantic-release/release-notes-generator"
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
      message: |-
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
```
- CI logs:
![image](https://user-images.githubusercontent.com/7180610/143661614-9ed6aca2-3824-4235-8e66-f45c94287b47.png)

NOTE: unfortunately I wasn't able to "google" myself out of this
