### ISSUE TITLE
Tagger and Creation Date not available AzDO

### ISSUE THREAD

**Issue by jppmateus** [semantic-release/semantic-release#2298]
## Current behavior

Using Azure DevOps Pipelines and Semantic Release, the information related with Tagger and Creation Date of the created tag are not available.

```
  - stage: release
    # condition: and(succeeded())
    jobs:
      - job: SemanticRelease
        steps:
          - task: Cache@2
            inputs:
              key: 'npm | "$(Agent.OS)" | package-lock.json'
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(npm_config_cache)
            displayName: 'Cache NPM packages'

          - task: NodeTool@0
            inputs:
              versionSpec: '16.13'
            displayName: 'Install Node.js'

          - script: npm ci --prefer-offline
            displayName: 'Install NPM dependencies'

          - script: npx semantic-release
            env: 
              GIT_CREDENTIALS: $(System.AccessToken)
            displayName: 'Semantic Release'
```

The result is this one:

![image](https://user-images.githubusercontent.com/6825702/146070457-2e45b2b4-d9c8-449a-9cec-f1ea02d8d84b.png)

## Environment

- **semantic-release** version: 18.0.1
- Plugins used:     '@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', 'semantic-release-ado',
- **semantic-release** configuration: 
```
module.exports = {
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    'semantic-release-ado',
    { varName: 'nextRelease', setOnlyOnRelease: false },
  ],
  branches: ['main', { name: 'develop', prerelease: true }, { name: 'test', prerelease: true }],
}
```
- CI logs:
```
[3:06:21 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[3:06:21 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "semantic-release-ado"
[3:06:21 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "semantic-release-ado"
[3:06:21 AM] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0-test.1
[3:06:21 AM] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "semantic-release-ado"
[3:06:21 AM] [semantic-release] [semantic-release-ado] › ℹ  Setting version 1.0.0-test.1 to the env var nextRelease
[3:06:21 AM] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "semantic-release-ado"
[3:06:21 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[3:06:21 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[3:06:22 AM] [semantic-release] › ✔  Created tag v1.0.0-test.1
[3:06:22 AM] [semantic-release] › ✔  Published release 1.0.0-test.1 on test channel
Finishing: Semantic Release
```
