### ISSUE TITLE
Error while publishing to npm "EINVALIDNPMTOKEN Invalid npm token."

### ISSUE THREAD

**Issue by senshiii** [semantic-release/semantic-release#2313]
I am trying to publish a package using semantic release and this is the error I am receiving.

Versions :- 
1. semantic-release : 18.0.1
2. node : 16.13.1
3. npm : 8.3.0

I have first run the `npx semantic-release-cli setup` with a valid GitHub token. This GitHub Token is stored as `MY_GITHUB_TOKEN` in my repo secrets. This command created a "publish" token and created a `NPM_TOKEN` secret in my [GitHub Repo](https://github.com/senshiii/immitate). 

I am using GitHub Actions. This is my ci yml file.

```yml
  name: CI
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]
        os: [windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            node: 16.x
            upload: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies ( clean )
        run: npm ci --ignore-scripts

      - name: Build
        run: npm run build --if-present

      - name: Upload Artifacts
        if: matrix.upload
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Install
        run: npm ci

      - name: Semantic Release
        run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
```   

Logs of semantic release step

```bash
[4:11:02 AM] [semantic-release] › ℹ  Running semantic-release version 18.0.1
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[4:11:03 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[4:11:04 AM] [semantic-release] › ✔  Run automated release from branch master on repository https://github.com/senshiii/immitate.git
[4:11:04 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[4:11:04 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[4:11:04 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[4:11:04 AM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /home/runner/work/_temp/.npmrc
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://registry.npmjs.org/-/whoami

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-12-31T04_11_04_766Z-debug.log
[4:11:04 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[4:11:04 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[4:11:04 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[4:11:04 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[4:11:04 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[4:11:04 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[4:11:04 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[4:11:04 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[4:11:04 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[4:11:05 AM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #1.
[4:11:07 AM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #1: https://github.com/senshiii/immitate/issues/1#issuecomment-1003261879.
[4:11:07 AM] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
[4:11:07 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.

If you are using Two Factor Authentication for your account, set its level to "Authorization only" (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) in your account settings. semantic-release cannot publish with the default "
Authorization and writes" level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.

AggregateError: 
    SemanticReleaseError: Invalid npm token.
        at module.exports (/home/runner/work/immitate/immitate/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/home/runner/work/immitate/immitate/node_modules/@semantic-release/npm/lib/verify-auth.js:26:33)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async verifyConditions (/home/runner/work/immitate/immitate/node_modules/@semantic-release/npm/index.js:36:7)
        at async validator (/home/runner/work/immitate/immitate/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
        at async /home/runner/work/immitate/immitate/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async Promise.all (index 0)
        at async next (/home/runner/work/immitate/immitate/node_modules/semantic-release/node_modules/p-reduce/index.js:16:18)
    at /home/runner/work/immitate/immitate/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/runner/work/immitate/immitate/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/work/immitate/immitate/node_modules/semantic-release/index.js:95:3)
    at async module.exports (/home/runner/work/immitate/immitate/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/runner/work/immitate/immitate/node_modules/semantic-release/cli.js:55:5)
Error: Process completed with exit code 1.
````

This is the .releaserc.json file
```json
  {
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    "@semantic-release/github",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "docs/CHANGELOG.md"
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": ["docs/CHANGELOG.md"]
      }
    ]
  ]
}
```

I have 2FA enabled in my npm account but it is set to "Authorization only". Please assist me to solve this.
