### ISSUE TITLE
GitLab fails when Push Rules for commit messages is enabled

### ISSUE THREAD

**Issue by dgroh** [semantic-release/semantic-release#2379]
## Current behavior

On our GitLab pipeline, when enabling Push Rules for commit messages the pipeline fails when running `npx semantic-release`.
That is our commit message rules configured on GitLab: `^(?i)((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_/¯)(\(\w+\))?(!)?(: (.*\s*)*))|(Merge (.*\s*)*)|(Initial commit$)`

Out `.releaserc` looks like that:

```
tagFormat: "${version}"
plugins:
  - "@semantic-release/commit-analyzer"
    
  - #
    - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - SharedAssemblyInfo.cs
          from: '\[assembly: AssemblyVersion\(".+"\)\]'
          to: '[assembly: AssemblyVersion("${nextRelease.version}")]'
          results:
            - file: SharedAssemblyInfo.cs
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - SharedAssemblyInfo.cs
          from: '\[assembly: AssemblyFileVersion\(".+"\)\]'
          to: '[assembly: AssemblyFileVersion("${nextRelease.version}")]'
          results:
            - file: SharedAssemblyInfo.cs
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
        - files:
            - SharedAssemblyInfo.cs
          from: '\[assembly: AssemblyInformationalVersion\(".+"\)\]'
          to: '[assembly: AssemblyInformationalVersion("${nextRelease.version}")]'
          results:
            - file: SharedAssemblyInfo.cs
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
          
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/gitlab"

  - #
    - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - SharedAssemblyInfo.cs
      message: "chore(release): ${nextRelease.version} [skip ci]"
branches:
  - "feature/BSL-12225"
```

> Please be aware that `feature/BSL-12225` is only a branch configured for test purposes.

Also note the message pattern `message: "chore(release): ${nextRelease.version} [skip ci]"` matches the commit message rule configured on GitLab.

**Now the error GitLab throws is the following:**

> GitLab: Commit message does not follow the pattern '^(?i)((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_/¯)(\(\w+\))?(!)?(: (.*\s*)*))|(Merge (.*\s*)*)|(Initial commit$)'

**The detailed log with the error:**

```
Error: Command failed with exit code 1: git push https://gitlab-ci-token:[secure]@gitlab.com/companyname/senex/shared/npm.common.git refs/notes/semantic-release
remote: GitLab: Commit message does not follow the pattern '^(?i)((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\_\(ツ\)_/¯)(\(\w+\))?(!)?(: (.*\s*)*))|(Merge (.*\s*)*)|(Initial commit$)'
To https://gitlab.com/companyname/senex/shared/npm.common.git
 ! [remote rejected] refs/notes/semantic-release -> refs/notes/semantic-release (pre-receive hook declined)
error: failed to push some refs to 'https://gitlab-ci-token:[secure]@gitlab.com/companyname/senex/shared/npm.common.git'
    at makeError (/builds/companyname/senex/shared/npm.common/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/builds/companyname/senex/shared/npm.common/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async pushNotes (/builds/companyname/senex/shared/npm.common/node_modules/semantic-release/lib/git.js:248:3)
    at async run (/builds/companyname/senex/shared/npm.common/node_modules/semantic-release/index.js:202:5)
    at async module.exports (/builds/companyname/senex/shared/npm.common/node_modules/semantic-release/index.js:268:22)
    at async module.exports (/builds/companyname/senex/shared/npm.common/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 1: git push https://gitlab-ci-token:[secure]@gitlab.com/companyname/senex/shared/npm.common.git refs/notes/semantic-release',
  command: 'git push https://gitlab-ci-token:[secure]@gitlab.com/companyname/senex/shared/npm.common.git refs/notes/semantic-release',
  escapedCommand: 'git push "https://gitlab-ci-token:[secure]@gitlab.com/companyname/senex/shared/npm.common.git" "refs/notes/semantic-release"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "remote: GitLab: Commit message does not follow the pattern '^(?i)((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|¯\\\\_\\(ツ\\)_/¯)(\\(\\w+\\))?(!)?(: (.*\\s*)*))|(Merge (.*\\s*)*)|(Initial commit$)'\n" +
    'To https://gitlab.com/companyname/senex/shared/npm.common.git\n' +
    ' ! [remote rejected] refs/notes/semantic-release -> refs/notes/semantic-release (pre-receive hook declined)\n' +
    "error: failed to push some refs to 'https://gitlab-ci-token:[secure]@gitlab.com/companyname/senex/shared/npm.common.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Even though the pipeline fails, the commit is pushed to the repository:

![image](https://user-images.githubusercontent.com/16785357/155683342-1ca3e317-985f-4c58-b062-03f5bcb5d1dd.png)

## Expected behavior

I expect the debug logs to show the exact commit message sent to GitLab to exclude an error on semantic-release side. This might be something rather related to GitLab than to semantic-release itself, but unfortunatelly the log does not show the exact message sent to GitLab. Maybe the message is not well parsed on side of `@semantic-release/git`?

## Environment

- **semantic-release** version: 
- CI environment: **GitLab**
- Plugins used: 
  - @semantic-release/commit-analyzer
  - @google/semantic-release-replace-plugin
  - @semantic-release/release-notes-generator
  - @semantic-release/changelog
  - @semantic-release/gitlab
  - @semantic-release/git
- **semantic-release** configuration: 
- CI logs:
