### ISSUE TITLE
Semantic-release crashes when an environment variable contains a very long json string

### ISSUE THREAD

**Issue by mcanevet** [semantic-release/semantic-release#2401]
## Current behavior

I'm using this `.gitlab-ci.yml` adapted from [this documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/gitlab-ci.md#gitlab-ciyml-configuration-for-all-projects)

```yaml
release:
  image: public.ecr.aws/docker/library/node:17-bullseye-slim
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/changelog @semantic-release/git conventional-changelog-conventionalcommits
  script:
    - semantic-release
  rules:
    - if: '$CI_COMMIT_REF_PROTECTED == "true"'
      when: manual
```
with this `.releaserc.yaml` file:
```yaml
{
  "plugins":
    [
      [
        "@semantic-release/commit-analyzer",
        { "preset": "conventionalcommits" },
      ],
      [
        "@semantic-release/release-notes-generator",
        { "preset": "conventionalcommits" },
      ],
      "@semantic-release/changelog",
      "@semantic-release/git",
    ],
}
```
Somehow it stopped working since yesterday without any output.
- Gitlab runner version is the same
- Docker image hash is the same
- semantic-release version is the same

It works fine if I run it from my laptop...

## Expected behavior

semantic-release should at least output some error message

## Environment

- **semantic-release** version: 19.0.2
- CI environment: Gitlab CI
- Plugins used: commit-analyzer, release-notes-generator, changelog and git
- **semantic-release** configuration: 
- CI logs: [here](https://gist.github.com/mcanevet/62371efb645274289c2e975b13bd90b2)
