### ISSUE TITLE
Semantic Version ignores package .npmrc file and attempts to load a non-existent one from temp

### ISSUE THREAD

**Issue by michaelm-rsi** [semantic-release/semantic-release#2441]
## Current behavior

After 2 days I'm at my wits end - I can't even a basic proof of concept of this versioning system running in gitlab.  I've made some progress, but have hit a wall with this error:

```
[9:11:07 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[9:11:07 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 1.0.0-alpha.1 to package.json in /builds/[secure]/0/npm/ucx/semanticversiontest
[9:11:07 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
[9:11:07 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 243: npm version 1.0.0-alpha.1 --userconfig /tmp/e31af65ecd4028fa1645312333[169](https://git.fleetcor.com/npm/ucx/semanticversiontest/-/jobs/125539#L169)9fd/.npmrc --no-git-tag-version --allow-same-version
    at makeError (/builds/[secure]/0/npm/ucx/semanticversiontest/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/builds/[secure]/0/npm/ucx/semanticversiontest/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async module.exports (/builds/[secure]/0/npm/ucx/semanticversiontest/node_modules/@semantic-release/npm/lib/prepare.js:22:3)
    at async prepare (/builds/[secure]/0/npm/ucx/semanticversiontest/node_modules/@semantic-release/npm/index.js:68:3)
    at async validator (/builds/[secure]/0/npm/ucx/semanticversiontest/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /builds/[secure]/0/npm/ucx/semanticversiontest/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/builds/[secure]/0/npm/ucx/semanticversiontest/node_modules/p-reduce/index.js:16:18) {
```

I can usually Google out of this sort of thing, but the documentation for this plugin is hopelessly confusing both on Google and Bing.  Also, the frequent version updating leads me to believe half the tutorials I've followed are woefully out of date.

I'm in a proof of concept repo made specifically to learn this versioning system and decide whether it is suitable to our needs.  The package.json file:

```
{
  "name": "@ucx/semanticversiontest",
  "version": "0.0.0-dev",
  "description": "Semantic Version Test",
  "type": "module",
  "scripts": {
    "test": "echo \"Test Placeholder ran\" && exit 0",
    "semantic-release": "semantic-release",
    "build": "webpack --mode=production"
  },
  "publishConfig": {
    "@ucx:registry": "https://git.fleetcor.com/api/v4/projects/1201/packages/npm/"
  },
  "files": [
    "dist/*"
  ],
  "repository": {
    "type": "git",
    "url": "https://git.fleetcor.com/npm/ucx/semanticversiontest.git"
  },
  "keywords": [
    "Test"
  ],
  "devDependencies": {
    "@semantic-release/git": "^10.0.1",
    "@semantic-release/gitlab": "^9.3.0",
    "@semantic-release/npm": "^9.0.1",
    "semantic-release": "^19.0.2",
    "webpack": "^5.72.1",
    "webpack-cli": "^4.9.2"
  }
}
```

The .releaserc.json file as best I can determine - again, countless contrary tutorials out there on search, and I have no clue which ones are right and which ones are out of date at this point.

```
{
  "branches": [
    {"name": "main"},
    {"name": "release", "channel": "rc", "prerelease": "rc"},
    {"name": "dev", "channel": "beta", "prerelease": "beta" },
    {"name": "feature/*", "channel": "alpha", "prerelease": "alpha"}
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/gitlab", 
    ["@semantic-release/npm", {
      "pkgRoot": "."
    }],
    [
      "@semantic-release/git",
      {
        "assets": ["package.json"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}
```

And finally, the gitlab.yml file. BTW, every tutorial I've seen wants the user to use a personal access token, but none of them talk about the use of project or group access tokens. I think I've cleared this hurdle and face an npm issue.

```
default:
  image: node:latest
  tags:
    - us-ea1-d-000  
  before_script:
    # - npm ci --cache .npm --prefer-offline
    - echo "@ucx:registry = ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > ./.npmrc
    - echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${NPM_TOKEN}" >> ./.npmrc
    - npm ci
    - npm get
  after_script:
    - cd /tmp/
    - ls -alt
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  GIT_STRATEGY: fetch
  GITLAB_TOKEN: $GITLAB_TOKEN
  NPM_TOKEN: $NPM_TOKEN
  NPM_USERNAME: $NPM_USERNAME
  NPM_CONFIG_USERCONFIG: $CL_PROJECT_DIR

stages:
  - release

publish:
  stage: release
  script:
    - npm run semantic-release
  # rules:
    # - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
```

I'm completely stuck. Our devops guy that knows gitlab like that back of his hand is completely stuck.  Posting here is a desperate hail mary - if it doesn't work we'll have to come up with a solution using just gitlab pipelines that doesn't involve semantic-release at all.

## Expected behavior

That it would work.

## Environment

- **semantic-release** version: 19.0.2
- CI environment: Gitlab 14.4.1-ee
- Plugins used: "@semantic-release/git": "^10.0.1", "@semantic-release/gitlab": "^9.3.0", "@semantic-release/npm": "^9.0.1",
- **semantic-release** configuration: See above
- CI logs: Can be provided on request - logs are not public.

**Comment by profhouse** [comment]
Same issue :(. Anyone can help?

**Comment by michaelm-rsi** [comment]
It's not Semantic Release. It's git lab's piss poor documentation.  After another week of struggle lead to this ci.yml

```
variables:
  GIT_COMMITTER_NAME: $GITLAB_USER_NAME
  GIT_COMMITTER_EMAIL: $GITLAB_USER_EMAIL

default:
  image: git.fleetcor.com:4567/containers/nodejs/nodejs:16
  tags:
    - us-ea1-d-000    

  before_script:
    - yum install git -y
    - npm ci
    - |
      {
        echo "@ucx:registry = ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}"
      } | tee -a .npmrc
    - git config --global user.name "${GITLAB_COMMITTER_NAME}"
    - git config --global user.email "${GITLAB_COMMITTER_EMAIL}"
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - release

publish:
  stage: release
  script:
    - git checkout $CI_COMMIT_REF_NAME
    - chmod -R 777 ./.git
    - chmod -R 777 /root/.npm
    - npm run semantic-release
```

Note we are using an internal nodejs image, so you'll need to change to a different one, and it will need to have git installed - most of the gitlab images do not, hence the yum call above to quickly install it in the before script.

Also I had to disable the verified email security check on push rules to get this to work.  I'm still working on a way to re-enable that push.

If you still have trouble with this after using the above ci script DM me and I'll see what I can do, but I'm going to close this ticket as at this point the behavior observed is normal and unrelated to the problem of getting this working on gitlab.
