### ISSUE TITLE
Drone CI publish from tag not working because branch is undefined

### ISSUE THREAD

**Issue by MauriceNino** [semantic-release/semantic-release#2445]
## Current behavior

No matter what I set for `branches`, when I release from a tag, I always get the following error:

```
This test run was triggered on the branch undefined, while semantic-release is configured to only publish from dev, main, therefore a new version won’t be published.
```

My pipeline step looks like this:

```yml
  - name: create release notes
    image: timbru31/node-alpine-git:latest
    when:
      event: tag
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - yarn --immutable --immutable-cache
      - yarn semantic-release
```

My config:

```json
{
  "branches": ["*"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github"
  ]
}
```

## Expected behavior

I would expect a release from a tag to run as well, if I specified the branch as `*`.

## Environment

- **semantic-release** version: 19.0.2
- CI environment: Drone
- Plugins used: `["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", "@semantic-release/github"]`
- **semantic-release** configuration: [commit](https://github.com/MauriceNino/dashdot/commit/3fef1fb3f5929d9e3ab2db926418a438c1afb94a)
- CI logs: [logs](https://drone.mauz.io/MauriceNino/dashdot/217/1/2)
