### ISSUE TITLE
EGITNOPERMISSION with a gitlab token and full permission activated

### ISSUE THREAD

**Issue by deshiloh** [semantic-release/semantic-release#2495]
### Current behavior

Hi ! 

I want to add semantic release in my project, 

I used this : 

```yml
release:
  image: node:16-buster-slim
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - semantic-release --dry-run --branches 23-semantic-release 
  only:
    - 23-semantic-release
```
but I got : 

```shell
code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `23-semantic-release` on the remote Git repository with URL `[https://gitlab-ci-token:[secure]@gitlab.com/deshiloh/motobleu-laravel.git](https://gitlab-ci-token:%5Bsecure%5D@gitlab.com/deshiloh/motobleu-laravel.git)`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
```

I created a GITLAB_TOKEN with full permission. 

What is wrong ? 

### Expected behavior

I want that the dry run can work 

### `semantic-release` version

latest

### CI environment

Gitlab

### Plugins used

@semantic-release/gitlab

### `semantic-release` configuration

```yml
release:
  image: node:16-buster-slim
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - semantic-release --dry-run --branches 23-semantic-release 
  only:
    - 23-semantic-release
```

### CI logs

```shell
code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `23-semantic-release` on the remote Git repository with URL `[https://gitlab-ci-token:[secure]@gitlab.com/deshiloh/motobleu-laravel.git](https://gitlab-ci-token:%5Bsecure%5D@gitlab.com/deshiloh/motobleu-laravel.git)`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
```

**Comment by AndresGX** [comment]
I have this same problem, I try add another ENV but still not working
![image](https://user-images.githubusercontent.com/87664730/188703988-3100a773-a15d-4b5f-add4-293002243902.png)

**Comment by perry-mitchell** [comment]
I'm having the same issue [here](https://github.com/perry-mitchell/semantic-release-slack-bot-demo/actions/runs/4509133469/jobs/7938538467):

```
[8:16:17 AM] [semantic-release] › ✔  Run automated release from branch staging on repository https://github.com/perry-mitchell/semantic-release-slack-bot-demo.git
[8:16:18 AM] [semantic-release] › ✖  The command "git push --dry-run --no-verify https://github.com/perry-mitchell/semantic-release-slack-bot-demo.git HEAD:staging" failed with the error message remote: Permission to perry-mitchell/semantic-release-slack-bot-demo.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/perry-mitchell/semantic-release-slack-bot-demo.git/': The requested URL returned error: 403.

...

[8:16:18 AM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch staging on the remote Git repository with URL https://github.com/perry-mitchell/semantic-release-slack-bot-demo.git.
```

My build file for Github:

```yaml
name: Release

on:
  push:
    branches:
      - main
      - staging

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - name: NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm ci
      - name: deploy
        run: npm run release
```

The slack webhook env var, by comparison, does work.
