### ISSUE TITLE
Error on publish to github package

### ISSUE THREAD

**Issue by gabriel-brotas** [semantic-release/semantic-release#2496]
### Current behavior

```
[8:57:12 PM] [semantic-release] › ✖  The command "git push --dry-run --no-verify https://github.com/** HEAD:master" failed with the error message remote: Permission to *** denied to github-actions[bot].
fatal: unable to access 'https://github.com/**/': The requested URL returned error: 403.
[8:57:12 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[8:57:12 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[8:57:13 PM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #3.
[8:57:15 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #3: https://github.com/**#issuecomment-1174343308.
[8:57:15 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[8:57:15 PM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL https://github.com/**.
This can be caused by:
    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)
SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/runner/work/is-odd/is-odd/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/runner/work/is-odd/is-odd/node_modules/semantic-release/index.js:98:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/runner/work/is-odd/is-odd/node_modules/semantic-release/index.js:[26](https://github.com/gabriel-brotas/is-odd/runs/7186762136?check_suite_focus=true#step:5:27)9:22)
    at async module.exports (/home/runner/work/is-odd/is-odd/node_modules/semantic-release/cli.js:55:5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `https://github.com/**`.\n' +
'\n' +
'This can be caused by:\n' +
' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
' - the repository being unavailable\n' +
' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
```

### Expected behavior

Publish to github package

### `semantic-release` version

19.0.3

### CI environment

github actions

### `semantic-release` configuration

package.json
```
{
  "name": "@.../....",
  "version": "0.0.3",
  "description": "verify is number is even or odd",
  "main": "index.js",
  "scripts": {
    "semantic-release": "semantic-release"
  },
  "keywords": [
    "javascript"
  ],
  "author": "gabriel-brotas",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/gabriel-brotas/is-odd/issues"
  },
  "homepage": "https://github.com/gabriel-brotas/is-odd#readme",
  "devDependencies": {
    "@semantic-release/commit-analyzer": "^9.0.2",
    "@semantic-release/github": "^8.0.4",
    "@semantic-release/release-notes-generator": "^10.0.3",
    "semantic-release": "^19.0.3"
  },
  "publishConfig": {
    "@gabriel-brotas:registry": "https://npm.pkg.github.com"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gabriel-brotas/is-odd.git"
  },
  "release": {
    "branches": [
      "master"
    ],
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/github",
        "@semantic-release/npm"
    ]
  }
}
```

.release.json
```
{
  "release": {
    "branches": ["master"]
  },
  "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/github",
      "@semantic-release/npm"
    ]
}
```

pipeline:
```
name: Node.js Package

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13.0
          registry-url: https://npm.pkg.github.com
          scope: "@gabriel-brotas"

      - name: Install dependencies
        run: npm install
        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_TOKEN }}
          GH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NPM_TOKEN: ${{ secrets.AUTH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          npx semantic-release
```

### CI logs

```
[8:57:12 PM] [semantic-release] › ✖  The command "git push --dry-run --no-verify https://github.com/** HEAD:master" failed with the error message remote: Permission to *** denied to github-actions[bot].
fatal: unable to access 'https://github.com/**/': The requested URL returned error: 403.
[8:57:12 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[8:57:12 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[8:57:13 PM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #3.
[8:57:15 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #3: https://github.com/**#issuecomment-1174343308.
[8:57:15 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[8:57:15 PM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL https://github.com/**.
This can be caused by:
    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)
SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/runner/work/is-odd/is-odd/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/runner/work/is-odd/is-odd/node_modules/semantic-release/index.js:98:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/runner/work/is-odd/is-odd/node_modules/semantic-release/index.js:[26](https://github.com/gabriel-brotas/is-odd/runs/7186762136?check_suite_focus=true#step:5:27)9:22)
    at async module.exports (/home/runner/work/is-odd/is-odd/node_modules/semantic-release/cli.js:55:5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `https://github.com/**`.\n' +
'\n' +
'This can be caused by:\n' +
' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
' - the repository being unavailable\n' +
' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
```
