### ISSUE TITLE
semantic-release does not create new Release

### ISSUE THREAD

**Issue by garatortiz** [semantic-release/semantic-release#2548]
I have the following problem:
- I have the github action that I share below, which runs correctly, and in fact creates the new tag with the version correctly. But what I can't do is generate the new Release or update the version in the package.json.

I also share the .releaserc file as well.

```
name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
          git_config_global: true
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
        run: npx semantic-release
```

`.releaserc`
```
{
  "branches": ["main", "next"],
  "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      ["@semantic-release/git",{
          "assets": ["CHANGELOG.md", "package.json", "package-lock.json","README.md"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }]
    ]
}
```
![image](https://user-images.githubusercontent.com/303122/187685836-0bc8eac4-cd8b-4b0b-bd58-6384eb469241.png)
![image](https://user-images.githubusercontent.com/303122/187685943-3cf3ac71-9b6f-45a2-8456-5a97f6363a54.png)
