### ISSUE TITLE
Existing tags not being auto released to github by semantic-release

### ISSUE THREAD

**Issue by gouravkhator** [semantic-release/semantic-release#2552]
### Current behavior

The **existing tags on the github repo** formatted as `v0.0.0`, which is the format followed by semantic-release, is not getting auto-released to github releases.

Github sample repo with proper config files: https://github.com/gouravkhator/temp-git/tree/7ff47c8deb5c5093ded1fde16b555b0b06d1aab0

### Expected behavior

As said in [this official docs](https://semantic-release.gitbook.io/semantic-release/usage/configuration#existing-version-tags), the semantic-release should work on existing tags on a particular repo.

### `semantic-release` version

^19.0.5

### CI environment

Github Actions

### Plugins used

```json
"plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/exec",
      {
        "prepareCmd": "npm run build"
      }
    ],
    "@semantic-release/npm",
    "@semantic-release/github"
  ]
```

### `semantic-release` configuration

My sample GitHub repo with proper config files: https://github.com/gouravkhator/temp-git/tree/7ff47c8deb5c5093ded1fde16b555b0b06d1aab0

## `package.json`:

```json
{
  "name": "temp-git",
  "version": "0.0.0-development",
  "description": "Temporary repo for npm and git automated releases demo",
  "main": "./dist/js/main.js",
  "module": "./dist/js/main.js",
  "type": "module",
  "files": [
    "dist/js/**"
  ],
  "bin": {
    "temp-git-cli": "./dist/js/main.js"
  },
  "scripts": {
    "test": "echo \"No test specified\"",
    "build": "mkdir -p dist/js && cp src/main.js dist/js/",
    "bin": "pkg . --compress GZip --output dist/bin/$npm_package_name-v${nextRelease.version}",
    "generate-binary": "npm run build && npm run bin",
    "commit": "cz",
    "semantic-release": "semantic-release"
  },
  "devDependencies": {
    "commitizen": "^4.2.5",
    "cz-conventional-changelog": "^3.3.0",
    "pkg": "^5.8.0",
    "semantic-release": "^19.0.5",
    "@semantic-release/exec": "^6.0.3"
  },
  "pkg": {
    "targets": [
      "node16-linux-x64",
      "node16-macos-x64",
      "node16-win-x64"
    ]
  },
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/exec",
      {
        "prepareCmd": "npm run build"
      }
    ],
    "@semantic-release/npm",
    "@semantic-release/github"
  ],
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "engines": {
    "node": ">=12"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gouravkhator/temp-git.git"
  },
  "keywords": [],
  "author": "Gourav Khator",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/gouravkhator/temp-git/issues"
  },
  "homepage": "https://github.com/gouravkhator/temp-git#readme"
}
```

## `.releaserc`:

```
{
  "branches": [
    "main"
  ]
}
```

## `publish.yml` Github workflow:

```yaml
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: "*"

jobs:
  quality-checks:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [12.x, 14.x, 16.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test

  publish:
    needs: [quality-checks]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

### CI logs

GitHub workflow works fine, and is successful, and no specific logs found.
