### ISSUE TITLE
unable to push git tag on protected branch with required status checks

### ISSUE THREAD

**Issue by Clumsy-Coder** [semantic-release/semantic-release#2556]
I'm unable to have semantic-release push a new tag and commit on a protected branch with require status checks.

# things done so far
- use custom Personal access token with `public_repo` permission
- use custom Personal access token with full `repo` permissions 
- Add permission to a github-action job

---
# configs

## .releaserc.js

```javascript
module.exports = {
  branches: ['master', { name: 'development', prerelease: true }],
  tagFormat: '${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/github',
    ['@semantic-release/npm', { npmPublish: false }],
    [
      '@semantic-release/git',
      {
        assets: ['CHANGELOG.md', 'package.json', 'package-lock.json'],
      },
    ],
    'semantic-release-export-data',
  ],
  // use https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-conventionalcommits
  // release rules: https://github.com/semantic-release/commit-analyzer/blob/master/lib/default-release-rules.js
  preset: 'conventionalcommits',

  // git emoji obtained from
  //    https://gist.github.com/parmentf/035de27d6ed1dce0b36a
  //    https://github.com/caiyongji/emoji-list
  //    https://github.com/pvdlg/conventional-changelog-metahub#commit-types
  // preset config for generating release notes and changelogs
  //    https://github.com/conventional-changelog/conventional-changelog-config-spec/blob/master/versions/2.0.0/README.md#type
  // prettier-ignore
  presetConfig: {
    types: [
      { type: "feat",     section: ":sparkles: Features",                             hidden: false }, // MINOR
      { type: "fix",      section: ":bug: Bug Fixes",                                 hidden: false }, // PATCH
      { type: "perf",     section: ":zap: Performance Improvements",                  hidden: false }, // PATCH
      { type: "revert",   section: ":rewind: Reverts",                                hidden: true  }, // NO_RELEASE
      { type: "docs",     section: ":books: Documentation",                           hidden: true  }, // NO_RELEASE
      { type: "style",    section: ":lipstick: Styles",                               hidden: true  }, // NO_RELEASE
      { type: "chore",    section: ":octopus: Miscellaneous Chores",                  hidden: true  }, // NO_RELEASE
      { type: "refactor", section: ":recycle: Code Refactoring",                      hidden: true  }, // NO_RELEASE
      { type: "test",     section: ":white_check_mark: Tests",                        hidden: true  }, // NO_RELEASE
      { type: "build",    section: ":package: Build System",                          hidden: true  }, // NO_RELEASE
      { type: "ci",       section: ":construction_worker: Continuous Integration",    hidden: true  }, // NO_RELEASE
    ],
  },
};

```

## .github/workflows/build.yaml

```yaml
  install:      # install npm packages and store node_modules to cache
  lint:         # lint code
  docker-build: # build docker image, if on master or development branch, push to github
  
  semantic-release:
    needs: docker-build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development'
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: |
            **/node_modules
            ${{ needs.install.outputs.npm-cache-dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm install --production=false

      - name: semantic-release
        run: npx semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.DEPENDABOT_TOKEN }}

```

## protected branch settings

![image](https://user-images.githubusercontent.com/19594044/189553288-82b6d0f6-d595-4233-a1d7-07e0928b27a5.png)

# error returned

![image](https://user-images.githubusercontent.com/19594044/189553631-ab4528f4-1b7f-4db5-ac1e-100fa2c03786.png)
