### ISSUE TITLE
Protected branch update failed for refs/heads/main. How to handle it?

### ISSUE THREAD

**Issue by shaobeichen** [semantic-release/semantic-release#2604]
### Current behavior

<img width="869" alt="image" src="https://user-images.githubusercontent.com/18715564/200875247-5bc44916-9507-4991-a8c2-3c4afa51a056.png">

One of my organizational repositories is using semantic-release, this is the first use, my main branch has protection rules turned on, and then this happens, how do I deal with it? Can you pull request instead of push?

The Github token has all the permissions except the deletion permission.

### Expected behavior

I hope I can pass ci normally

### `semantic-release` version

19.0.5

### CI environment

github actions

### `semantic-release` configuration

{
    "branches": [
        {
            "name": "main"
        }
    ],
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/npm",
        [
            "@semantic-release/git",
            {
                "assets": [
                    "package.json",
                    "CHANGELOG.md"
                ],
                "message": "release: v${nextRelease.version} [skip ci] \n\n${nextRelease.notes}"
            }
        ],
        "@semantic-release/github"
    ]
}

### CI logs

```
[3:30:55 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 2 file(s) to commit
[3:30:56 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
[3:30:56 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://github.com/make3waves/makaka HEAD:main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request.        
To https://github.com/make3waves/makaka
 ! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/make3waves/makaka'
    at makeError (/home/runner/work/makaka/makaka/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/makaka/makaka/node_modules/execa/index.js:[118](https://github.com/make3waves/makaka/actions/runs/3426537159/jobs/5715209876#step:6:119):26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async push (/home/runner/work/makaka/makaka/node_modules/@semantic-release/git/lib/git.js:51:3)
    at async module.exports (/home/runner/work/makaka/makaka/node_modules/@semantic-release/git/lib/prepare.js:69:5)
    at async prepare (/home/runner/work/makaka/makaka/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/runner/work/makaka/makaka/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/makaka/makaka/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/makaka/makaka/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async pluginsConf.<computed> [as prepare] (/home/runner/work/makaka/makaka/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  shortMessage: 'Command failed with exit code 1: git push --tags https://github.com/make3waves/makaka HEAD:main',
  command: 'git push --tags https://github.com/make3waves/makaka HEAD:main',
  escapedCommand: 'git push --tags "https://github.com/make3waves/makaka" "HEAD:main"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/main.        \n' +
    'remote: error: Changes must be made through a pull request.        \n' +
    'To https://github.com/make3waves/makaka\n' +
    ' ! [remote rejected] HEAD -> main (protected branch hook declined)\n' +
    "error: failed to push some refs to 'https://github.com/make3waves/makaka'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
Error: Command failed with exit code 1: git push --tags https://github.com/make3waves/makaka HEAD:main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request.        
To https://github.com/make3waves/makaka
 ! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/make3waves/makaka'
    at makeError (/home/runner/work/makaka/makaka/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/makaka/makaka/node_modules/execa/index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async push (/home/runner/work/makaka/makaka/node_modules/@semantic-release/git/lib/git.js:51:3)
    at async module.exports (/home/runner/work/makaka/makaka/node_modules/@semantic-release/git/lib/prepare.js:69:5)
    at async prepare (/home/runner/work/makaka/makaka/node_modules/@semantic-release/git/index.js:28:3)
    at async validator (/home/runner/work/makaka/makaka/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/makaka/makaka/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/makaka/makaka/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async pluginsConf.<computed> [as prepare] (/home/runner/work/makaka/makaka/node_modules/semantic-release/lib/plugins/index.js:80:11) {
  shortMessage: 'Command failed with exit code 1: git push --tags https://github.com/make3waves/makaka HEAD:main',
  command: 'git push --tags https://github.com/make3waves/makaka HEAD:main',
  escapedCommand: 'git push --tags "https://github.com/make3waves/makaka" "HEAD:main"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: error: GH006: Protected branch update failed for refs/heads/main.        \n' +
    'remote: error: Changes must be made through a pull request.        \n' +
    'To [https://github.com/make3waves/makaka\n](https://github.com/make3waves/makaka/n)' +
    ' ! [remote rejected] HEAD -> main (protected branch hook declined)\n' +
    "error: failed to push some refs to 'https://github.com/make3waves/makaka'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/git'
}
```

**Comment by rharkor** [comment]
up

**Comment by KaiSchwarz-cnic** [comment]
+1

**Comment by travi** [comment]
first, consider whether you _really_ need to make commits during your release workflow. semantic-release works well without doing so, which is a big reason we do not include the git plugin in our default configuration.

if you decide that you still want to make commits as part of your release workflow, you need to use a token from a user that has permissions to bypass your branch protection rules. your options for doing so depend on how youve configured your branch protection

**Comment by KaiSchwarz-cnic** [comment]
We noticed that using a fine grained PAT isn't possible even with

```
permissions:
    contents: write,
    issues: write,
    deployments: write
```

activated (we tried also with all permissions activated), still the tag push isn't working. On our end we need the git plugin as we push assets.

 A classic token made this again possible. Not sure about the exact difference between classic and [beta] fine grained tokens, but that's what we noticed ...

**Comment by seebeen** [comment]
If you have protected branches, you need to use a PAT. (Classic or fine grained).

PAT user needs to be exempt from branch protection rules. You also need to define ENV Vars in the release step so everything matches up.

For an example workflow see [this repo](https://github.com/oblakstudio/serbian-addons-for-woocommerce).

**Comment by fantomblackstar** [comment]
I ran into the same issue, and here's the solution that worked for me.

1.  **Specify people, teams who are allowed to bypass required pull requests (available in Branch Protection Settings)**

<img width="550" height="47" alt="Image" src="https://github.com/user-attachments/assets/f7c0e39e-7383-4024-b48d-9b0089e92dad" />

2. **Update GitHub Actions Workflow**

   * Set `persist-credentials: false` in the `actions/checkout` step.
   * Use a **Personal Access Token (PAT)** instead of the default `GITHUB_TOKEN`. 
Token should be generated by users from step 1

###  Example Workflow:

```yaml
jobs:
  semantic-release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false  # 👈 Important!

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        run: npm ci 

      - name: Run Semantic Release
        run: npx semantic-release --ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}  # 👈 Use a PAT here
```

**Comment by oindrila-b** [comment]
Hi, I am facing a similar issues with my semantic-bot. I have created a github app, installed it on my repo, and have given it the following permissions :

```
- Content : Read and Write
- Metadata : Read only
```

My main branch has the protection enabled for requiring PRs for merging to main, however I've also checked the : `Allow specific actors to bypass the rule` -  where I added my app. 

I have also created a github secret token which I am using to allow the semantic bot to push the version to main without having to open a PR.

i had created a test branch with the same permission and the semantic-release-bot was able to push it there but for main I get the same issue.


Can someone give me context? Am I missing permissions?

**Comment by kdev** [comment]
>My main branch has the protection enabled for requiring PRs for merging to main, however I've also checked the : Allow specific actors to bypass the rule - where I added my app.

You need to allow the PAT-Owner to bypass the Rule. If you don't want to allow the PAT Owner to bypass your branch protections you may need to create some sort of service user.

**Comment by oindrila-b** [comment]
Is this not possible without PAT? Since I've created a Github app, made secrets for that app, installed the app, given it the right permissions and also mentioned which repo to push to. 

Here's my release.yml for reference 

```
name: Release

on:
  push:
    branches:
      - main 

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write    # so semantic-release can push commits + tags
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # semantic-release needs full history + tags

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: ./server
        run: bun install

      # NEW STEP: Get GitHub App Token
      - name: Get GitHub App Token
        id: github-app-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RELEASE_APP_ID }}
          private_key: ${{ secrets.RELEASE_APP_SECRET }}
          installation_retrieval_mode: "repository"
          installation_retrieval_payload: ${{ github.repository }}

      - name: Run semantic-release
        working-directory: ./server
        env:
          HUSKY: 0
          # CHANGED: Use GitHub App token instead of default GITHUB_TOKEN
          GITHUB_TOKEN: ${{ steps.github-app-token.outputs.token }}
          GH_TOKEN: ${{ steps.github-app-token.outputs.token }}
        run: bunx semantic-release --no-ci
```
