### ISSUE TITLE
ENOPKG Missing `package.json` file even when package.json is present

### ISSUE THREAD

**Issue by codebarz** [semantic-release/semantic-release#2622]
### Current behavior

I get the ENOPKG Missing `package.json` file error when running a release on GitHub Actions. I added commands to check the files in the directory and the package.json file is present.

I add the `ls` command to list all files just to make sure the `package.json` is present. On the CI logs, you'd see it is present along with the other files.

**Github actions workflow**
```yml
name: Test and Publish
on:
  push:
    branches: 'main'
    paths-ignore:
      - .gitignore
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check for forgotten it.only in unit tests
        run: "! git grep -F 'it.only' -- src/__tests__"
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: yarn test
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [test]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Re-Install
        run: yarn
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Prepare Publish to NPM
        run: yarn run preparePub
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Release
        run: cd dist && pwd && ls -la && npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

Kindly let me know if you need any other info

### Expected behavior

This is meant to create a release to GitHub packages

### `semantic-release` version

19.0.5

### CI environment

Github Actions

### Plugins used

@semantic-release/commit-analyzer
@semantic-release/release-notes-generator
@semantic-release/npm
@semantic-release/github

### `semantic-release` configuration

```json
{
  "branches": [
    "main"
  ],
  "repositoryUrl": "https://github.com/org/org-react-components",
  "debug": "true",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/npm",
      {
        "pkgRoot": "dist/*"
      }
    ],
    "@semantic-release/github"
  ]
}

```

### CI logs

```
/home/runner/work/org-react-components/org-react-components/dist
drwxr-xr-x 6 runner docker 4096 Nov 20 02:13 .
drwxr-xr-x 9 runner docker 4096 Nov 20 02:12 ..
drwxr-xr-x 2 runner docker 4096 Nov 20 02:12 __tests__
drwxr-xr-x 5 runner docker 4096 Nov 20 02:13 cjs
drwxr-xr-x 3 runner docker 4096 Nov 20 02:12 components
drwxr-xr-x 2 runner docker 4096 Nov 20 02:12 constants
-rw-r--r-- 1 runner docker   30 Nov 20 02:12 index.d.ts
-rw-r--r-- 1 runner docker   63 Nov 20 02:12 index.js
-rw-r--r-- 1 runner docker  121 Nov 20 02:12 index.js.map
-rw-r--r-- 1 runner docker   86 Nov 
-rw-r--r-- 1 runner docker  124 Nov 20 02:12 jest.setup.js
-rw-r--r-- 1 runner docker  156 Nov 20 02:12 jest.setup.js.map
-rw-r--r-- 1 runner docker 2692 Nov 20 02:13 package.json
[2:13:06 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.5
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[2:13:06 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[2:13:08 AM] [semantic-release] › ✔  Run automated release from branch main on repository [https://github.com/org/org-react-components](https://github.com/org/org-react-components)
[2:13:09 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[2:13:09 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[2:13:09 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[2:13:09 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[2:13:09 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com/)
[2:13:09 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[2:13:09 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[2:13:11 AM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #8.
[2:13:12 AM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #8: [https://github.com/org/org-react-components/issues/8#issuecomment-1321014942.](https://github.com/org/org-react-components/issues/8#issuecomment-1321014942.)
[2:13:12 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[2:13:12 AM] [semantic-release] › ✖  ENOPKG Missing `package.json` file.
A package.json file (https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.

Please follow the npm guideline (https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid package.json file.

AggregateError: 
    SemanticReleaseError: Missing `package.json` file.
        at module.exports (/home/runner/work/org-react-components/org-react-components/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/home/runner/work/org-react-components/org-react-components/node_modules/@semantic-release/npm/lib/get-pkg.js:17:33)
        at async verifyConditions (/home/runner/work/org-react-components/org-react-components/node_modules/@semantic-release/npm/index.js:32:17)
        at async validator (/home/runner/work/org-react-components/org-react-components/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
        at async /home/runner/work/org-react-components/org-react-components/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async Promise.all (index 0)
        at async next (/home/runner/work/org-react-components/org-react-components/node_modules/p-reduce/index.js:16:18)
    at /home/runner/work/org-react-components/org-react-components/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/runner/work/org-react-components/org-react-components/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/work/org-react-components/org-react-components/node_modules/semantic-release/index.js:103:3)
    at async module.exports (/home/runner/work/org-react-components/org-react-components/node_modules/semantic-release/index.js:269:22)
    at async module.exports (/home/runner/work/org-react-components/org-react-components/node_modules/semantic-release/cli.js:55:5)
Error: Process completed with exit code 1.
```
