### ISSUE TITLE
Add the ability to update changelog without doing anything else.

### ISSUE THREAD

**Issue by albert-a** [semantic-release/semantic-release#2626]
### New feature motivation

I'm facing problems while implementing the pipeline for building Debian packages in GitLab:

- prepare: use semantic release to updae CHANGELOG.md, which is required for subsequent Debian packages builds, but not committing it anywhere, because the build may fail, and release won't happen, I just save it as an artifact to use in the following build stages.
- multiple build stages for different distributions, which require CHANGELOG.md
- release: commit the CHANGELOG.md to the repository and create a release.

The solution suggested in #964 to use exec works only when you have a single build stage. To implement it in one stage I have to dive into building systems that use chrooted environments, which are extremely complex. And it simply no go in comparison to simplicity of the docker images and neat integration to the pipeline. 

Luckily there is the `--dry-run` option, that almost does what I want, It generates and prints the release-notes which I can merge with the existing CHANGELOG.md and create updated CHANGELOG.md.

Unfortunately the format used in the output of the program is different from the format it uses to update CHANGELOG.md. And I have to do a lot of conversion to bring it to the form of CHANGELOG.md:
- strip other (not release notes) output from `semantic-release --dry-run`
- trim whitespaces in the beginning of the lines
- substitute hyperlinks:  WORD (https://site.com) -> \[WORD\](https://site.com)
- insert blank lines before `### sections`
- perform text the manipulation using several temporary files

Although I've implemented it in a bash script, I'm afraid something may break with new semantic-release versions because, for example, the output format might change.

### New feature description

I propose 3 possible solutions:

1. Add `--update-changelog` option for use with `--dry-run` so that it also updates the changelog, but does not commit or  pushing it to any repository.
2. If 1st is not possible, please add `--release-notes-output-file` option for use with `--dry-run` to separate the log output and actual release notes by saving the notes to a separate file. But please do it in the format used to update the changelog.
3. If first two not possible, please at least change the format of the release notes in the `semantic-release --dry-run` output to match the CHANGELOG.md format.

### New feature implementation

Unfortunately I don't have an implementation other than the shell script I mentioned:

```
semantic-release -d | tee >(sed -nr '/^## [][0-9.]/,${s|([0-9A-Za-z/._-]+) \((https://[0-9A-Za-z/?&%_.-]+)\)|[\1](\2)|;s/^\s+//;s/^### /\n&/;p}' > .release-notes.tmp)
{   echo "$CHANGELOG_TITLE"
    echo
    cat .release-notes.tmp
    cat CHANGELOG.md
} > CHANGELOG.md.new
mv CHANGELOG.md{.new,}
```

**Comment by thislooksfun** [comment]
You could also make a new `.releaserc` file with only the plugins needed for generating the changelog and swap it out in your different stages. You can even make a `.releaserc.js` file and disable the plugins based on environment variables.

**Comment by at-blacknight** [comment]
I've also tried to make a new  `.releaserc.yaml` file but i'm actually not sure how to configure it to not create a tag.

> You could also make a new `.releaserc` file with only the plugins needed for generating the changelog and swap it out in your different stages. You can even make a `.releaserc.js` file and disable the plugins based on environment variables.

my use case is to generate the proposed version and the changelog file in order to be used in various points of subsequent pipelines.

```
branches:
    - name: main
    - name: uat
      channel: uat
      prerelease: true

plugins:
    - - "@semantic-release/commit-analyzer"
      - preset: conventionalcommits
    - - "@semantic-release/release-notes-generator"
      - preset: conventionalcommits
        presetConfig:
          compareUrlFormat: "{{host}}/{{owner}}/{{repository}}/branchCompare?baseVersion=GT{{previousTag}}&targetVersion=GT{{currentTag}}&_a=files"
          issueUrlFormat: "{{host}}/{{owner}}/_workitems?id={{id}}"
    - - "@semantic-release/changelog"
      - changelogFile: "NEW-CHANGELOG.md"
        preset: "conventionalcommits"
    - - "semantic-release-ado"
      - varName: version
        setOnlyOnRelease: true
        isOutput: true
tagFormat: "v${version}"
```
