### ISSUE TITLE
How to do git authentication in GitHub Actions

### ISSUE THREAD

**Issue by hongaar** [semantic-release/semantic-release#2636]
### Current behavior

After enabling branch protection on the default branch, I got the following (expected) error:

```
[9:59:32 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags https://github.com/hongaar/semantic-release-yarn.git HEAD:main
remote: error: GH006: Protected branch update failed for refs/heads/main.        
remote: error: Changes must be made through a pull request. 3 of 3 required status checks are expected.        
To https://github.com/hongaar/semantic-release-yarn.git
 ! [remote rejected] HEAD -> main (protected branch hook declined)
error: failed to push some refs to 'https://github.com/hongaar/semantic-release-yarn.git'
```

I then switched from the GitHub Actions provided token to a Personal Access Token (since I'm an admin for this project, I should be able to circumvent the branch protection rules).

```diff
     - run: yarn release
        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GH_TOKEN: ${{ secrets.GH_PAT }}
```

I got the same error.

After some debugging, it occurs to me that probably the authentication from the `checkout` action is used instead of my passed in PAT, so:

```diff
     - uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.GH_PAT }}
```

This works.

However, then I read that [the recommended approach](https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#pushing-package.json-changes-to-a-master-branch) is to instead use:

```diff
     - uses: actions/checkout@v3
        with:
-          token: ${{ secrets.GH_PAT }}
+          persist-credentials: false
```

But now I'm getting errors again:

```
2022-12-08T12:04:41.425Z semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://github.com/hongaar/semantic-release-yarn.git
2022-12-08T12:04:41.538Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://github.com/hongaar/semantic-release-yarn.git HEAD:main
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/hongaar/semantic-release-yarn.git/'
```

I remember seeing different logic for GH_TOKEN and GITHUB_TOKEN in the source code, so I try:

```diff
     - run: yarn release
        env:
-          GH_TOKEN: ${{ secrets.GH_PAT }}
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
```

That works!

### Expected behavior

There is one recommended approach to use GitHub Actions + semantic-release with a Personal Access Token (e.g. to circumvent branch protection for release commits)

### `semantic-release` version

19.0.5

### CI environment

GitHub Actions

### Plugins used

See config

### `semantic-release` configuration

```json5
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "../../../../dist/cjs/index.cjs", // entrypoint for "semantic-release-yarn"
    "@semantic-release/github",
    [
      "@semantic-release/git",
      {
        "assets": ["CHANGELOG.md", "package.json", "packages/*/package.json"],
        "message": "chore(release): ${nextRelease.version}\n\n${nextRelease.notes}\n\n[skip ci]"
      }
    ]
  ]
}
```

### CI logs

Relevant lines included above, full logs in commit history here: https://github.com/hongaar/semantic-release-yarn/commits/main

**Comment by hongaar** [comment]
I'd be happy to contribute a PR but would like some input in how to approach this, i.e. shou

**Comment by TimPietrusky** [comment]
I only got my GitHub Action + Branch Protection + Semantic Release working because of this issue. 

Thank you @hongaar

**Comment by kdev** [comment]
This is maybe off-topic but:
@TimPietrusky would you mind sharing how you setup your branch protection to allow pushes from semantic-release?

**Comment by Zebradil** [comment]
The following configuration works for me:

```yaml
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Semantic Release
        id: semantic
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GH_PAT }}
```

Where `CUSTOM_GH_PAT` is a personal access token with full `repo` access, the corresponding user of this token is an admin in the repository — for bypassing branch protection.

**Comment by TimPietrusky** [comment]
@kdev almost exactly how @Zebradil did it, just using `semantic-release` directly:

```
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      // Some stuff in between

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
```

[See full action](https://github.com/failfa-st/2D-GameCreator/blob/main/.github/workflows/release.yml).
