### ISSUE TITLE
New version not published since v20.1.0 because local branch wrongfully assumed to be behind the remote one

### ISSUE THREAD

**Issue by qutax** [semantic-release/semantic-release#2693]
### Current behavior

When running the pipeline with changes that should trigger a new release, a version is not published with the following message:
> The local branch main is behind the remote one, therefore a new version won't be published.

However, there were no changes and the local branch should be up-to-date.

Downgrading to v20.0.4 resolves the issue.

### Expected behavior

A new version should be published / `semantic-release` should correctly check the status of the local Git branch.

### `semantic-release` version

20.1.0

### CI environment

Azure Pipelines

### Plugins used

- @semantic-release/commit-analyzer
- @semantic-release/release-notes-generator
- @semantic-release/changelog
- @semantic-release/npm
- @semantic-release/git
- [@codedependant/semantic-release-docker](https://github.com/esatterwhite/semantic-release-docker)
- [semantic-release-ado](https://github.com/lluchmk/semantic-release-ado)

### `semantic-release` configuration

```yaml
branches:
  - "main"
#repositoryUrl: — no need, will use from git origin
tagFormat: "[REDACTED]-${version}"
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/npm"
  - - "@semantic-release/git"
    - message: |
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}
      assets:
        - "CHANGELOG.md"
        - "package.json"
  - - "@codedependant/semantic-release-docker"
    - dockerFile: "packages/backend/Dockerfile"
      dockerImage: "[REDACTED]"
      dockerLogin: false
      dockerProject: "service"
      dockerRegistry: "[REDACTED]"
      dockerTags: [ "latest", "{{version}}", "{{major}}-latest", "{{major}}.{{minor}}" ]
  - - "semantic-release-ado"
    - varName: "imageVersion"
      setOnlyOnRelease: true
      isOutput: true
```

### CI logs

```text
[4:38:45 PM] [semantic-release] › ℹ  Running semantic-release version 20.1.0
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@codedependant/semantic-release-docker"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "semantic-release-ado"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "semantic-release-ado"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@codedependant/semantic-release-docker"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@codedependant/semantic-release-docker"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "success" from "@codedependant/semantic-release-docker"
[4:38:46 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@codedependant/semantic-release-docker"
[4:38:47 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://[REDACTED].visualstudio.com/[REDACTED]/_git/[REDACTED]
[4:38:47 PM] [semantic-release] › ℹ  The local branch main is behind the remote one, therefore a new version won't be published.
```
