### ISSUE TITLE
Changing running branch for semantic release

### ISSUE THREAD

**Issue by mehdihadeli** [semantic-release/semantic-release#2704]
Hi,
I defined possible branches for my releases inner `.releaserc.yaml`. But because I'm using [workflow_run](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run) of GitHub action inner my CD workflow, it gives me a default branch for `GITHUB_REF` GitHub action environment variable, that is not my exactly triggered branch. Is there any way, when I run `npx semantic-release`, I pass my desired branch for analyzing semantic-release?

``` yaml
branches:
   - main
   - '+([0-9])?(.{+([0-9]),x}).x'
   - name: develop
     prerelease: dev
     channel:  dev
```
