### ISSUE TITLE
Travis job does not complete (minion is waiting for a leader; leader is waiting for the minion)

### ISSUE THREAD

**Issue by gajus** [semantic-release/semantic-release#274]
This is the leader:

https://travis-ci.org/gajus/gitinfo/jobs/152546543

```
This is a leader
Leader waits for minions [u'92.2', u'92.3']...
Leader waits for minions [u'92.2', u'92.3']...
Leader waits for minions [u'92.2', u'92.3']...
Leader waits for minions [u'92.2', u'92.3']...
Leader waits for minions [u'92.2', u'92.3']...
Leader waits for minions [u'92.2', u'92.3']...
Leader waits for minions [u'92.2']...
Leader waits for minions [u'92.2']...
Leader waits for minions [u'92.2']...
Leader waits for minions [u'92.2']...
Leader waits for minions [u'92.2']...
```

It appears to be waiting for job #92.2.

Here is the job #92.2:

https://travis-ci.org/gajus/gitinfo/jobs/152546544

```
[travis-after-all] Job succeeded (8410eebc89b4c2d11691744e52da09fd89c48ac5fd599c7ef564c66bac130664)
[travis-after-all] Waiting for 92.1 and 92.3 to be done...
[travis-after-all] Waiting for 92.1 and 92.3 to be done...
[travis-after-all] Waiting for 92.1 to be done...
[travis-after-all] Waiting for 92.1 to be done...
[travis-after-all] Waiting for 92.1 to be done...
```

It appears to be waiting for the leader to complete.

This is my `.travis-ci.yml` configuration:

``` yaml
language: node_js
node_js:
    - 6
    - 5
    - 4
before_install:
    - npm install --global npm@3
before_script:
    - curl -Lo travis_after_all.py https://git.io/vLSON
script:
    - NODE_ENV=development npm run build
    - rm -fr ./dist
    - NODE_ENV=production npm run build
    - npm run lint
    - flow
    - nyc --silent npm run test
    - nyc report --reporter=text-lcov | coveralls
    - nyc check-coverage --lines 90
    - conventional-changelog-lint --from=HEAD~$(git --no-pager rev-list master..HEAD --count)
after_success:
    - python travis_after_all.py
    - export $(cat .to_export_back)
    - git config --global user.name "semantic-release (via TravisCI)"
    - git config --global user.email "semantic-release@travis"
    - semantic-release pre && npm publish && semantic-release post
notifications:
    email: false
sudo: false
```

What am I missing?
