### ISSUE TITLE
[Feature Request] NPM provenance

### ISSUE THREAD

**Issue by jonluca** [semantic-release/semantic-release#2770]
### New feature motivation

You can generate provenance statements for the packages you publish. This allows you to publicly establish where a package was built and who published a package, which can increase supply-chain security for your packages.

### New feature description

https://docs.npmjs.com/generating-provenance-statements

NPM has provenance statements in Github Actions - it would be great if we could add a flag that adds it in semantic-release

**Comment by travi** [comment]
This is already supported. Please see https://github.com/semantic-release/npm#npm-provenance

Would additional details or highlighting this in another part of our docs make this more clear?

**Comment by travi** [comment]
i've added another mention of using provenance to our docs [here](https://semantic-release.gitbook.io/semantic-release/recipes/ci-configurations/github-actions#npm-provenance), so i'm going to close this for now. feel free to still respond if you think that other mentions elsewhere would have been helpful when you were looking for this information.

**Comment by jonluca** [comment]
Awesome, nope I should've RTFM. Thanks!

**Comment by travi** [comment]
No worries. Since its new, still trying to figure out the best way to make it clear that we're good to go. Excited to see that you're already opting in to using provenance 🎉

**Comment by jonluca** [comment]
One more minor thing that is definitely due to me blindly copy + pasting, but if you copy + paste the default ci from the npm docs you link to, it causes semantic release to fail with `EGITNOPERMISSION`.

The docs have

```yaml
name: Publish Package to npmjs
on:
 release:
   types: [created]
jobs:
 build:
   runs-on: ubuntu-latest
   permissions:
     contents: read
     id-token: write
   steps:
     - uses: actions/checkout@v3
     - uses: actions/setup-node@v3
       with:
         node-version: '18.x'
         registry-url: 'https://registry.npmjs.org'
     - run: npm install -g npm
     - run: npm ci
     - run: npm publish --provenance --access public
       env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

as the default, but it needs to be:

```
    permissions:
      contents: write
      id-token: write
```

for it to work (due to pushing to the master branch)
