### ISSUE TITLE
Changelog links no longer valid with GitLab 16.0 release

### ISSUE THREAD

**Issue by ryancausey** [semantic-release/semantic-release#2804]
### Current behavior

The changelog commit links are no longer working as of GitLab 16.0. With the release of GitLab version 16.0, the "legacy routes" were removed. See these links for more info:

https://docs.gitlab.com/ee/update/removals.html#legacy-routes-removed

https://gitlab.com/gitlab-org/gitlab/-/issues/28848

This means that the currently generated changelog URLS, such as `https://gitlab.com/munipal-oss/fluctuate/commit/648ebcf7a7b53408be50416a136db53448465605` are no longer valid and result in a 404. These URLS need a `/-/` at the end of the group/project path. Given the previous invalid URL, a valid URL is `https://gitlab.com/munipal-oss/fluctuate/-/commit/648ebcf7a7b53408be50416a136db53448465605`.

### Expected behavior

The changelog links generated are valid for GitLab.com

### `semantic-release` version

21.0.2

### CI environment

GitLab

### Plugins used

- "@semantic-release/commit-analyzer"
- "@semantic-release/release-notes-generator"
- "@semantic-release/changelog"
- "@semantic-release/exec"
- "@semantic-release/git"
- "@semantic-release/gitlab"

### `semantic-release` configuration

```yaml
preset: conventionalcommits
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  # Funky nested list because that's what semantic-release expects
  -
    - "@semantic-release/exec"
    - "prepareCmd": "~/.local/bin/poetry version ${nextRelease.version}"
      "publishCmd": "~/.local/bin/poetry publish
        --build
        --no-interaction
        -vvv"
  -
    - "@semantic-release/git"
    - "assets":
      - "dist/**/*.tar.gz"
      - "dist/**/*.whl"
      - "CHANGELOG.md"
      # Need this to keep the version number update in the pyproject.toml file that is
      # updated during release.
      - "pyproject.toml"
  -
    - "@semantic-release/gitlab"
    - "assets":
      - "path": "dist/**/*.tar.gz"
        "label": "Source distribution"
        "type": "package"
      - "path": "dist/**/*.whl"
        "label": "Wheel package"
        "type": "package"
```

### CI logs

https://gitlab.com/munipal-oss/fluctuate/-/jobs/4238025685
