### ISSUE TITLE
ISSUE: Failed step "verifyConditions" of plugin "@semantic-release/npm

### ISSUE THREAD

**Issue by AnneJoJo** [semantic-release/semantic-release#2951]
### Current behavior

Hello, Our team recently faces a build issue with  "verifyConditions" of plugin "@semantic-release/npm".
**Node: 16.13.0
yarn 1.22.17**
semantic-release version: 17.3.0 (I also tried 19.0.2, still failed)

This is our ***.yml file, for some credential issue, I customized our lib name

```
inherit: "job:///metropolis/templates/looper-template-node"
tools:
  nodejs: 16.13.0
  yarn: 1.22.17
  sonarscanner: 4.6.2.2472

envs:
  global:
    variables:
      SLACK_CHANNEL: "[channel name]"
      SLACK_CHANNEL_ERROR: "[channel name]"
      GITHUB_BASE: "[channel domain]"
      GITHUB_REPO: "[repo name]"
      GITHUB_COMMIT_ID: ${GITHUB_BRANCH_HEAD_SHA}
      # Scripts
      LOOPER_SCRIPT_MODULE: "scripts"
      LOOPER_SCRIPT_PATH: node_modules/${LOOPER_SCRIPT_MODULE}/[cicd tool name]
      # Branch names
      RELEASE_BRANCH: main
      DOCUMENTATION_BRANCH: documentation

branches:
  - spec: main
    triggers:
      - pr:
          call: pr
      - push:
          call: push
          ignoreAuthor:
            - jenkinspan

flows:
  pr:
    try:
      - shell: echo "Checking pull request"
      - call: installDependencies
      - call: checkCommitCount
      - call: runUnitTesting
      - call: checkCommitFormat
    finally:
      - call: run-sonar-pr

  push:
    try:
      - shell: echo "Release flow"
      - call: installDependencies
      - var(prevPackage): exposeVars(package.json)
      - call: release(BRANCH=$RELEASE_BRANCH)
      - var(package): exposeVars(package.json)
      - call: verifyRelease
      - call: generateDocumentation
      - call: notifyReleaseSuccess
    finally:
      - call: run-sonar

  installDependencies:
    try:
      - call: yarn-install

  yarn-install:
    - (name Yarn - Install) yarn install --loglevel verbose

  runUnitTesting:
    - shell (name Run unit and/or integration tests): yarn test --coverage

  verifyRelease:
    - shell (name Verify the release): |
          bash ${LOOPER_SCRIPT_PATH}/verify-release.sh ${prevPackage.version} ${package.version}

  release:
    - shell (name Release with semantic-release for ${BRANCH} branch): |
        rm -rf ./docs/*
        rm -rf node_modules
        yarn install
        git remote prune origin
        npx semantic-release

  updatePackageJSONVersion:
    - try:
        shell (name Updating release version): |
            bash ${LOOPER_SCRIPT_PATH}/update-release-version.sh ${package.version} ${BRANCH}
      catch:
        call: notifyMergeFailure

  generateDocumentation:
    - shell (name Generate documentation): |
          bash ${LOOPER_SCRIPT_PATH}/generate-documentation.sh ${package.version} ${DOCUMENTATION_BRANCH} ${RELEASE_BRANCH}

  checkCommitCount:
    - shell (name Check that there is only a single commit): |
          bash ${LOOPER_SCRIPT_PATH}/check-commit-count.sh ${RELEASE_BRANCH} ${NEXT_BRANCH}

  checkCommitFormat:
    - shell (name Check the commit format): |
          bash ${[CICD name]_SCRIPT_PATH}/check-commit-format.sh

  notifyReleaseSuccess:
    - slack.postMessage:
        message: ":party: 
                  ${package.name}
                  *v${package.version}*
                  has been released! 
                  :party:"
        channelId: ${SLACK_CHANNEL}
        iconEmoji: ":build-doge-right:"
        attachments:
          - blocks:
            - type: section
              text:
                type: mrkdwn
                text: 'Release Documentation'
          - fallback: ${BUILD_URL}
            actions:
            - type: "button"
              text: "Release Notes"
              url: "${GITHUB_BASE}/${GITHUB_REPO}/releases/tag/v${package.version}"
            - type: "button"
              text: "Api Docs"
              url: "${GITHUB_BASE}/pages/${GITHUB_REPO}"
            - type: "button"
              text: "Current Code Diff"
              url: "${GITHUB_BASE}/${GITHUB_REPO}/commit/${GITHUB_COMMIT_ID}"      
          - blocks:
            - type: section
              text:
                type: mrkdwn
                text: '[CICD name] Build Job logs & info'

  notifyMergeFailure:
    - slack.postMessage:
        message: "${package.name}
                  An error occurred while merging ${RELEASE_BRANCH} into ${NEXT_BRANCH}!"
        channelId: ${SLACK_CHANNEL_ERROR}
        iconEmoji: ":paerror:"

  run-sonar-pr:
    - call: run-sonar-with-pr

  run-sonar:
    - sonar("Sonar"):
        - (cpc-api-client sonar) sonar-scanner -Dproject.settings=sonar-project.properties

  run-sonar-with-pr:
    - sonar("Sonar"):
        - (cpc-api-client-pr sonar) sonar-scanner -X -Dproject.settings=sonar-project.properties
          -Dsonar.pullrequest.github.repository=${GITHUB_ORG}/${GITHUB_REPO}
          -Dsonar.pullrequest.key=${GITHUB_PR_NUMBER}
          -Dsonar.pullrequest.branch=${GITHUB_PR_SOURCE_BRANCH}
          -Dsonar.pullrequest.base=${GITHUB_PR_TARGET_BRANCH}
          -Dsonar.scm.revision=${GITHUB_PR_HEAD_SHA}
```

### Expected behavior

Should get` npx --no-install semantic-release ` passed

### `semantic-release` version

17.3.0

### CI environment

Github actions

### Plugins used

@semantic-release/exec": "^5.0.0 @semantic-release/git": "9.0.0"

### `semantic-release` configuration

```
{
  "branches": ["main"],
  "ci": true,
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    "@semantic-release/git"
  ]
}
```

### CI logs

17:44:31 + git remote prune origin
17:44:31 + npx semantic-release
17:44:32 [9:44:32 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.7
17:44:33 [9:44:32 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
17:44:33 [9:44:32 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
17:44:33 [9:44:32 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
17:44:33 [9:44:32 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
17:44:33 [9:44:32 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
17:44:33 [9:44:32 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
17:44:33 [9:44:32 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
17:44:33 [9:44:32 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
17:44:36 [9:44:36 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://gecgithub01.walmart.com/CustomerTransaction/cpc-api-client.git
17:44:37 [9:44:37 PM] [semantic-release] › ✔  Allowed to push to the Git repository
17:44:37 [9:44:37 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry [secure]
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /mnt/jenkinspan/.npmrc, /mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/.npmrc
17:44:37 [9:44:37 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
17:44:37 [9:44:37 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
17:44:37 [9:44:37 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
17:44:37 [9:44:37 PM] [semantic-release] › ℹ  Found git tag v19.5.0 associated with version 19.5.0 on branch main
17:44:37 [9:44:37 PM] [semantic-release] › ℹ  Found 13 commits since last release
17:44:37 [9:44:37 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: revert: revert july 12 (#512)
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: revert chnage back (#511)
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(.looper.yml): added npm version to see if it fixes the build issue (#509)
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci(.looper.yml): added npm version to see if it fixes the build issue (#508)
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(balanceinquiry): production EBT and Gift card inquiry API is missing "authorizationTimestamp" (#499)
17:44:37 
17:44:37 Production EBT and Gift card inquiry API is missing "authorizationTimestamp" field. These field is
17:44:37 available in the CPC QA environment. This filed will be necessary to display the timestamp for COSTL
17:44:37 lane
17:44:37 
17:44:37 BREAKING CHANGE: Removed authorizationTimestamp checks and made it optional field
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is major
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 13 commits complete: major release
17:44:37 [9:44:37 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
17:44:37 [9:44:37 PM] [semantic-release] › ℹ  The next release version is 20.0.0
17:44:37 [9:44:37 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
17:44:37 [9:44:37 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
17:44:37 [9:44:37 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
17:44:37 [9:44:37 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 20.0.0 to package.json in /mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws
17:44:37 TypeError: Class extends value #<Object> is not a constructor or null
17:44:37     at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/read-entry.js:91:4)
17:44:37     at Module._compile (node:internal/modules/cjs/loader:1101:14)
17:44:37     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
17:44:37     at Module.load (node:internal/modules/cjs/loader:981:32)
17:44:37     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
17:44:37     at Module.require (node:internal/modules/cjs/loader:1005:19)
17:44:37     at require (node:internal/modules/cjs/helpers:102:18)
17:44:37     at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/pack.js:27:19)
17:44:37     at Module._compile (node:internal/modules/cjs/loader:1101:14)
17:44:37     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
17:44:37 [9:44:37 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
17:44:37 [9:44:37 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: npm version 20.0.0 --userconfig /tmp/594281f9968163fc243be8b516072c93/.npmrc --no-git-tag-version --allow-same-version
17:44:37 TypeError: Class extends value #<Object> is not a constructor or null
17:44:37     at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/read-entry.js:91:4)
17:44:37     at Module._compile (node:internal/modules/cjs/loader:1101:14)
17:44:37     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
17:44:37     at Module.load (node:internal/modules/cjs/loader:981:32)
17:44:37     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
17:44:37     at Module.require (node:internal/modules/cjs/loader:1005:19)
17:44:37     at require (node:internal/modules/cjs/helpers:102:18)
17:44:37     at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/pack.js:27:19)
17:44:37     at Module._compile (node:internal/modules/cjs/loader:1101:14)
17:44:37     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
17:44:37     at makeError (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/execa/lib/error.js:60:11)
17:44:37     at handlePromise (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/execa/index.js:118:26)
17:44:37     at processTicksAndRejections (node:internal/process/task_queues:96:5)
17:44:37     at async module.exports (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/@semantic-release/npm/lib/prepare.js:21:3)
17:44:37     at async prepare (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/@semantic-release/npm/index.js:68:3)
17:44:37     at async validator (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
17:44:37     at async /mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
17:44:37     at async Promise.all (index 0)
17:44:37     at async next (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/p-reduce/index.js:16:18) {
17:44:37   shortMessage: 'Command failed with exit code 1: npm version 20.0.0 --userconfig /tmp/594281f9968163fc243be8b516072c93/.npmrc --no-git-tag-version --allow-same-version',
17:44:37   command: 'npm version 20.0.0 --userconfig /tmp/594281f9968163fc243be8b516072c93/.npmrc --no-git-tag-version --allow-same-version',
17:44:37   escapedCommand: 'npm version 20.0.0 --userconfig "/tmp/594281f9968163fc243be8b516072c93/.npmrc" --no-git-tag-version --allow-same-version',
17:44:37   exitCode: 1,
17:44:37   signal: undefined,
17:44:37   signalDescription: undefined,
17:44:37   stdout: '',
17:44:37   stderr: 'TypeError: Class extends value #<Object> is not a constructor or null\n' +
17:44:37     '    at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/read-entry.js:91:4)\n' +
17:44:37     '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
17:44:37     '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
17:44:37     '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
17:44:37     '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
17:44:37     '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
17:44:37     '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
17:44:37     '    at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/pack.js:27:19)\n' +
17:44:37     '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
17:44:37     '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)',
17:44:37   failed: true,
17:44:37   timedOut: false,
17:44:37   isCanceled: false,
17:44:37   killed: false,
17:44:37   pluginName: '@semantic-release/npm'
17:44:37 }
17:44:37 Error: Command failed with exit code 1: npm version 20.0.0 --userconfig /tmp/594281f9968163fc243be8b516072c93/.npmrc --no-git-tag-version --allow-same-version
17:44:37 TypeError: Class extends value #<Object> is not a constructor or null
17:44:37     at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/read-entry.js:91:4)
17:44:37     at Module._compile (node:internal/modules/cjs/loader:1101:14)
17:44:37     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
17:44:37     at Module.load (node:internal/modules/cjs/loader:981:32)
17:44:37     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
17:44:37     at Module.require (node:internal/modules/cjs/loader:1005:19)
17:44:37     at require (node:internal/modules/cjs/helpers:102:18)
17:44:37     at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/pack.js:27:19)
17:44:37     at Module._compile (node:internal/modules/cjs/loader:1101:14)
17:44:37     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
17:44:37     at makeError (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/execa/lib/error.js:60:11)
17:44:37     at handlePromise (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/execa/index.js:118:26)
17:44:37     at processTicksAndRejections (node:internal/process/task_queues:96:5)
17:44:37     at async module.exports (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/@semantic-release/npm/lib/prepare.js:21:3)
17:44:37     at async prepare (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/@semantic-release/npm/index.js:68:3)
17:44:37     at async validator (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
17:44:37     at async /mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
17:44:37     at async Promise.all (index 0)
17:44:37     at async next (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/p-reduce/index.js:16:18) {
17:44:37   shortMessage: 'Command failed with exit code 1: npm version 20.0.0 --userconfig /tmp/594281f9968163fc243be8b516072c93/.npmrc --no-git-tag-version --allow-same-version',
17:44:37   command: 'npm version 20.0.0 --userconfig /tmp/594281f9968163fc243be8b516072c93/.npmrc --no-git-tag-version --allow-same-version',
17:44:37   escapedCommand: 'npm version 20.0.0 --userconfig "/tmp/594281f9968163fc243be8b516072c93/.npmrc" --no-git-tag-version --allow-same-version',
17:44:37   exitCode: 1,
17:44:37   signal: undefined,
17:44:37   signalDescription: undefined,
17:44:37   stdout: '',
17:44:37   stderr: 'TypeError: Class extends value #<Object> is not a constructor or null\n' +
17:44:37     '    at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/read-entry.js:91:4)\n' +
17:44:37     '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
17:44:37     '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
17:44:37     '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
17:44:37     '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
17:44:37     '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
17:44:37     '    at require (node:internal/modules/cjs/helpers:102:18)\n' +
17:44:37     '    at Object.<anonymous> (/mnt/jenkinspan/workspace/CustomerTransaction/webpos2.0/cpc-api-services/ws/node_modules/npm/node_modules/tar/lib/pack.js:27:19)\n' +
17:44:37     '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
17:44:37     '    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)',
17:44:37   failed: true,
17:44:37   timedOut: false,
17:44:37   isCanceled: false,
17:44:37   killed: false,
17:44:37   pluginName: '@semantic-release/npm'
```
