### ISSUE TITLE
package.json version doesn't update for private repo

### ISSUE THREAD

**Issue by olliecee** [semantic-release/semantic-release#3396]
## Issue
I want to use the `@semantic-release/npm` package which is included as one of the default plugins from [semantic-release](https://github.com/semantic-release/semantic-release) to simply update my `package.json`'s version property during my GitHub actions CI workflow. 

According to the official documentation for the `npmPublish` option it says
> If `false` the package.json version will still be updated.

Also, the default setting is `false`
> `false` if the package.json [private](https://docs.npmjs.com/files/package.json#private) property is `true`, `true` otherwise.
<img width="948" alt="image" src="https://github.com/user-attachments/assets/b37f0dca-ec64-4c45-8f50-42c42989c413">

I added my `package.json` to show that my `private` property is set to `true`, which would prevent npm publishing but still allow my `package.json`'s version to update.

The most interesting part is that the logs indicate a version update to my package.json but I don't see that reflected in my repository.
```
[@semantic-release/npm] › ℹ  Write version 1.0.1 to package.json in /home/runner/work/royaletactics/royaletactics
v1.0.1
```

## My settings + logs + package.json file
`.github/workflows/release.yml`

File contents
```
name: CI
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
```

`npx semantic-release` results
```
[7:33:42 PM] [semantic-release] › ℹ  Running semantic-release version 24.0.0
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[7:33:42 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[7:33:43 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://github.com/redacted
[7:33:43 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[7:33:43 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[7:33:43 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[7:33:43 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[7:33:43 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com/)
[7:33:43 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[7:33:43 PM] [semantic-release] › ℹ  Found git tag v1.0.0 associated with version 1.0.0 on branch main
[7:33:43 PM] [semantic-release] › ℹ  Found 1 commits since last release
[7:33:43 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[7:33:43 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: allow package.json to update versioning
[7:33:43 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[7:33:43 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: patch release
[7:33:43 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[7:[33](https://github.com/redacted/actions/runs/9997562781/job/27634410792#step:6:34):43 PM] [semantic-release] › ℹ  The next release version is 1.0.1
[7:33:43 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[7:33:43 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[7:33:43 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[7:33:43 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 1.0.1 to package.json in /home/runner/work/royaletactics/royaletactics
v1.0.1
[7:33:44 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[7:33:45 PM] [semantic-release] › ✔  Created tag v1.0.1
[7:33:45 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
[7:33:45 PM] [semantic-release] [@semantic-release/npm] › ℹ  Skip publishing to npm registry as package.json's private property is true
[7:33:45 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"
[7:33:45 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
[7:33:[45](https://github.com/redacted/actions/runs/9997562781/job/27634410792#step:6:46) PM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/redacted/releases/tag/v1.0.1
[7:33:45 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[7:33:45 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[7:33:[46](https://github.com/redacted/actions/runs/9997562781/job/27634410792#step:6:47) PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/github"
[7:33:46 PM] [semantic-release] › ✔  Published release 1.0.1 on default channel
```

`package.json`
File contents
```
{
  "name": "redacted",
  "version": "0.1.1",
  "private": true,
  "author": "redacted",
  "repository": {
    "url": "https://github.com/redacted"
  },
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@babel/runtime": "^7.24.7",
    "@heroicons/react": "^2.1.3",
    "@reduxjs/toolkit": "^2.2.3",
    "@sentry/react": "^8.18.0",
    "@shopify/polaris": "^13.2.0",
    "date-fns": "^3.6.0",
    "firebase": "^10.11.1",
    "formik": "^2.4.6",
    "goober": "^2.1.14",
    "lodash": "^4.17.21",
    "next": "^14.2.3",
    "react": "^18",
    "react-dom": "^18",
    "react-redux": "^9.1.2",
    "yup": "^1.4.0",
    "zod": "^3.23.4"
  },
  "devDependencies": {
    "@types/lodash": "^4.17.1",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.4.19",
    "eslint": "^9.6.0",
    "postcss": "^8.4.38",
    "semantic-release": "^24.0.0",
    "tailwindcss": "^3.4.4",
    "typescript": "^5"
  }
}

```
