### ISSUE TITLE
Release 24.1.0 breaks pipeline

### ISSUE THREAD

**Issue by ppa007asr** [semantic-release/semantic-release#3429]
### Current behavior

When using pipelines a task status for commands is checked with the stderr stream on linux. When its empty the task is succesful completed.
When something is found on the stderr stream the task fails and pipeline stops.

Some platforms give the option to ignore any messages on stderr. You could use that to ignore warning messages but that would mean any relevant error messages get ignored as well

### Expected behavior

warning messages should be send to stdout and maybe create a featureflag to be able to send it to stderr. but not do this by default

### `semantic-release` version

24.1.0

### CI environment

azure

### Plugins used

semantic-release/commit-analyzer
semantic-release/changelog
semantic-release/git
semantic-release-ado

### `semantic-release` configuration

```yml
branches:
  - main
tagFormat: "v${version}"
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: conventionalcommits
      releaseRules:
        - type: docs
          release: patch
        - type: refactor
          release: patch
        - type: test
          release: patch
        - type: style
          release: patch
      parserOpts:
        mergePattern: "Merged PR .*:"
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
  - - "semantic-release-ado"
    - isOutput: true
      setOnlyOnRelease: false
      assets:
        - CHANGELOG.md
```

### CI logs

```
[8:51:30 AM] [semantic-release] › ℹ  Running semantic-release version 24.1.0
[8:51:30 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[8:51:30 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[8:51:30 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:51:30 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "semantic-release-ado"
[8:51:30 AM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "semantic-release-ado"
[8:51:30 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[8:51:30 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[8:51:33 AM] [semantic-release] › ⚠  Run automated release from branch main on repository ### in dry-run mode
[8:51:33 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:51:33 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[8:51:33 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[8:51:33 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[8:51:33 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[8:51:33 AM] [semantic-release] › ℹ  Found git tag v1.9.3 associated with version 1.9.3 on branch main
[8:51:33 AM] [semantic-release] › ℹ  Found 2 commits since last release
[8:51:33 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:51:33 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ###
[8:51:33 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[8:51:33 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: Add node files and folders to gitignore
[8:51:33 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[8:51:33 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[8:51:33 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:51:33 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "semantic-release-ado"
[8:51:33 AM] [semantic-release] [semantic-release-ado] › ℹ  Setting current version 1.9.3 to the env var nextRelease

[8:51:33 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "semantic-release-ado"
[8:51:33 AM] [semantic-release] › ℹ  The next release version is 1.9.4
[8:51:33 AM] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "semantic-release-ado"
[8:51:33 AM] [semantic-release] [semantic-release-ado] › ℹ  Setting version 1.9.4 to the env var nextRelease

[8:51:33 AM] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "semantic-release-ado"
[8:51:33 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/changelog" in dry-run mode
[8:51:33 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/git" in dry-run mode
[8:51:33 AM] [semantic-release] › ⚠  Skip v1.9.4 tag creation in dry-run mode
[8:51:33 AM] [semantic-release] › ✔  Published release 1.9.4 on default channel
[8:51:33 AM] [semantic-release] › ℹ  Release note for version 1.9.4:
##[error]Bash wrote one or more lines to the standard error stream.
##[error][8:51:33 AM] [semantic-release] › ⚠  Run automated release from branch main on repository ### in dry-run mode
##[error][8:51:33 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/changelog" in dry-run mode
##[error][8:51:33 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/git" in dry-run mode
##[error][8:51:33 AM] [semantic-release] › ⚠  Skip v1.9.4 tag creation in dry-run mode
```
