### ISSUE TITLE
This test run is not the build leader and therefore a new version won’t be published.

### ISSUE THREAD

**Issue by cacothi** [semantic-release/semantic-release#347]
Hey Guys,

I'm getting the following message when push it to trevis:

This test run is not the build leader and therefore a new version won’t be published.

What does it means? the test is running successfully

**Comment by armand1m** [comment]
i'm getting this same issue on travis ci, this job shows it better for further details: https://travis-ci.org/armand1m/generate-random-points/jobs/198233123

**Comment by Khaledgarbaya** [comment]
I am having the same issue. I did publish the package manually but still failing in the next pushes

**Comment by armand1m** [comment]
Apparently it just seems like the library will wait until the master build leader resolves the CI cycle, so when it is done, it does publish the package. Probably this feature is implemented in order to avoid publish the package more than once. Would be nice to see it in docs. (I did not has searched but never has seen before either so, if it exists, someone post the link here please.)

**Comment by Khaledgarbaya** [comment]
Yeah, that was the issue thanks a lot. But what if I want to release a specific version that is not the leader like currently I am testing using node 6 and 7 and I want to release only in v6 because it is.

**Comment by jy95** [comment]
Still the case .. Any news about this ?

I am using semantic-release 7.0.2 and Travis CI.

my .travis.yml
```yml
language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack:
      on_success: change
      on_failure: always
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
after_success:
  - npm run coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
```
