### ISSUE TITLE
sh: semantic-release: command not found

### ISSUE THREAD

**Issue by balibou** [semantic-release/semantic-release#351]
Hello,

When I run: "npm run semantic-release" (semantic-release pre && npm publish && semantic-release post), I get this error: "sh: semantic-release: command not found"

I've just followed the instructions from [here](https://glebbahmutov.com/blog/how-to-setup-semantic-release-on-circle-ci/) then installed a package for CircleCI [here](https://github.com/bahmutov/condition-circle#install-and-configure)

Thanks for any help :)

**Comment by matiascarranza** [comment]
Hi @balibou, try running `npm install` after semantic-release-cli setup

**Comment by pvdlg** [comment]
@balibou Did that solved your issue ?

**Comment by dwiyatci** [comment]
I've got a similar issue on the latest version (9.1.0) on Travis CI here. Not sure where I did it wrong. 

`"scripts": { "semantic-release": "semantic-release" }`

Any clue?

![screen shot 2017-11-01 at 20 39 08](https://user-images.githubusercontent.com/4405796/32294038-4a4d4b8e-bf45-11e7-9e76-d83ca38ed0ce.png)

**Comment by pvdlg** [comment]
Can you try again after removing `npm prune` from your `.travis.yml` ?

**Comment by dwiyatci** [comment]
@pvdlg Thanks a lot for the valuable clue! I think that's it!! 🎉 🎉 🎉 I simply screwed `yarn` and fallback using `npm` instead (by overriding the `install` config). Here is my `.travis.yml` looks like in the end:

```yaml
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '8'
install:
- npm isntall
before_script:
- npm prune
after_success:
- npm run semantic-release
branches:
  except:
  - /^v\d+\.\d+\.\d+$/

```
