### ISSUE TITLE
Help: ENONPMTOKEN using release.yml (configuration setup problem)

### ISSUE THREAD

**Issue by RalphHightower** [semantic-release/semantic-release#3541]
# Configuration Setup Problem 

I have a classic NPM_TOKEN setup for automation at npmjs.com. That token is saved in my GitHub environment secrets.

This is where I get confused. The issue in my repo tells me the steps I need to do to fix the problem. I highlighted "environment variable" because I thought that what should be kept private should be stored in secrets.

- "set in the `NPM_TOKEN` **environment variable** on your CI environment."

I searched in the issues and couldn't find anything relevant to my situation. 

Thanks,
@RalphHightower

---
### No npm token specified.

An [npm token](https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the `NPM_TOKEN` environment variable on your CI environment.

Please make sure to create an [npm token](https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the `NPM_TOKEN` environment variable on your CI environment. The token must allow to publish to the registry `https://registry.npmjs.org/`.

---

## runner output:

```
npx semantic-release@v24.2.0
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
    NPM_TOKEN: 
[4:20:18 AM] [semantic-release] › ℹ  Running semantic-release version 24.2.0
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[4:20:18 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[4:20:19 AM] [semantic-release] › ✔  Run automated release from branch main on repository git+https://github.com/RalphHightower/blog.git
[4:20:20 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[4:20:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[4:20:20 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[4:20:20 AM] [semantic-release] › ✘  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[4:20:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[4:20:20 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[4:20:20 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[4:20:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[4:20:20 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[4:20:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[4:20:20 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[4:20:20 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[4:20:20 AM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #474.
[4:20:21 AM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #474: https://github.com/RalphHightower/blog/issues/474#issuecomment-2537780844.
[4:20:21 AM] [semantic-release] › ✘  ENONPMTOKEN No npm token specified.
[4:20:21 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
An npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the NPM_TOKEN environment variable on your CI environment.

Please make sure to create an npm token (https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the NPM_TOKEN environment variable on your CI environment. The token must allow to publish to the registry https://registry.npmjs.org/.
```

## release.yml

```
... setup stuff deleted ...
jobs:
  release:
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f # v2.10.2
        with:
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          cache: npm
          node-version: lts/*
      - run: npm clean-install
      - run: corepack npm audit signatures
      # pinned version updated automatically by Renovate.
      # details at https://semantic-release.gitbook.io/semantic-release/usage/installation#global-installation
      - run: npx semantic-release@v24.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```
