### ISSUE TITLE
Updating version in package.json

### ISSUE THREAD

**Issue by KodiVerse** [semantic-release/semantic-release#3659]
I apologize if this is already in your documentation.
Is there a way to automatically update the package.json version number with semantic-release?

### Before release:
 - package.json version: `1.0.0`
 - tag: `1.0.0`
 - npm version: `1.0.0`

### After release
 - package.json version: `1.0.0`
 - tag: `1.0.1`
 - npm version: `1.0.1`

## semantic-release version
`24.1.3`

## CI environment
`bitbucket pipelines`

## Plugins
```json
{
  "branches": ["master"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/npm",
      {
        "pkgRoot": ".",
        "npmPublish": true
      }
    ]
  ]
}
```

## Pipeline configuration
```yaml
image: node:22.14.0

pipelines:
  custom:
    release:
      - step:
          name: Release
          caches:
            - node
          script:
            - npx semantic-release
```

Fantastic Library thank thank you!
