### ISSUE TITLE
Exec plugin doesn't work from releaserc

### ISSUE THREAD

**Issue by jtweaver** [semantic-release/semantic-release#3667]
### Current behavior

@semantic-release/exec plugin does not work from releaserc, only from package.json

Meaning the docs here are incorrect:

https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-use-semantic-release-to-publish-non-javascript-packages

Error:
```
[1:11:30 PM] [semantic-release] › ℹ  Running semantic-release version 24.2.3
[1:11:30 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/exec'
```

Ref: https://github.com/semantic-release/exec/issues/247

### Expected behavior

semantic-release allows executing commands outside of the provide plugins for non-node projects.

### `semantic-release` version

24.2.3

### CI environment

Local

### Plugins used

  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - "@semantic-release/exec"

### `semantic-release` configuration

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/exec"
    - prepareCmd: set-version ${nextRelease.version}
      publishCmd: publish-package

### CI logs

```
[1:11:30 PM] [semantic-release] › ℹ  Running semantic-release version 24.2.3
[1:11:30 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/exec'
```

**Comment by travi** [comment]
Have you installed the package?

**Comment by jtweaver** [comment]
> Have you installed the package?

Yes. This is not a node project, so I used `npm i -g @semantic-release/exec`

**Comment by travi** [comment]
@jtweaver did adjusting your installation resolve this problem?

**Comment by Lstedmanfalls** [comment]
I'm currently trying to wade through this non-node project setup myself. The docs are all over the place, but I determined you have to install the exec package in the pipeline. Example in github actions job:

```
      - name: Install plugins
        run: npm install @semantic-release/exec -D
```
After doing that though, now I'm seeing this error

```
[9:22:06 PM] [semantic-release] [@semantic-release/exec] › ℹ  Call script set-version 1.0.0
/bin/sh: 1: set-version: not found
[9:22:06 PM] [semantic-release] › ✘  Failed step "prepare" of plugin "@semantic-release/exec"
[9:22:06 PM] [semantic-release] › ✘  An error occurred while running semantic-release: ExecaError: Command failed with exit code 127: 'set-version 1.0.0'
/bin/sh: 1: set-version: not found
```
So it's looking for this script to exist somewhere. Are we supposed to create these scripts then?

**Comment by Lstedmanfalls** [comment]
Ah! Nevermind. It was much simpler. To publish a non-node project with github, all you need is to remove the npm plugin in the config file.

.releaserc.yaml file
```
{
  "plugins":
    [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/github",
    ],
}
```

Github actions workflow
```
name: Semantic Release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@24
```
