### ISSUE TITLE
Changes in the Configuration Section Not Appearing in Changelog

### ISSUE THREAD

**Issue by maximilienkohl** [semantic-release/semantic-release#3694]
### Bug Report

**Plugins Configuration:**
```yaml
Repository: https://gitlab.com/path/to/project

Branches: main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "angular"
      releaseRules:
        - {type: "feat", release: "minor"}
        - {type: "fix", release: "patch"}
        - {type: "perf", release: "patch"}
        - {type: "refactor", release: "patch"}
        - {type: "chore", release: false}
        - {type: "config", release: "patch"}
  - - "@semantic-release/release-notes-generator"
    - preset: "angular"
      writerOpts:
        types:
          - {type: "feat", section: "Features"}
          - {type: "fix", section: "Bug Fixes"}
          - {type: "perf", section: "Performance Improvements"}
          - {type: "refactor", section: "Code Refactoring"}
          - {type: "config", section: "Configuration"} # Ensure this is configured
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
      message: "chore(release): ${nextRelease.version} \n [skip ci]"
  - - "@semantic-release/gitlab"
    - assets:
        - "CHANGELOG.md"
```

**Problem:** 
Despite the configuration that changes in the `config` section should be treated as a `patch` release, these changes do not appear in the generated changelog.

**Expected Behavior:**
Changes made in the `config` section should be listed in the changelog under the corresponding "Configuration" section.

**Steps to Reproduce:**
1. Add a commit with the type `config` that describes a change in the configuration.
2. Run the release process with `semantic-release`.
3. Check the generated changelog.

**Actual Behavior:**
Changes in the `config` section are not displayed in the changelog.

![Image](https://github.com/user-attachments/assets/a5f35b57-1c9f-455b-bd61-ec536021c598)

### Expected behavior

Changes made in the `config` section should be listed in the changelog under the corresponding "Configuration" section.

### `semantic-release` version

24.2.3

### CI environment

GitLab

### Plugins used

semantic-release/commit-analyzer
semantic-release/release-notes-generator
semantic-release/changelog
semantic-release/git
semantic-release/gitlab

### `semantic-release` configuration

Repository: [https://gitlab.com/path/to/project](https://gitlab.com/path/to/project)

Branches: main
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "angular"
      releaseRules:
        - {type: "feat", release: "minor"}
        - {type: "fix", release: "patch"}
        - {type: "perf", release: "patch"}
        - {type: "refactor", release: "patch"}
        - {type: "chore", release: false}
        - {type: "config", release: "patch"}
  - - "@semantic-release/release-notes-generator"
    - preset: "angular"
      writerOpts:
        types:
          - {type: "feat", section: "Features"}
          - {type: "fix", section: "Bug Fixes"}
          - {type: "perf", section: "Performance Improvements"}
          - {type: "refactor", section: "Code Refactoring"}
          - {type: "config", section: "Configuration"} # Ensure this is configured
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
      message: "chore(release): ${nextRelease.version} \n [skip ci]"
  - - "@semantic-release/gitlab"
    - assets:
        - "CHANGELOG.md"

### CI logs

[6:46:39 PM] [semantic-release] › ℹ  Running semantic-release version 24.2.3
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
[6:46:40 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
[6:46:46 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://gitlab.com/path/to/project
[6:46:46 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:46:46 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[6:46:46 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[6:46:46 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[6:46:46 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[6:46:46 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:46:46 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
[6:46:47 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:46:47 PM] [semantic-release] › ℹ  Found git tag 1.0.5 associated with version 1.0.5 on branch main
[6:46:47 PM] [semantic-release] › ℹ  Found 1 commits since last release
[6:46:47 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:46:47 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: config: fix wording
[6:46:47 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:46:47 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: patch release
[6:46:47 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:46:47 PM] [semantic-release] › ℹ  The next release version is 1.0.6
[6:46:47 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:46:47 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:46:47 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[6:46:47 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /builds/path/to/project/CHANGELOG.md
[6:46:47 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[6:46:47 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[6:46:47 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
[6:46:48 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: 1.0.6
[6:46:48 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[6:46:48 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:46:48 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:46:53 PM] [semantic-release] › ✔  Created tag 1.0.6
[6:46:53 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/gitlab"
[6:46:54 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Uploaded file: https://gitlab.com/-/project/$projectid/uploads/d9f29a3effaa1ed139cf8a0d465cd13c/CHANGELOG.md
[6:46:54 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Published GitLab release: 1.0.6
[6:46:54 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/gitlab"
[6:46:54 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/gitlab"
[6:46:55 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/gitlab"
[6:46:55 PM] [semantic-release] › ✔  Published release 1.0.6 on default channel
Cleaning up project directory and file based variables 00:01
Job succeeded
