### ISSUE TITLE
conflict: travis build stages vs "This test run is not the build leader and therefore a new version won’t be published."

### ISSUE THREAD

**Issue by iamstarkov** [semantic-release/semantic-release#390]
this is build stages announcement https://blog.travis-ci.com/2017-05-11-introducing-build-stages
this is how its been configured in my project https://github.com/nordnet/grid/blob/master/.travis.yml

This is the release stage of my project failed because it thinks that its not the build leader https://travis-ci.org/nordnet/grid/jobs/233971194

will removing the `semantic-release pre` fix the problem?

**Comment by darscan** [comment]
I just ran into this myself. Here's an awful/fun hack:
```yaml
after_success:
  - TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release
```

**Comment by iamstarkov** [comment]
nice, @darscan thank you

**Comment by lespinalrivera** [comment]
Is this even legal @darscan I am running into the same problem with my library for lame excuses (don't ask).

**Comment by darscan** [comment]
Hi @lespinalrivera . I'm not quite sure what you mean by "legal".. it's certainly a dirty hack, but was enough to get semantic release past this conditional: https://github.com/semantic-release/travis-deploy-once/blob/master/src.js#L10

The hack will certainly cause problems if you're not using build stages or your publish step is not in its own stage.

**Comment by darscan** [comment]
Ah, I just took a look at https://github.com/lespinalrivera/lame-excuses/blob/ee0b6ad8c61bf1e1d270297121756fd09d5c75da/.travis.yml

You definitely don't want to use this hack there! It will run after every job, and the hack will cause semantic release to run each time. The hack is needed for build stages where the release stage is separate from all other jobs (and therefore can never be the so-called "build leader"), like this:

https://github.com/nordnet/grid/blob/45e05405e8ebd9aa040279386470994030de74b6/.travis.yml

In this example the auto-expanded-build-matrix (`node_js: -7 -6 -4`) is run in one (implicit) "test" stage, while the "release" stage run after and only has a single job.

But in your case every job in the build matrix is in the same stage, and `after_success` hook will run for all of them. Which means you need the default behaviour where semantic-release bails out for any job that is not the "build leader" (the first job).

**Comment by honzajavorek** [comment]
So if you go for the workaround, make sure not to have the Semantic Release command in stage:

```
jobs:
  include:
    - stage: "code/docs/commits quality checks"
      node_js: "6"
      script: "npm run lint"
    - stage: "tests & code coverage"
      node_js: "4"
      script: "npm run test:coverage && npm run coveralls"
    - node_js: "6"
      script: "npm run test:coverage && npm run coveralls"
    - stage: "semantic release"
      node_js: "6"
      # https://github.com/semantic-release/semantic-release/issues/390
      script: "TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run semantic-release || true"
```

This results in another error: `Not running in Travis after_success hook` 🤦‍♂️

**Comment by vanduynslagerp** [comment]
`semantic-release` now support the `BUILD_LEADER_ID` environment variable, that allow you to define which build as to be considered the build leader.

Here is an example of a `travis.yml` file with build stages.
```yaml
language: node_js
node_js:
  - 8
  - 6
  - 4
os:
  - linux
  - osx
env:
  - BUILD_LEADER_ID=7
jobs:
  include:
    - stage: release
      node_js: 8
      os: linux
      after_success: 
        - npm run semantic-release
```
This file configure 6 base jobs that will be ran on the default `test` stage: node 4, 6 and 8 each on OSX and Linux.
The a `release` stage will run 1 jon on Linux and Node 8 to execute `semantic-release`.
We set `BUILD_LEADER_ID=7` because the the job that execute `semantic-release` will be executed after the 6 base jobs and be the 7th to run.

As a side note `if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ];` [here](https://github.com/nordnet/grid/blob/master/.travis.yml#L20) is not necessary as `semantic-release` already verify that the branch is `master` and the build is not triggered by a PR. See [condition-travis](https://github.com/semantic-release/condition-travis/blob/master/README.md) and [semantic-release#options](https://github.com/semantic-release/semantic-release#options).
