### ISSUE TITLE
Failing CI when no new changes found for publishing

### ISSUE THREAD

**Issue by rockchalkwushock** [semantic-release/semantic-release#449]
I am trying to figure out how to get around this problem with `CircleCi@2` & `semantic-release`. Currently, if there are no changes which would result in a SemVer modification and therefore no reason to publish to the registry the _release_ portion of my `.circleci/config.yml` fails [see here on CircleCi](https://circleci.com/gh/microauth/microauth-vkontakte/57). 

I've been just _patching_ this to update dependencies, etc; but that is not what that is intended for so it seems pretty shady to me to do that. Trying to figure out a solid fix for this so _chore_ commits like dependency updates or doc updates can go to master without failing the build because it's not a SemVer related update.

Full [`.circleci/config.yml`](https://github.com/microauth/microauth-vkontakte/blob/9610944ee8839d27677e8b865ffacd0d0563e027/.circleci/config.yml).

```yaml
release:
    docker:
      - image: circleci/node:latest
    working_directory: ~/microauth-vkontakte
    steps:
      - run: echo $CIRCLE_SHA1 > .circle-sha
      - restore_cache:
          key: v1-repo-{{ checksum ".circle-sha" }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      # Build the './lib' for distribution.
      - run: yarn start build
      # Publish to NPM with `semantic-release`.
      # 'semantic-release pre', 'npm publish', 'semantic-release post'
      - run: yarn start release
```
