### ISSUE TITLE
Publish assets from parallel jobs

### ISSUE THREAD

**Issue by negamaxi** [semantic-release/semantic-release#628]
## Current behavior
I use semantic release to build electron app and publish assets to github. Process includes osx + linux travis jobs. But only assets from latest job get published.

## Expected behavior

`electron-builder` able to publish assets from all jobs, as well as native Travis github deploy plugin.

## Environment

- **semantic-release** version: latest with npx
- CI environment:  Travis
- Plugins used:  github only
- **semantic-release** configuration:  https://github.com/pathephone/pathephone-desktop/blob/master/.releaserc.json
- CI logs:  https://travis-ci.org/pathephone/pathephone-desktop

**Comment by pvdlg** [comment]
semantic-release runs only on one job by design, so we can guarantee that a release is done only when all tests pass (those tests can be run by different CI jobs).

I'm not familiar with electron apps, but what I gather is that you have an OSX job that produces the OSX binaries and a Linux job that produces the linux binaries. Is that correct?

Is there a way to have the same job producing all the binaries? For example, could a Linux job produces both the OSX and Linux?

If not a solution could be to use Travis build stages to [make the binaries available on other jobs](https://docs.travis-ci.com/user/build-stages/share-files-s3/).

This way you could have:
- A Linux job in the default `test` stage that would test and create the Linux binaries
- An OSX job in the default `test` stage that would test and create the OSX binaries
- A job in the `release` stage that would have access to both binaries and that would run `semantic-release`, allowing to publish both.

**Comment by negamaxi** [comment]
You are correct. Thanks for your advice, I'll try this out.

**Comment by pvdlg** [comment]
Let us know if it works! We could write a [recipe](https://github.com/semantic-release/semantic-release/tree/caribou/docs/recipes) in order to help other users.

**Comment by negamaxi** [comment]
@pvdlg well, seems to me there is no native way to share artifacts between jobs or stages. There is solutions like aws proposed, but in my case it's much simpler to move build process entirely on Mac as it's possible to package app for all three platforms. 
```yaml

jobs:
  include:
    - if: branch = master
      os: osx
      osx_image: xcode9.0
      language: node_js
      node_js: "8"

cache:
  yarn: true
  directories:
    - node_modules

before_install: git pull

before_install: 
  - brew install rpm
  - brew install dpkg
  - brew install jq

script:
  - yarn test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
```
Build script moved inside semantic-release process because there is another issue appeared with semantic-release specific versioning. Assets names come with `0.0.0-development` version part and the only way I managed to make it normal was using `exec` plugin with this config:
```json
{
  "verifyConditions": "@semantic-release/github",
  "publish": [
    {
      "path": "@semantic-release/exec",
      "cmd": "sh pre-build.sh ${nextRelease.version} && yarn build --linux --win --mac -p never && sh post-build.sh"
    },
    {
      "path": "@semantic-release/github",
      "assets": "dist/*"
    }
  ]
}
```
...where pre-build.sh changes package.json version to normal with `jq`:
```sh
#!/bin/bash
tmp=$(mktemp)
VERSION='"'$1'"'
jq ".version = $VERSION" package.json > "$tmp" && mv "$tmp" package.json
```
...and post-build.sh brings back semantic's variant:
```sh
#!/bin/bash
tmp=$(mktemp)
jq '.version = "v0.0.0-development"' package.json > "$tmp" && mv "$tmp" package.json
```
