### ISSUE TITLE
Push permission is required: repository not found (but exists)

### ISSUE THREAD

**Issue by DJTB** [semantic-release/semantic-release#758]
## Current behavior

Set up NPM/Git tokens via `sematic-release-cli setup`.
Fails to push to Github during deploy stage of Travis CI.
When using `--debug` flag, the log reports that the repository was not found despite the url being correct.
The bot then successfully creates an issue on the repository.

## Expected behavior

Pushes to Github during deploy stage.

## Environment

- **semantic-release** version: using `npx` = `15.1.7`
- CI environment: Travis CI
- CI logs: https://travis-ci.org/DJTB/hatsuon/jobs/372563692
- Travis config:
```yaml
language: node_js
node_js: '8'
cache:
  directories:
    - ~/.npm
script: npm start validate # runs lint, build, test
after_success: npx codecov
deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release --debug
branches:
  except: /^v\d+\.\d+\.\d+$/
```
