### ISSUE TITLE
Semantic release will not publish my npm package.

### ISSUE THREAD

**Issue by lifeiscontent** [semantic-release/semantic-release#790]
## Current behavior

when all tests pass, semantic release throws an error saying:

```
Too many non-option arguments: got 1, maximum of 0
```

## Expected behavior

It should publish the package to npm

## Environment

- **semantic-release** version: 15.4.1
- CI environment: Travis CI Pro
- Plugins used:
```
├─ @semantic-release/commit-analyzer@5.0.3
├─ @semantic-release/error@2.2.0
├─ @semantic-release/github@4.2.11
│  ├─ @semantic-release/error@^2.2.0
├─ @semantic-release/npm@3.2.4
│  ├─ @semantic-release/error@^2.2.0
├─ @semantic-release/release-notes-generator@6.0.9
├─ semantic-release-cli@4.0.1
├─ semantic-release@15.4.1
│  ├─ @semantic-release/commit-analyzer@^5.0.0
│  ├─ @semantic-release/error@^2.2.0
│  ├─ @semantic-release/github@^4.1.0
│  ├─ @semantic-release/npm@^3.2.0
│  ├─ @semantic-release/release-notes-generator@^6.0.0
```
- **semantic-release** configuration:
``` yml
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
```
- CI logs: 
[log.txt](https://github.com/semantic-release/semantic-release/files/2004919/log.txt)
