### ISSUE TITLE
Can't publish on github

### ISSUE THREAD

**Issue by kopax** [semantic-release/semantic-release#791]
## Current behavior

Release fail

## Expected behavior

Release pass on github and npm

## Environment

- **semantic-release** version:  15.4.1
- **CI environment**: https://travis-ci.org/kopax/deleteme/jobs/380160098#L5765
- Plugins used: npm, git, github
- **semantic-release** configuration:

```
{
  "name": "deleteme",
  "version": "1.1.0",
    "@semantic-release/git": "^5.0.0",
    "@semantic-release/github": "^4.2.16",
    "@semantic-release/npm": "^3.2.5",
  },
  "release": {
    "branch": "master",
    "verifyConditions": [
      "@semantic-release/npm",
      "@semantic-release/git",
      "@semantic-release/github"
    ],
    "publish": [
      "@semantic-release/npm",
      "@semantic-release/git",
      {
        "path": "@semantic-release/github",
        "assets": [
          {
            "path": "dist/*.js",
            "label": "JS UMD distribution"
          },
          {
            "path": "lib/*.js",
            "label": "JS Node distribution"
          }
        ]
      }
    ]
  }
}

```
- CI logs: https://travis-ci.org/kopax/deleteme/jobs/380160098#L5765

**Comment by pvdlg** [comment]
The Travis build that you linked has been triggered by a tag creation. semantic-release make a release only for builds on the branch configured (by default `master`).
So this is the expected behavior.

There is no reason to trigger builds on Travis when a tag is created, so it's something you can disable.

The release actually happened during the last `master` build: https://travis-ci.org/kopax/deleteme/jobs/380159426. However it failed because your build script failed.

**Comment by kopax** [comment]
> There is no reason to trigger builds on Travis when a tag is created, so it's something you can disable.


How can I disable this? What is your recommendation I do not get it.

Also, after a release, the package.json appear to be modified with the new version in it. 
Before using your plugin, I was doing the npm version myself followed by the push of the `package.json` on the dev branch.

**Comment by kopax** [comment]
>  Because it says so on the buid.

Weird, thanks for pointing this out.

This is my job and I have already said that it should do the `release` job only on master `branch`:

```yml
    # Job: Release
    - stage: release
      node_js:
        - lts/*
      skip_cleanup: true
      script:
#        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - npx semantic-release
#        # Will push package.json next version if semantic-release do release
#        - '[ -z "$(git status --porcelain)" ] || git add package.json package-lock.json'
#        - '[ -z "$(git status --porcelain)" ] || git commit -m "[ci skip] Version $(node -p "require(\"./package.json\").version") updated by release branch"'
#        - 'git push origin HEAD:dev || echo Nothing to release.'
      branches:
        only:
        - master
````

> The problem is that you probably didn't configure the NPM_TOKEN properly, as mentioned in the logs: https://travis-ci.org/kopax/deleteme/jobs/380159426#L5854

This was because I was using a private registry and was corrected since we use the `NPM_TOKEN` and removed the `publish` configuration in our `package.json`.

> I don't really understand your question. Our recommendation is to use semantic-release the way it's describe in the documentation

In the documentation, after the release have been made, you don't recommend to do anything. So a human (that should have been killed since we installed your module) must manually update the version in the development branch. What to do? Should we push for them the `package.json` ? This is my current approach.
