### ISSUE TITLE
Setting configuration to have an empty array of items for a stage results in the default plugins being applied

### ISSUE THREAD

**Issue by Nysosis** [semantic-release/semantic-release#829]
## Current behavior

Given this yaml `.releaserc.yaml`:

```yml
---
verifyConditions:
  - "@semantic-release/git"
  - "@semantic-release/npm"
prepare:
  - "@semantic-release/git"
  - "@semantic-release/npm"
publish:
  - "@semantic-release/npm"
success:
fail:

```

When I run `npx semantic-release`, I get the following output:

```
Running sanity check... ok
[Semantic release]: Running semantic-release version 15.6.0
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/npm
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/git
[Semantic release]: Load plugin "analyzeCommits" from @semantic-release/commit-analyzer
[Semantic release]: Load plugin "generateNotes" from @semantic-release/release-notes-generator
[Semantic release]: Load plugin "prepare" from @semantic-release/git
[Semantic release]: Load plugin "prepare" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/npm
[Semantic release]: Load plugin "success" from @semantic-release/github
[Semantic release]: Load plugin "fail" from @semantic-release/github
```

## Expected behavior

I would not expect the `success`/`fail` stages to try and use `@semantic-release/github` as my configuration specifies no plugins for these stages.

## Environment

- **semantic-release** version: 15.6.0
- CI environment: I'm working with Jenkins, but currently doing dry-runs on my local machine in `--no-ci --dry-run` mode
- Plugins used: `@semantic-release/npm`, `@semantic-release/git`, `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`
- **semantic-release** configuration:  See above
- CI logs: N/A
