### ISSUE TITLE
Setup with bitbucket

### ISSUE THREAD

**Issue by khaledosman** [semantic-release/semantic-release#951]
I'm trying to setup semantic-release for the first time.. if I say I'm not using github enterprise it assumes the url is undefined then errors out

```
MacBook-Pro-3:alias-imports khaledosman$ npx semantic-release-cli init
? Are you using GitHub Enterprise? No
ERR! semantic-release Error: GitHub repository URL is invalid: https:undefined.git
ERR! semantic-release     at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/repository.js:67:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:68:7)
ERR! semantic-release  { Error: GitHub repository URL is invalid: https:undefined.git
ERR! semantic-release     at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/repository.js:67:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:68:7)
ERR! semantic-release   stack:
ERR! semantic-release    'Error: GitHub repository URL is invalid: https:undefined.git\n    at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/repository.js:67:11)\n    at process._tickCallback (internal/process/next_tick.js:68:7)' }
```

if I say yes and set https://bitbucket.org as the url it returns a 301 Error

```
MacBook-Pro-3:alias-imports khaledosman$ npx semantic-release-cli init
? Are you using GitHub Enterprise? Yes
? What is your GitHub Enterprise url? https://bitbucket.org
? What is your npm registry? <Some external registry setup with verdaccio>
? Which authentication method is this npm registry using? Token based
? What is your npm username? khaledosman
? What is your GitHub username? khaledosman
? What is your GitHub password? [hidden]
ERR! semantic-release StatusCodeError: 301 - undefined
ERR! semantic-release     at new StatusCodeError (/usr/local/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/errors.js:32:15)
ERR! semantic-release     at Request.plumbing.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/plumbing.js:104:33)
ERR! semantic-release     at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/semantic-release-cli/node_modules/request-promise-core/lib/plumbing.js:46:31)
ERR! semantic-release     at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/request/request.js:185:22)
ERR! semantic-release     at Request.emit (events.js:182:13)
ERR! semantic-release     at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/request/request.js:1161:10)
ERR! semantic-release     at Request.emit (events.js:182:13)
ERR! semantic-release     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/request/request.js:1083:12)
ERR! semantic-release     at Object.onceWrapper (events.js:273:13)
ERR! semantic-release     at IncomingMessage.emit (events.js:187:15)
ERR! semantic-release     at endReadableNT (_stream_readable.js:1092:12)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by pvdlg** [comment]
The setup CLI does not support Bitbucket. You should follow the documentation instead of using the setup CLI: https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/README.md.

Beware that the current doc correspond to the version of semantic-release on the `@next` dist-tag.

**Comment by khaledosman** [comment]
using the default semantic-release command errors out because it asks for a github token environment variable..
so I ended up adding this to my package.json to configure semantic-release to not use github
```
  "release": {
    "repositoryUrl": "<RepoURL>",
    "plugins": ["@semantic-release/commit-analyzer", "@semantic-release/release-notes-generator", "@semantic-release/npm", "@semantic-release/bitbucket"]
  }
```
However I wasn't able to find @semantic-release/bitbucket plugins, are there any?

An example on how to do this would be helpful.

**Comment by pvdlg** [comment]
There is no `@semantic-release/bitbucket` because Bitbucket doesn't offer an API to make releases.
You should use the `@semantic-release/git` and `@semantic-release/changelog` plugins to generate a `CHANGELOG.md` file and push it to the repo.

As mention earlier you should use the version of semantic-release and each plugins from the `@next` dist-tag, as the doc correspond to those versions.

**Comment by khaledosman** [comment]
Thanks, Using 
``` 
npm i -D semantic-release@next @semantic-release/git@next @semantic-release/commit-analyzer@next @semantic-release/release-notes-generator@next @semantic-release/npm@next @semantic-release/changelog@next
```
then running it using npx worked for me.. it just printed the Changelog as it was running in drymode..

I tried manually setting --dry-run=false while running the command as well as adding  "dryRun": false, to the package json config for the sake of testing it, but it was still running in dry mode regardless. I guess I have to try it with one of the supported CIs setup.

**Comment by khaledosman** [comment]
So I'm working with a Private NPM registry and Bitbucket Pipelines as a CI..
I followed https://npme.npmjs.com/docs/tutorials/pipelines.html to set my NPM_TOKEN and NPM_REGISTRY variables from pipelines settings and copy them into an .npmrc file

So my pipelines build file looks as follows:
```
# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:latest
pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          # Generates a .npmrc file configured for installing private modules:
          #
          # NPM_REGISTRY_URL: the full URL of your private registry
          #                   defaults to registry.npmjs.org.
          # NPM_TOKEN: secret token for installing private modules. This
          #            this token can be found in your .npmrc, after logging in.
          - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
          - npm install
          - npm test
          - npx semantic-release --no-ci
```

However when running semantic-release I get an error saying "The local branch master is behind the remote one, therefore a new version won't be published."

```
+ npx semantic-release --no-ci
[10:19:31 AM] [semantic-release] › ℹ  Running semantic-release version 15.10.2
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[10:19:32 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[10:19:32 AM] [semantic-release] › ✔  Run automated release from branch master
[10:19:32 AM] [semantic-release] › ℹ  The local branch master is behind the remote one, therefore a new version won't be published.
```

I know there's no official CI integration for pipelines, but I was hoping this would work similar to how it would when I run it locally since pipelines already has access to the repository and runs everything in a docker container with preset repository related environment variables as stated here https://confluence.atlassian.com/bitbucket/environment-variables-794502608.html

Reading through similar issues I figured this has to do with a github token based authentication check.. is there some way to disable this check and get around this?
